#!/bin/sh

# Build a local version of octave-cli from the development sources:
#   hg clone https://www.octave.org/hg/octave
#   pushd octave
#   hg pull
#   hg update
#   ./bootstrap
#   popd
#
# Require Fedora packages: wget readline-devel lzip sharutils gcc gcc-c++
# gcc-gfortran gmp-devel mpfr-devel make cmake gnuplot-latex m4 gperf 
# bison flex openblas-devel patch texinfo texinfo-tex librsvg2 librsvg2-devel
# librsvg2-tools icoutils autoconf automake libtool pcre pcre-devel freetype
# freetype-devel gnupg2 texlive-dvisvgm
# hdf5 hdf5-devel qt qscintilla-qt5 qscintilla-qt5-devel rapidjson-devel
# qhull qhull-devel portaudio portaudio-devel libsndfile libsndfile-devel
# libcurl libcurl-devel gl2ps gl2ps-devel fontconfig-devel mesa-libGLU
# mesa-libGLU-devel qt5-qttools qt5-qttools-common qt5-qttools-devel
#
# See https://wiki.octave.org/GraphicsMagick for GraphicksMagic dependencies
#
# SuiteSparse requires extra definitions to install other than at /usr/local
#
# Octave-forge packages don't install at the prefix when the user is not root.
#
# From the fftw-3.3.8 release notes (May 28th, 2018):
#    Fixed AVX, AVX2 for gcc-8.
#      By default, FFTW 3.3.7 was broken with gcc-8. AVX and AVX2 code
#      assumed that the compiler honors the distinction between +0 and -0,
#      but gcc-8 -ffast-math does not. The default CFLAGS included
#      -ffast-math . This release ensures that FFTW works with gcc-8
#      -ffast-math , and removes -ffast-math from the default CFLAGS for
#      good measure.
# 
# Get the GNU octave public keys with:
#    wget https://ftp.gnu.org/gnu/gnu-keyring.gpg
#    gpg2 --import gnu-keyring.gpg
# then verify the .sig file with (for example):
#    gpg2 --verify octave-6.2.0.tar.lz.sig
#
# Note the worrying error from Octave-forge package control-3.2.0.tar.gz in
# the FORTRAN file from slicot.tar.gz, MA02ID.f at lines 188 and 230:
# 
#   184 |          DO 90 J = 1, N+1
#       |                                                                     2
# ......
#   188 |                DWORK(J-1) = DWORK(J-1) + TEMP
#       |                     1
# Warning: Array reference at (1) out of bounds (0 < 1) in loop beginning at (2)

#
# Produce code for Intel nehalem CPU. If necessary replace with mtune=generic
#
OPTFLAGS="-m64 -march=nehalem -O2"

#
# Assume these files are present. Get them if they are not.
#

#
# Get Octave archive
#
OCTAVE_VER=8.0.0

#
# Set Octave directories
#
OCTAVE_DIR="/usr/local/octave-"$OCTAVE_VER
OCTAVE_INCLUDE_DIR=$OCTAVE_DIR/include
OCTAVE_LIB_DIR=$OCTAVE_DIR/lib
OCTAVE_BIN_DIR=$OCTAVE_DIR/bin
OCTAVE_SHARE_DIR=$OCTAVE_DIR/share/octave
export LD_LIBRARY_PATH=$OCTAVE_LIB_DIR
export LDFLAGS=-L$OCTAVE_LIB_DIR
export PATH=$PATH:$OCTAVE_BIN_DIR

#
# Get library archives
#
LAPACK_VER=${LAPACK_VER:-3.10.0}
LAPACK_ARCHIVE=lapack-$LAPACK_VER".tar.gz"
LAPACK_URL=http://github.com/Reference-LAPACK/lapack/archive/v$LAPACK_VER.tar.gz
if ! test -f $LAPACK_ARCHIVE; then
  wget -c $LAPACK_URL -O $LAPACK_ARCHIVE
fi

ARPACK_ARCHIVE=arpack-ng-master.zip
ARPACK_URL=https://github.com/opencollab/arpack-ng/archive/master.zip
if ! test -f $ARPACK_ARCHIVE; then
  wget -c $ARPACK_URL -O $ARPACK_ARCHIVE
fi

SUITESPARSE_VER=${SUITESPARSE_VER:-5.10.1}
SUITESPARSE_ARCHIVE=SuiteSparse-$SUITESPARSE_VER".tar.gz"
SUITESPARSE_URL=https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v$SUITESPARSE_VER".tar.gz"
if ! test -f $SUITESPARSE_ARCHIVE; then
  wget -c $SUITESPARSE_URL -O $SUITESPARSE_ARCHIVE
fi

QRUPDATE_VER=${QRUPDATE_VER:-1.1.2}
QRUPDATE_ARCHIVE=qrupdate-$QRUPDATE_VER".tar.gz"
QRUPDATE_URL=https://sourceforge.net/projects/qrupdate/files/qrupdate/1.2/$QRUPDATE_ARCHIVE
if ! test -f $QRUPDATE_ARCHIVE; then
  wget -c $QRUPDATE_URL
fi

FFTW_VER=${FFTW_VER:-3.3.10}
FFTW_ARCHIVE=fftw-$FFTW_VER".tar.gz"
FFTW_URL=ftp://ftp.fftw.org/pub/fftw/$FFTW_ARCHIVE
if ! test -f $FFTW_ARCHIVE; then
  wget -c $FFTW_URL
fi

GLPK_VER=${GLPK_VER:-5.0}
GLPK_ARCHIVE=glpk-$GLPK_VER".tar.gz"
GLPK_URL=https://ftp.gnu.org/gnu/glpk/$GLPK_ARCHIVE
if ! test -f $GLPK_ARCHIVE; then
  wget -c $GLPK_URL
fi

SUNDIALS_VER=${SUNDIALS_VER:-5.8.0}
SUNDIALS_ARCHIVE=sundials-$SUNDIALS_VER".tar.gz"
SUNDIALS_URL=https://github.com/LLNL/sundials/releases/download/v$SUNDIALS_VER/$SUNDIALS_ARCHIVE
if ! test -f $SUNDIALS_ARCHIVE; then
  wget -c $SUNDIALS_URL
fi

GRAPHICSMAGICK_VER=${GRAPHICSMAGICK_VER:-1.3.37}
GRAPHICSMAGICK_ARCHIVE=GraphicsMagick-$GRAPHICSMAGICK_VER".tar.xz"
GRAPHICSMAGICK_URL=https://ixpeering.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/$GRAPHICSMAGICK_VER/$GRAPHICSMAGICK_ARCHIVE
if ! test -f $GRAPHICSMAGICK_ARCHIVE; then
  wget -c $GRAPHICSMAGICK_URL
fi


#
# Get octave-forge packages
#
OCTAVE_FORGE_URL=https://sourceforge.net/projects/octave/files/\
Octave%20\Forge%20Packages/Individual%20Package%20Releases/

IO_VER=${IO_VER:-2.6.4}
IO_ARCHIVE=io-$IO_VER".tar.gz"
IO_URL=$OCTAVE_FORGE_URL$IO_ARCHIVE
if ! test -f $IO_ARCHIVE; then
    wget -c $IO_URL
fi

STATISTICS_VER=${STATISTICS_VER:-1.4.3}
STATISTICS_ARCHIVE=statistics-$STATISTICS_VER".tar.gz"
STATISTICS_URL=$OCTAVE_FORGE_URL$STATISTICS_ARCHIVE
if ! test -f $STATISTICS_ARCHIVE; then
    wget -c $STATISTICS_URL
fi

STRUCT_VER=${STRUCT_VER:-1.0.17}
STRUCT_ARCHIVE=struct-$STRUCT_VER".tar.gz"
STRUCT_URL=$OCTAVE_FORGE_URL$STRUCT_ARCHIVE
if ! test -f $STRUCT_ARCHIVE; then
    wget -c $STRUCT_URL 
fi

OPTIM_VER=${OPTIM_VER:-1.6.1}
OPTIM_ARCHIVE=optim-$OPTIM_VER".tar.gz"
OPTIM_URL=$OCTAVE_FORGE_URL$OPTIM_ARCHIVE
if ! test -f $OPTIM_ARCHIVE; then
    wget -c $OPTIM_URL 
fi

CONTROL_VER=${CONTROL_VER:-3.3.1}
CONTROL_ARCHIVE=control-$CONTROL_VER".tar.gz"
CONTROL_URL=$OCTAVE_FORGE_URL$CONTROL_ARCHIVE
if ! test -f $CONTROL_ARCHIVE; then
    wget -c $CONTROL_URL 
fi

SIGNAL_VER=${SIGNAL_VER:-1.4.1}
SIGNAL_ARCHIVE=signal-$SIGNAL_VER".tar.gz"
SIGNAL_URL=$OCTAVE_FORGE_URL$SIGNAL_ARCHIVE
if ! test -f $SIGNAL_ARCHIVE; then
    wget -c $SIGNAL_URL 
fi

PARALLEL_VER=${PARALLEL_VER:-4.0.1}
PARALLEL_ARCHIVE=parallel-$PARALLEL_VER".tar.gz"
PARALLEL_URL=$OCTAVE_FORGE_URL$PARALLEL_ARCHIVE
if ! test -f $PARALLEL_ARCHIVE; then
    wget -c $PARALLEL_URL 
fi

SYMBOLIC_VER=${SYMBOLIC_VER:-2.9.0}
SYMBOLIC_ARCHIVE=symbolic-$SYMBOLIC_VER".tar.gz"
SYMBOLIC_URL=$OCTAVE_FORGE_URL$SYMBOLIC_ARCHIVE
if ! test -f $SYMBOLIC_ARCHIVE; then
    wget -c $SYMBOLIC_URL 
fi

#
# !?!WARNING!?!
#
# Starting from scratch!
#
rm -Rf $OCTAVE_DIR
echo "Building octave-"$OCTAVE_VER

#
# Build lapack
#
rm -Rf lapack-$LAPACK_VER
tar -xf $LAPACK_ARCHIVE
cat > lapack-$LAPACK_VER".patch.uue" << 'EOF'
begin-base64 644 lapack-3.10.0.patch
RmlsZXMgbGFwYWNrLTMuMTAuMC5vcmlnL1NSQy9NYWtlZmlsZSBhbmQgbGFw
YWNrLTMuMTAuMC9TUkMvTWFrZWZpbGUgZGlmZmVyCi0tLSBsYXBhY2stMy4x
MC4wLm9yaWcvU1JDL01ha2VmaWxlCTIwMjEtMDYtMjkgMDI6Mzk6MTIuMDAw
MDAwMDAwICsxMDAwCisrKyBsYXBhY2stMy4xMC4wL1NSQy9NYWtlZmlsZQky
MDIxLTA5LTIwIDEyOjQxOjAyLjkxMjc4NjYzOCArMTAwMApAQCAtNTU2LDYg
KzU1Niw5IEBACiAJJChBUikgJChBUkZMQUdTKSAkQCAkXgogCSQoUkFOTElC
KSAkQAogCiskKG5vdGRpciAkKExBUEFDS0xJQjolLmE9JS5zbykpOiAkKEFM
TE9CSikgJChBTExYT0JKKSAkKERFUFJFQ0FURUQpCisJJChGQykgLXNoYXJl
ZCAtV2wsLXNvbmFtZSwkQCAtbyAkQCAkXgorCiAuUEhPTlk6IHNpbmdsZSBj
b21wbGV4IGRvdWJsZSBjb21wbGV4MTYKIAogU0lOR0xFX0RFUFMgOj0gJChT
TEFTUkMpICQoRFNMQVNSQykKRmlsZXMgbGFwYWNrLTMuMTAuMC5vcmlnL0JM
QVMvU1JDL01ha2VmaWxlIGFuZCBsYXBhY2stMy4xMC4wL0JMQVMvU1JDL01h
a2VmaWxlIGRpZmZlcgotLS0gbGFwYWNrLTMuMTAuMC5vcmlnL0JMQVMvU1JD
L01ha2VmaWxlCTIwMjEtMDYtMjkgMDI6Mzk6MTIuMDAwMDAwMDAwICsxMDAw
CisrKyBsYXBhY2stMy4xMC4wL0JMQVMvU1JDL01ha2VmaWxlCTIwMjEtMDkt
MjAgMTI6NDE6MDIuOTE1Nzg2NjEwICsxMDAwCkBAIC0xNDksNiArMTQ5LDkg
QEAKIAkkKEFSKSAkKEFSRkxBR1MpICRAICReCiAJJChSQU5MSUIpICRACiAK
KyQobm90ZGlyICQoQkxBU0xJQjolLmE9JS5zbykpOiAkKEFMTE9CSikKKwkk
KEZDKSAtc2hhcmVkIC1XbCwtc29uYW1lLCRAIC1vICRAICReCisKIC5QSE9O
WTogc2luZ2xlIGRvdWJsZSBjb21wbGV4IGNvbXBsZXgxNgogc2luZ2xlOiAk
KFNCTEFTMSkgJChBTExCTEFTKSAkKFNCTEFTMikgJChTQkxBUzMpCiAJJChB
UikgJChBUkZMQUdTKSAkKEJMQVNMSUIpICReCkZpbGVzIGxhcGFjay0zLjEw
LjAub3JpZy9tYWtlLmluYy5leGFtcGxlIGFuZCBsYXBhY2stMy4xMC4wL21h
a2UuaW5jLmV4YW1wbGUgZGlmZmVyCi0tLSBsYXBhY2stMy4xMC4wLm9yaWcv
bWFrZS5pbmMuZXhhbXBsZQkyMDIxLTA2LTI5IDAyOjM5OjEyLjAwMDAwMDAw
MCArMTAwMAorKysgbGFwYWNrLTMuMTAuMC9tYWtlLmluYy5leGFtcGxlCTIw
MjEtMDktMjAgMTI6NDE6MDIuOTExNzg2NjQ3ICsxMDAwCkBAIC03LDcgKzcs
OCBAQAogIyAgQ0MgaXMgdGhlIEMgY29tcGlsZXIsIG5vcm1hbGx5IGludm9r
ZWQgd2l0aCBvcHRpb25zIENGTEFHUy4KICMKIENDID0gZ2NjCi1DRkxBR1Mg
PSAtTzMKK0JMRE9QVFMgPSAtZlBJQyAtbTY0IC1tYXJjaD1uZWhhbGVtCitD
RkxBR1MgPSAtTzMgJChCTERPUFRTKQogCiAjICBNb2RpZnkgdGhlIEZDIGFu
ZCBGRkxBR1MgZGVmaW5pdGlvbnMgdG8gdGhlIGRlc2lyZWQgY29tcGlsZXIK
ICMgIGFuZCBkZXNpcmVkIGNvbXBpbGVyIG9wdGlvbnMgZm9yIHlvdXIgbWFj
aGluZS4gIE5PT1BUIHJlZmVycyB0bwpAQCAtMTcsMTAgKzE4LDEwIEBACiAj
ICBhbmQgaGFuZGxlIHRoZXNlIHF1YW50aXRpZXMgYXBwcm9wcmlhdGVseS4g
QXMgYSBjb25zZXF1ZW5jZSwgb25lCiAjICBzaG91bGQgbm90IGNvbXBpbGUg
TEFQQUNLIHdpdGggZmxhZ3Mgc3VjaCBhcyAtZmZwZS10cmFwPW92ZXJmbG93
LgogIwotRkMgPSBnZm9ydHJhbgotRkZMQUdTID0gLU8yIC1mcmVjdXJzaXZl
CitGQyA9IGdmb3J0cmFuIC1mcmVjdXJzaXZlICQoQkxET1BUUykKK0ZGTEFH
UyA9IC1PMiAKIEZGTEFHU19EUlYgPSAkKEZGTEFHUykKLUZGTEFHU19OT09Q
VCA9IC1PMCAtZnJlY3Vyc2l2ZQorRkZMQUdTX05PT1BUID0gLU8wCiAKICMg
IERlZmluZSBMREZMQUdTIHRvIHRoZSBkZXNpcmVkIGxpbmtlciBvcHRpb25z
IGZvciB5b3VyIG1hY2hpbmUuCiAjCkBAIC01NSw3ICs1Niw3IEBACiAjICBV
bmNvbW1lbnQgdGhlIGZvbGxvd2luZyBsaW5lIHRvIGluY2x1ZGUgZGVwcmVj
YXRlZCByb3V0aW5lcyBpbgogIyAgdGhlIExBUEFDSyBsaWJyYXJ5LgogIwot
I0JVSUxEX0RFUFJFQ0FURUQgPSBZZXMKK0JVSUxEX0RFUFJFQ0FURUQgPSBZ
ZXMKIAogIyAgTEFQQUNLRSBoYXMgdGhlIGludGVyZmFjZSB0byBzb21lIHJv
dXRpbmVzIGZyb20gdG1nbGliLgogIyAgSWYgTEFQQUNLRV9XSVRIX1RNRyBp
cyBkZWZpbmVkLCBhZGQgdGhvc2Ugcm91dGluZXMgdG8gTEFQQUNLRS4KQEAg
LTc0LDcgKzc1LDcgQEAKICMgIG1hY2hpbmUtc3BlY2lmaWMsIG9wdGltaXpl
ZCBCTEFTIGxpYnJhcnkgc2hvdWxkIGJlIHVzZWQgd2hlbmV2ZXIKICMgIHBv
c3NpYmxlLikKICMKLUJMQVNMSUIgICAgICA9ICQoVE9QU1JDRElSKS9saWJy
ZWZibGFzLmEKK0JMQVNMSUIgICAgICA9ICQoVE9QU1JDRElSKS9saWJibGFz
LmEKIENCTEFTTElCICAgICA9ICQoVE9QU1JDRElSKS9saWJjYmxhcy5hCiBM
QVBBQ0tMSUIgICAgPSAkKFRPUFNSQ0RJUikvbGlibGFwYWNrLmEKIFRNR0xJ
QiAgICAgICA9ICQoVE9QU1JDRElSKS9saWJ0bWdsaWIuYQo=
====
EOF

# Patch
uudecode lapack-$LAPACK_VER".patch.uue"
tar -xf $LAPACK_ARCHIVE
pushd lapack-$LAPACK_VER
patch -p1 < ../lapack-$LAPACK_VER".patch"
mv -f make.inc.example make.inc
popd
# Make libblas.so
pushd lapack-$LAPACK_VER/BLAS/SRC
make -j 6 libblas.so
popd
# Make liblapack.so
pushd lapack-$LAPACK_VER/SRC
make -j 6 liblapack.so
popd
# Install
mkdir -p $OCTAVE_LIB_DIR
pushd lapack-$LAPACK_VER/BLAS/SRC
cp libblas.so $OCTAVE_LIB_DIR
popd
pushd lapack-$LAPACK_VER/SRC
cp liblapack.so $OCTAVE_LIB_DIR
popd
rm -Rf lapack-$LAPACK_VER
rm -f lapack-$LAPACK_VER".patch" lapack-$LAPACK_VER".patch.uue"

#
# Build arpack
#
rm -Rf arpack-ng-master
unzip $ARPACK_ARCHIVE
pushd arpack-ng-master
sh ./bootstrap
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS \
LDFLAGS=-L$OCTAVE_LIB_DIR F77=gfortran \
./configure --prefix=$OCTAVE_DIR --with-blas=-lblas --with-lapack=-llapack
make && make install
popd
rm -Rf arpack-ng-master

#
# Build SuiteSparse
#
rm -Rf SuiteSparse-$SUITESPARSE_VER
tar -xf $SUITESPARSE_ARCHIVE
# Building GraphBLAS is very slow so dont
cat > SuiteSparse-$SUITESPARSE_VER".patch.uue" << 'EOF'
begin-base64 644 SuiteSparse-5.10.1.patch
LS0tIFN1aXRlU3BhcnNlLTUuMTAuMS5vcmlnL01ha2VmaWxlCTIwMjEtMDUt
MTggMjM6MDE6MTYuMDAwMDAwMDAwICsxMDAwCisrKyBTdWl0ZVNwYXJzZS01
LjEwLjEvTWFrZWZpbGUJMjAyMS0wOS0yMCAxMjozNToyMS40NDM5NzQ4Nzcg
KzEwMDAKQEAgLTM0LDcgKzM0LDcgQEAKIAkoIGNkIEdQVVFSRW5naW5lICYm
ICQoTUFLRSkgKQogZW5kaWYKIAkoIGNkIFNQUVIgJiYgJChNQUtFKSApCi0J
KCBjZCBHcmFwaEJMQVMgJiYgJChNQUtFKSBKT0JTPSQoSk9CUykgQ01BS0Vf
T1BUSU9OUz0nJChDTUFLRV9PUFRJT05TKScgKQorIwkoIGNkIEdyYXBoQkxB
UyAmJiAkKE1BS0UpIEpPQlM9JChKT0JTKSBDTUFLRV9PUFRJT05TPSckKENN
QUtFX09QVElPTlMpJyApCiAJKCBjZCBTTElQX0xVICYmICQoTUFLRSkgKQog
IwkoIGNkIFBJUk9fQkFORCAmJiAkKE1BS0UpICkKICMJKCBjZCBTS1lMSU5F
X1NWRCAmJiAkKE1BS0UpICkKQEAgLTYzLDcgKzYzLDcgQEAKIAkoIGNkIEdQ
VVFSRW5naW5lICYmICQoTUFLRSkgaW5zdGFsbCApCiBlbmRpZgogCSggY2Qg
U1BRUiAmJiAkKE1BS0UpIGluc3RhbGwgKQotCSggY2QgR3JhcGhCTEFTICYm
ICQoTUFLRSkgSk9CUz0kKEpPQlMpIENNQUtFX09QVElPTlM9JyQoQ01BS0Vf
T1BUSU9OUyknIGluc3RhbGwgKQorIwkoIGNkIEdyYXBoQkxBUyAmJiAkKE1B
S0UpIEpPQlM9JChKT0JTKSBDTUFLRV9PUFRJT05TPSckKENNQUtFX09QVElP
TlMpJyBpbnN0YWxsICkKICMJKCBjZCBQSVJPX0JBTkQgJiYgJChNQUtFKSBp
bnN0YWxsICkKICMJKCBjZCBTS1lMSU5FX1NWRCAmJiAkKE1BS0UpIGluc3Rh
bGwgKQogCSggY2QgU0xJUF9MVSAmJiAkKE1BS0UpIGluc3RhbGwgKQpAQCAt
MTQ0LDcgKzE0NCw3IEBACiAJKCBjZCBHUFVRUkVuZ2luZSAmJiAkKE1BS0Up
IGxpYnJhcnkgKQogZW5kaWYKIAkoIGNkIFNQUVIgJiYgJChNQUtFKSBsaWJy
YXJ5ICkKLQkoIGNkIEdyYXBoQkxBUyAmJiAkKE1BS0UpIEpPQlM9JChKT0JT
KSBDTUFLRV9PUFRJT05TPSckKENNQUtFX09QVElPTlMpJyBsaWJyYXJ5ICkK
KyMJKCBjZCBHcmFwaEJMQVMgJiYgJChNQUtFKSBKT0JTPSQoSk9CUykgQ01B
S0VfT1BUSU9OUz0nJChDTUFLRV9PUFRJT05TKScgbGlicmFyeSApCiAJKCBj
ZCBTTElQX0xVICYmICQoTUFLRSkgbGlicmFyeSApCiAjCSggY2QgUElST19C
QU5EICYmICQoTUFLRSkgbGlicmFyeSApCiAjCSggY2QgU0tZTElORV9TVkQg
JiYgJChNQUtFKSBsaWJyYXJ5ICkKQEAgLTE3Miw3ICsxNzIsNyBAQAogCSgg
Y2QgR1BVUVJFbmdpbmUgJiYgJChNQUtFKSBzdGF0aWMgKQogZW5kaWYKIAko
IGNkIFNQUVIgJiYgJChNQUtFKSBzdGF0aWMgKQotCSggY2QgR3JhcGhCTEFT
ICYmICQoTUFLRSkgSk9CUz0kKEpPQlMpIENNQUtFX09QVElPTlM9JyQoQ01B
S0VfT1BUSU9OUyknIHN0YXRpYyApCisjCSggY2QgR3JhcGhCTEFTICYmICQo
TUFLRSkgSk9CUz0kKEpPQlMpIENNQUtFX09QVElPTlM9JyQoQ01BS0VfT1BU
SU9OUyknIHN0YXRpYyApCiAJKCBjZCBTTElQX0xVICYmICQoTUFLRSkgc3Rh
dGljICkKICMJKCBjZCBQSVJPX0JBTkQgJiYgJChNQUtFKSBzdGF0aWMgKQog
IwkoIGNkIFNLWUxJTkVfU1ZEICYmICQoTUFLRSkgc3RhdGljICkKQEAgLTIz
Myw3ICsyMzMsNyBAQAogCiAjIENyZWF0ZSB0aGUgUERGIGRvY3VtZW50YXRp
b24KIGRvY3M6Ci0JKCBjZCBHcmFwaEJMQVMgJiYgJChNQUtFKSBkb2NzICkK
KyMJKCBjZCBHcmFwaEJMQVMgJiYgJChNQUtFKSBkb2NzICkKIAkoIGNkIE1v
bmdvb3NlICAmJiAkKE1BS0UpIGRvY3MgKQogCSggY2QgQU1EICYmICQoTUFL
RSkgZG9jcyApCiAJKCBjZCBDQU1EICYmICQoTUFLRSkgZG9jcyApCg==
====
EOF
uudecode SuiteSparse-$SUITESPARSE_VER".patch.uue"
pushd SuiteSparse-$SUITESPARSE_VER
patch -p 1 < ../SuiteSparse-$SUITESPARSE_VER".patch"
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS make -j 6 \
      INSTALL=$OCTAVE_DIR OPTIMIZATION=-O2 BLAS=-lblas LAPACK=-llapack install
popd
rm -Rf SuiteSparse-$SUITESPARSE_VER
rm -f SuiteSparse-$SUITESPARSE_VER".patch"
rm -f SuiteSparse-$SUITESPARSE_VER".patch".uue

#
# Build qrupdate
#
rm -Rf qrupdate-$QRUPDATE_VER
tar -xf $QRUPDATE_ARCHIVE
pushd qrupdate-$QRUPDATE_VER
rm -f Makeconf
cat > Makeconf << 'EOF'
FC=gfortran
FFLAGS=-fimplicit-none -funroll-loops -m64 -march=nehalem -O2
FPICFLAGS=-fPIC

ifeq ($(strip $(PREFIX)),)
  PREFIX=/usr/local
endif

BLAS=-L$(PREFIX)/lib -lblas
LAPACK=-L$(PREFIX)/lib -llapack

VERSION=1.1
MAJOR=1
LIBDIR=lib
DESTDIR=
EOF
make PREFIX=$OCTAVE_DIR solib install
popd
rm -Rf qrupdate-$QRUPDATE_VER

#
# Build glpk
#
rm -Rf glpk-$GLPK_VER
tar -xf $GLPK_ARCHIVE
pushd glpk-$GLPK_VER
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS \
./configure --prefix=$OCTAVE_DIR
make -j 6 && make install
popd
rm -Rf glpk-$GLPK_VER

#
# Build fftw
#
rm -Rf fftw-$FFTW_VER
tar -xf $FFTW_ARCHIVE
pushd fftw-$FFTW_VER
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS \
./configure --prefix=$OCTAVE_DIR --enable-shared \
            --with-combined-threads --enable-threads
make -j 6 && make install
popd
rm -Rf fftw-$FFTW_VER

#
# Build fftw single-precision
#
rm -Rf fftw-$FFTW_VER
tar -xf $FFTW_ARCHIVE
pushd fftw-$FFTW_VER
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS \
./configure --prefix=$OCTAVE_DIR --enable-shared \
            --with-combined-threads --enable-threads --enable-single
make -j 6 && make install
popd
rm -Rf fftw-$FFTW_VER

#
# Build sundials
#
rm -Rf sundials-$SUNDIALS_VER
tar -xf $SUNDIALS_ARCHIVE
mkdir -p build-sundials-$SUNDIALS_VER
pushd build-sundials-$SUNDIALS_VER
CFLAGS=$OPTFLAGS CXXFLAGS=$OPTFLAGS FFLAGS=$OPTFLAGS \
echo " c \n g \n q \n" | \
    ccmake -DENABLE_KLU=ON -DKLU_LIBRARY_DIR:PATH=$OCTAVE_LIB_DIR \
	   -DCMAKE_INSTALL_LIBDIR=lib --install-prefix $OCTAVE_DIR \
	   ../sundials-$SUNDIALS_VER
cmake ../sundials-$SUNDIALS_VER
make -j 6 && make install
popd
rm -Rf build-sundials-$SUNDIALS_VER sundials-$SUNDIALS_VER

#
# Build GraphicsMagick
#
rm -Rf GraphicsMagick-$GRAPHICSMAGICK_VER
tar -xf $GRAPHICSMAGICK_ARCHIVE
mkdir -p build-GraphicsMagick-$GRAPHICSMAGICK_VER
pushd build-GraphicsMagick-$GRAPHICSMAGICK_VER
../GraphicsMagick-$GRAPHICSMAGICK_VER/configure \
    --prefix=$OCTAVE_DIR --enable-shared --disable-static \
    --with-quantum-depth=16  --with-magick-plus-plus=yes
make && make install
popd
rm -Rf build-GraphicsMagick-$GRAPHICSMAGICK_VER \
       GraphicsMagick-$GRAPHICSMAGICK_VER

#
# Build octave
#
rm -Rf build
mkdir build
pushd build
export CFLAGS="$OPTFLAGS -std=c11 -I$OCTAVE_INCLUDE_DIR"
export CXXFLAGS="$OPTFLAGS -std=c++11 -I$OCTAVE_INCLUDE_DIR"
export FFLAGS=$OPTFLAGS
export LDFLAGS="-L$OCTAVE_LIB_DIR"
# Add --enable-address-sanitizer-flags for address sanitizer build
PKG_CONFIG_PATH=$OCTAVE_LIB_DIR/pkgconfig \
../octave/configure --prefix=$OCTAVE_DIR \
         --disable-java \
         --without-fltk \
         --with-blas=-lblas \
         --with-lapack=-llapack \
         --with-qt=5 \
         --with-magick=GraphicsMagick++ \
         --with-arpack-includedir=$OCTAVE_INCLUDE_DIR \
         --with-arpack-libdir=$OCTAVE_LIB_DIR \
         --with-qrupdate-includedir=$OCTAVE_INCLUDE_DIR \
         --with-qrupdate-libdir=$OCTAVE_LIB_DIR \
         --with-amd-includedir=$OCTAVE_INCLUDE_DIR \
         --with-amd-libdir=$OCTAVE_LIB_DIR \
         --with-camd-includedir=$OCTAVE_INCLUDE_DIR \
         --with-camd-libdir=$OCTAVE_LIB_DIR \
         --with-colamd-includedir=$OCTAVE_INCLUDE_DIR \
         --with-colamd-libdir=$OCTAVE_LIB_DIR \
         --with-ccolamd-includedir=$OCTAVE_INCLUDE_DIR \
         --with-ccolamd-libdir=$OCTAVE_LIB_DIR \
         --with-cholmod-includedir=$OCTAVE_INCLUDE_DIR \
         --with-cholmod-libdir=$OCTAVE_LIB_DIR \
         --with-cxsparse-includedir=$OCTAVE_INCLUDE_DIR \
         --with-cxsparse-libdir=$OCTAVE_LIB_DIR \
         --with-umfpack-includedir=$OCTAVE_INCLUDE_DIR \
         --with-umfpack-libdir=$OCTAVE_LIB_DIR \
         --with-glpk-includedir=$OCTAVE_INCLUDE_DIR \
         --with-glpk-libdir=$OCTAVE_LIB_DIR \
         --with-fftw3-includedir=$OCTAVE_INCLUDE_DIR \
         --with-fftw3-libdir=$OCTAVE_LIB_DIR \
         --with-fftw3f-includedir=$OCTAVE_INCLUDE_DIR \
         --with-fftw3f-libdir=$OCTAVE_LIB_DIR \
	 --with-klu-includedir=$OCTAVE_INCLUDE_DIR \
	 --with-klu-libdir=$OCTAVE_LIB_DIR \
	 --with-sundials_nvecserial-includedir=$OCTAVE_INCLUDE_DIR \
	 --with-sundials_nvecserial-libdir=$OCTAVE_LIB_DIR \
	 --with-sundials_ida-includedir=$OCTAVE_INCLUDE_DIR \
	 --with-sundials_ida-libdir=$OCTAVE_LIB_DIR \
	 --with-sundials_sunlinsolklu-includedir=$OCTAVE_INCLUDE_DIR \
	 --with-sundials_sunlinsolklu-libdir=$OCTAVE_LIB_DIR 

make V=1 -j6
make install
popd
#rm -Rf build
rm -f octave-$OCTAVE_VER.patch.uue octave-$OCTAVE_VER.patch

#
# Compiling octave is done
#

#
# Install Octave-Forge packages
#
#
# Fix struct package error_helpers.h  and install the struct package
#
cat > struct-$STRUCT_VER".patch.uue" << 'EOF'
begin-base64 644 struct-1.0.17.patch
RmlsZXMgc3RydWN0LTEuMC4xNy9zcmMvZXJyb3ItaGVscGVycy5oIGFuZCBz
dHJ1Y3QtMS4wLjE3Lm5ldy9zcmMvZXJyb3ItaGVscGVycy5oIGRpZmZlcgot
LS0gc3RydWN0LTEuMC4xNy9zcmMvZXJyb3ItaGVscGVycy5oCTIwMjEtMDIt
MTcgMDY6MDM6MzguMDAwMDAwMDAwICsxMTAwCisrKyBzdHJ1Y3QtMS4wLjE3
Lm5ldy9zcmMvZXJyb3ItaGVscGVycy5oCTIwMjItMDItMTQgMTQ6NTQ6NTIu
MzQ5NTAwODY1ICsxMTAwCkBAIC00NCwxMyArNDQsNiBAQAogICAgIHRyeSBc
CiAgICAgICB7IFwKICAgICAgICAgY29kZSA7IFwKLSBcCi0gICAgICAgIGlm
IChlcnJvcl9zdGF0ZSkgXAotICAgICAgICAgIHsgXAotICAgICAgICAgICAg
ZXJyb3IgKF9fVkFfQVJHU19fKTsgXAotIFwKLSAgICAgICAgICAgIHJldHVy
biByZXR2YWw7IFwKLSAgICAgICAgICB9IFwKICAgICAgIH0gXAogICAgIGNh
dGNoIChPQ1RBVkVfX0VYRUNVVElPTl9FWENFUFRJT04mIGUpIFwKICAgICAg
IHsgXApAQCAtNjQsNyArNTcsOSBAQAogICAgICAgfSBcCiAgICAgY2F0Y2gg
KE9DVEFWRV9fRVhFQ1VUSU9OX0VYQ0VQVElPTiYgZSkgXAogICAgICAgeyBc
Ci0gICAgICAgIHZlcnJvciAoZSwgX19WQV9BUkdTX18pOyBcCisgICAgICAg
IF9wX2Vycm9yIChfX1ZBX0FSR1NfXyk7IFwKKyBcCisgICAgICAgIGV4aXQg
KDEpOyBcCiAgICAgICB9CiAjZW5kaWYKIApAQCAtNzcsMTMgKzcyLDYgQEAK
ICAgICB0cnkgXAogICAgICAgeyBcCiAgICAgICAgIGNvZGUgOyBcCi0gXAot
ICAgICAgICBpZiAoZXJyb3Jfc3RhdGUpIFwKLSAgICAgICAgICB7IFwKLSAg
ICAgICAgICAgIF9wX2Vycm9yIChfX1ZBX0FSR1NfXyk7IFwKLSBcCi0gICAg
ICAgICAgICBleGl0ICgxKTsgXAotICAgICAgICAgIH0gXAogICAgICAgfSBc
CiAgICAgY2F0Y2ggKE9DVEFWRV9fRVhFQ1VUSU9OX0VYQ0VQVElPTiYpIFwK
ICAgICAgIHsgXApAQCAtMTE2LDExICsxMDQsNiBAQAogICAgIHRyeSBcCiAg
ICAgICB7IFwKICAgICAgICAgY29kZSA7IFwKLSAgICAgICAgaWYgKGVycm9y
X3N0YXRlKSBcCi0gICAgICAgICAgeyBcCi0gICAgICAgICAgICBlcnJvcl9z
dGF0ZSA9IDA7IFwKLSAgICAgICAgICAgIGVyciA9IHRydWU7IFwKLSAgICAg
ICAgICB9IFwKICAgICAgIH0gXAogICAgIGNhdGNoIChPQ1RBVkVfX0VYRUNV
VElPTl9FWENFUFRJT04mKSBcCiAgICAgICB7IFwK
====
EOF
uudecode struct-$STRUCT_VER".patch.uue" > struct-$STRUCT_VER".patch"
tar -xf $STRUCT_ARCHIVE
NEW_STRUCT_ARCHIVE=struct-$STRUCT_VER".new.tar.gz"
pushd struct-$STRUCT_VER
patch -p1 < ../struct-$STRUCT_VER".patch"
popd
tar -czf $NEW_STRUCT_ARCHIVE struct-$STRUCT_VER
rm -Rf struct-$STRUCT_VER struct-$STRUCT_VER".patch.uue" struct-$STRUCT_VER".patch"

$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$NEW_STRUCT_ARCHIVE
rm -f $NEW_STRUCT_ARCHIVE

#
# Other packages
#
$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$IO_ARCHIVE
$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$STATISTICS_ARCHIVE
$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$CONTROL_ARCHIVE

#
# Fix parallel package pserver.cc and install the parallel package
#
cat > parallel-$PARALLEL_VER".patch.uue" << 'EOF'
begin-base64 644 parallel-4.0.1.patch
RmlsZXMgcGFyYWxsZWwtNC4wLjEvc3JjL2Vycm9yLWhlbHBlcnMuaCBhbmQg
cGFyYWxsZWwtNC4wLjEubmV3L3NyYy9lcnJvci1oZWxwZXJzLmggZGlmZmVy
Ci0tLSBwYXJhbGxlbC00LjAuMS9zcmMvZXJyb3ItaGVscGVycy5oCTIwMjEt
MDMtMTcgMDU6MDM6MDkuMDAwMDAwMDAwICsxMTAwCisrKyBwYXJhbGxlbC00
LjAuMS5uZXcvc3JjL2Vycm9yLWhlbHBlcnMuaAkyMDIyLTAyLTE0IDIxOjI0
OjMyLjY2NDQ1NjYwNyArMTEwMApAQCAtMSwxMCArMSwxMCBAQAogLyoKIAot
Q29weXJpZ2h0IChDKSAyMDE2LTIwMTggT2xhZiBUaWxsIDxpN3Rpb2xAdC1v
bmxpbmUuZGU+CitDb3B5cmlnaHQgKEMpIDIwMTYtMjAxOSBPbGFmIFRpbGwg
PGk3dGlvbEB0LW9ubGluZS5kZT4KIAogVGhpcyBwcm9ncmFtIGlzIGZyZWUg
c29mdHdhcmU7IHlvdSBjYW4gcmVkaXN0cmlidXRlIGl0IGFuZC9vciBtb2Rp
ZnkKIGl0IHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGUgR05VIEdlbmVyYWwgUHVi
bGljIExpY2Vuc2UgYXMgcHVibGlzaGVkIGJ5Ci10aGUgRnJlZSBTb2Z0d2Fy
ZSBGb3VuZGF0aW9uOyBlaXRoZXIgdmVyc2lvbiAzIG9mIHRoZSBMaWNlbnNl
LCBvcgordGhlIEZyZWUgU29mdHdhcmUgRm91bmRhdGlvbjsgZWl0aGVyIHZl
cnNpb24gMiBvZiB0aGUgTGljZW5zZSwgb3IKIChhdCB5b3VyIG9wdGlvbikg
YW55IGxhdGVyIHZlcnNpb24uCiAKIFRoaXMgcHJvZ3JhbSBpcyBkaXN0cmli
dXRlZCBpbiB0aGUgaG9wZSB0aGF0IGl0IHdpbGwgYmUgdXNlZnVsLApAQCAt
NDQsMTMgKzQ0LDYgQEAKICAgICB0cnkgXAogICAgICAgeyBcCiAgICAgICAg
IGNvZGUgOyBcCi0gXAotICAgICAgICBpZiAoZXJyb3Jfc3RhdGUpIFwKLSAg
ICAgICAgICB7IFwKLSAgICAgICAgICAgIGVycm9yIChfX1ZBX0FSR1NfXyk7
IFwKLSBcCi0gICAgICAgICAgICByZXR1cm4gcmV0dmFsOyBcCi0gICAgICAg
ICAgfSBcCiAgICAgICB9IFwKICAgICBjYXRjaCAoT0NUQVZFX19FWEVDVVRJ
T05fRVhDRVBUSU9OJiBlKSBcCiAgICAgICB7IFwKQEAgLTY0LDcgKzU3LDkg
QEAKICAgICAgIH0gXAogICAgIGNhdGNoIChPQ1RBVkVfX0VYRUNVVElPTl9F
WENFUFRJT04mIGUpIFwKICAgICAgIHsgXAotICAgICAgICB2ZXJyb3IgKGUs
IF9fVkFfQVJHU19fKTsgXAorICAgICAgICBfcF9lcnJvciAoX19WQV9BUkdT
X18pOyBcCisgXAorICAgICAgICBleGl0ICgxKTsgXAogICAgICAgfQogI2Vu
ZGlmCiAKQEAgLTc3LDEzICs3Miw2IEBACiAgICAgdHJ5IFwKICAgICAgIHsg
XAogICAgICAgICBjb2RlIDsgXAotIFwKLSAgICAgICAgaWYgKGVycm9yX3N0
YXRlKSBcCi0gICAgICAgICAgeyBcCi0gICAgICAgICAgICBfcF9lcnJvciAo
X19WQV9BUkdTX18pOyBcCi0gXAotICAgICAgICAgICAgZXhpdCAoMSk7IFwK
LSAgICAgICAgICB9IFwKICAgICAgIH0gXAogICAgIGNhdGNoIChPQ1RBVkVf
X0VYRUNVVElPTl9FWENFUFRJT04mKSBcCiAgICAgICB7IFwKQEAgLTExNiwx
MSArMTA0LDYgQEAKICAgICB0cnkgXAogICAgICAgeyBcCiAgICAgICAgIGNv
ZGUgOyBcCi0gICAgICAgIGlmIChlcnJvcl9zdGF0ZSkgXAotICAgICAgICAg
IHsgXAotICAgICAgICAgICAgZXJyb3Jfc3RhdGUgPSAwOyBcCi0gICAgICAg
ICAgICBlcnIgPSB0cnVlOyBcCi0gICAgICAgICAgfSBcCiAgICAgICB9IFwK
ICAgICBjYXRjaCAoT0NUQVZFX19FWEVDVVRJT05fRVhDRVBUSU9OJikgXAog
ICAgICAgeyBcCkZpbGVzIHBhcmFsbGVsLTQuMC4xL3NyYy9wLWNvbnRyb2wu
Y2MgYW5kIHBhcmFsbGVsLTQuMC4xLm5ldy9zcmMvcC1jb250cm9sLmNjIGRp
ZmZlcgotLS0gcGFyYWxsZWwtNC4wLjEvc3JjL3AtY29udHJvbC5jYwkyMDIx
LTAzLTE3IDA1OjAzOjA5LjAwMDAwMDAwMCArMTEwMAorKysgcGFyYWxsZWwt
NC4wLjEubmV3L3NyYy9wLWNvbnRyb2wuY2MJMjAyMi0wMi0xNCAyMTo1Mzox
Ni40MDYyNjQ0MTAgKzExMDAKQEAgLTI4Niw3ICsyODYsNyBAQAogICAgICAg
ICB9CiAgICAgICBlbHNlCiAgICAgICAgIHsKLSAgICAgICAgICBucHJvY19t
YXggPSBudW1fcHJvY2Vzc29ycyAoTlBST0NfQ1VSUkVOVCk7CisgICAgICAg
ICAgbnByb2NfbWF4ID0gb2N0YXZlX251bV9wcm9jZXNzb3JzX3dyYXBwZXIg
KE5QUk9DX0NVUlJFTlQpOwogCiAgICAgICAgICAgZ251bGliX3BvbGxmZHMg
PSBnbnVsaWJfYWxsb2NfcG9sbGZkcyAobnByb2NfbWF4KTsKICAgICAgICAg
fQpGaWxlcyBwYXJhbGxlbC00LjAuMS9zcmMvcGFyYWxsZWwtZ251dGxzLmgg
YW5kIHBhcmFsbGVsLTQuMC4xLm5ldy9zcmMvcGFyYWxsZWwtZ251dGxzLmgg
ZGlmZmVyCi0tLSBwYXJhbGxlbC00LjAuMS9zcmMvcGFyYWxsZWwtZ251dGxz
LmgJMjAyMS0wMy0xNyAwNTowMzowOS4wMDAwMDAwMDAgKzExMDAKKysrIHBh
cmFsbGVsLTQuMC4xLm5ldy9zcmMvcGFyYWxsZWwtZ251dGxzLmgJMjAyMi0w
Mi0xNCAyMTo1MzoxMC45ODMyOTAyMzMgKzExMDAKQEAgLTQ0LDcgKzQ0LDcg
QEAKIAogI2luY2x1ZGUgPHN0ZGludC5oPgogCi0vLyBXZSBsaW5rIGFnYWlu
c3QgdGhlIGdudWxpYiBudW1fcHJvY2Vzc29ycygpIHVzZWQgYnkgT2N0YXZl
LiBucHJvYy5oCisvLyBXZSBsaW5rIGFnYWluc3QgdGhlIGdudWxpYiBvY3Rh
dmVfbnVtX3Byb2Nlc3NvcnNfd3JhcHBlcigpIHVzZWQgYnkgT2N0YXZlLiBu
cHJvYy5oCiAvLyB1c2VkIGJ5IE9jdGF2ZSBpcyBub3QgYWNjZXNzaWJsZS4g
SWYgdGhlIGludGVyZmFjZSBjaGFuZ2VzLCB0aGlzCiAvLyB3aWxsIHN0b3Ag
d29ya2luZy4KIGV4dGVybiAiQyIgewpAQCAtNTgsNyArNTgsNyBAQAogCiAv
KiBSZXR1cm4gdGhlIHRvdGFsIG51bWJlciBvZiBwcm9jZXNzb3JzLiAgVGhl
IHJlc3VsdCBpcyBndWFyYW50ZWVkIHRvCiAgICBiZSBhdCBsZWFzdCAxLiAg
Ki8KLWV4dGVybiB1bnNpZ25lZCBsb25nIGludCBudW1fcHJvY2Vzc29ycyAo
ZW51bSBucHJvY19xdWVyeSBxdWVyeSk7CitleHRlcm4gdW5zaWduZWQgbG9u
ZyBpbnQgb2N0YXZlX251bV9wcm9jZXNzb3JzX3dyYXBwZXIgKGVudW0gbnBy
b2NfcXVlcnkgcXVlcnkpOwogfQogCiAKRmlsZXMgcGFyYWxsZWwtNC4wLjEv
c3JjL3Bjb25uZWN0LmNjIGFuZCBwYXJhbGxlbC00LjAuMS5uZXcvc3JjL3Bj
b25uZWN0LmNjIGRpZmZlcgotLS0gcGFyYWxsZWwtNC4wLjEvc3JjL3Bjb25u
ZWN0LmNjCTIwMjEtMDMtMTcgMDU6MDM6MDkuMDAwMDAwMDAwICsxMTAwCisr
KyBwYXJhbGxlbC00LjAuMS5uZXcvc3JjL3Bjb25uZWN0LmNjCTIwMjItMDIt
MTQgMjE6NTQ6MjQuMzg5OTQwNjg1ICsxMTAwCkBAIC00MDcsNyArNDA3LDcg
QEAKICAgbmV0d29yay0+aW5zZXJ0X2Nvbm5lY3Rpb24gKGNvbm4sIDApOwog
CiAgIC8vIHN0b3JlIG51bWJlciBvZiBwcm9jZXNzb3IgY29yZXMgYXZhaWxh
YmxlIGluIGNsaWVudAotICBjb25uLT5zZXRfbnByb2MgKG51bV9wcm9jZXNz
b3JzIChOUFJPQ19DVVJSRU5UKSk7CisgIGNvbm4tPnNldF9ucHJvYyAob2N0
YXZlX251bV9wcm9jZXNzb3JzX3dyYXBwZXIgKE5QUk9DX0NVUlJFTlQpKTsK
IAogICBmb3IgKHVpbnQzMl90IGkgPSAwOyBpIDwgbmhvc3RzOyBpKyspCiAg
ICAgewpGaWxlcyBwYXJhbGxlbC00LjAuMS9zcmMvY29uZmlndXJlIGFuZCBw
YXJhbGxlbC00LjAuMS5uZXcvc3JjL2NvbmZpZ3VyZSBkaWZmZXIKLS0tIHBh
cmFsbGVsLTQuMC4xL3NyYy9jb25maWd1cmUJMjAyMS0wMy0xNyAwNTowMzo0
NC43NjY3Mzc4MTcgKzExMDAKKysrIHBhcmFsbGVsLTQuMC4xLm5ldy9zcmMv
Y29uZmlndXJlCTIwMjItMDItMTQgMjE6MjQ6MzIuNjY3NDU2NTkyICsxMTAw
CkBAIC0yMzQ4MiwxMSArMjM0ODIsMTEgQEAKIF9BQ0VPRgogaWYgYWNfZm5f
Y3h4X3RyeV9jb21waWxlICIkTElORU5PIjsgdGhlbiA6CiAKLSRhc19lY2hv
ICIjZGVmaW5lIE9DVEFWRV9fSU5URVJQUkVURVJfX1NZTUJPTF9UQUJMRV9f
QVNTSUdOIG9jdGF2ZTo6aW50ZXJwcmV0ZXI6OnRoZV9pbnRlcnByZXRlciAo
KSAtPiBnZXRfc3ltYm9sX3RhYmxlICgpLmFzc2lnbiIgPj5jb25mZGVmcy5o
CiskYXNfZWNobyAiI2RlZmluZSBPQ1RBVkVfX0lOVEVSUFJFVEVSX19TWU1C
T0xfVEFCTEVfX0FTU0lHTiBvY3RhdmU6OmludGVycHJldGVyOjp0aGVfaW50
ZXJwcmV0ZXIgKCkgLT4gYXNzaWduIiA+PmNvbmZkZWZzLmgKIAogCi0gICAg
IHsgJGFzX2VjaG8gIiRhc19tZToke2FzX2xpbmVuby0kTElORU5PfTogcmVz
dWx0OiBvY3RhdmU6OmludGVycHJldGVyOjp0aGVfaW50ZXJwcmV0ZXIgKCkg
LT4gZ2V0X3N5bWJvbF90YWJsZSAoKS5hc3NpZ24iID4mNQotJGFzX2VjaG8g
Im9jdGF2ZTo6aW50ZXJwcmV0ZXI6OnRoZV9pbnRlcnByZXRlciAoKSAtPiBn
ZXRfc3ltYm9sX3RhYmxlICgpLmFzc2lnbiIgPiY2OyB9CisgICAgIHsgJGFz
X2VjaG8gIiRhc19tZToke2FzX2xpbmVuby0kTElORU5PfTogcmVzdWx0OiBv
Y3RhdmU6OmludGVycHJldGVyOjp0aGVfaW50ZXJwcmV0ZXIgKCkgLT4gYXNz
aWduIiA+JjUKKyRhc19lY2hvICJvY3RhdmU6OmludGVycHJldGVyOjp0aGVf
aW50ZXJwcmV0ZXIgKCkgLT4gYXNzaWduIiA+JjY7IH0KICAgICAgZWNobyAn
CiAnID4+IG9jdC1hbHQtaW5jbHVkZXMuaAogZWxzZQpGaWxlcyBwYXJhbGxl
bC00LjAuMS9zcmMvX19vY3RhdmVfc2VydmVyX18uY2MgYW5kIHBhcmFsbGVs
LTQuMC4xLm5ldy9zcmMvX19vY3RhdmVfc2VydmVyX18uY2MgZGlmZmVyCi0t
LSBwYXJhbGxlbC00LjAuMS9zcmMvX19vY3RhdmVfc2VydmVyX18uY2MJMjAy
MS0wMy0xNyAwNTowMzowOS4wMDAwMDAwMDAgKzExMDAKKysrIHBhcmFsbGVs
LTQuMC4xLm5ldy9zcmMvX19vY3RhdmVfc2VydmVyX18uY2MJMjAyMi0wMi0x
NCAyMTozOTo1MC45NjgwOTg3OTMgKzExMDAKQEAgLTMxNyw3ICszMTcsNyBA
QAogI2VuZGlmIC8vIEhBVkVfTElCR05VVExTCiAKICAgLy8gZGV0ZXJtaW5l
IG93biBudW1iZXIgb2YgdXNhYmxlIHByb2Nlc3NvciBjb3JlcwotICB1aW50
MzJfdCBucHJvYyA9IG51bV9wcm9jZXNzb3JzIChOUFJPQ19DVVJSRU5UKTsK
KyAgdWludDMyX3QgbnByb2MgPSBvY3RhdmVfbnVtX3Byb2Nlc3NvcnNfd3Jh
cHBlciAoTlBST0NfQ1VSUkVOVCk7CiAKICAgLy8gVGhlIHNlcnZlcnMgY29t
bWFuZCBzdHJlYW0gd2lsbCBub3QgYmUgaW5zZXJ0ZWQgaW50byBhCiAgIC8v
IGNvbm5lY3Rpb24gb2JqZWN0Lgo=
====
EOF
uudecode parallel-$PARALLEL_VER".patch.uue" > parallel-$PARALLEL_VER".patch"
tar -xf $PARALLEL_ARCHIVE
NEW_PARALLEL_ARCHIVE=parallel-$PARALLEL_VER".new.tar.gz"
pushd parallel-$PARALLEL_VER
patch -p1 < ../parallel-$PARALLEL_VER".patch"
popd
tar -czf $NEW_PARALLEL_ARCHIVE parallel-$PARALLEL_VER
rm -Rf parallel-$PARALLEL_VER parallel-$PARALLEL_VER".patch.uue" parallel-$PARALLEL_VER".patch"

$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$NEW_PARALLEL_ARCHIVE
rm -f $NEW_PARALLEL_ARCHIVE

#
# Fix optim package quadprog function and install the optim package
#
cat > optim-$OPTIM_VER".patch.uue" << 'EOF'
begin-base64 644 optim-1.6.1.patch
RmlsZXMgb3B0aW0tMS42LjEvaW5zdC9sc3FsaW4ubSBhbmQgb3B0aW0tMS42
LjEubmV3L2luc3QvbHNxbGluLm0gZGlmZmVyCi0tLSBvcHRpbS0xLjYuMS9p
bnN0L2xzcWxpbi5tCTIwMjEtMDItMTcgMDY6MDI6MTMuMDAwMDAwMDAwICsx
MTAwCisrKyBvcHRpbS0xLjYuMS5uZXcvaW5zdC9sc3FsaW4ubQkyMDIyLTAy
LTE0IDE1OjA0OjQxLjk3MDUzMjg3MSArMTEwMApAQCAtMTE1LDcgKzExNSw3
IEBACiAKICAgaWYgKG5fb3V0ID4gMikKICAgICAjIyBXZSBkb24ndCBuZWVk
IHRvIGtub3cgaWYgb3JpZ2luYWwgbl9vdXQgd2FzIDMgb3IgMi4KLSAgICBu
X291dCAtLTsKKyAgICBuX291dC0tOwogICBlbmRpZgogCiAgIHF1YWRwcm9n
X291dCA9IGNlbGwgKDEsIG1heCAobl9vdXQsIDEpKTsKRmlsZXMgb3B0aW0t
MS42LjEvaW5zdC92Znplcm8ubSBhbmQgb3B0aW0tMS42LjEubmV3L2luc3Qv
dmZ6ZXJvLm0gZGlmZmVyCi0tLSBvcHRpbS0xLjYuMS9pbnN0L3ZmemVyby5t
CTIwMjEtMDItMTcgMDY6MDI6MTMuMDAwMDAwMDAwICsxMTAwCisrKyBvcHRp
bS0xLjYuMS5uZXcvaW5zdC92Znplcm8ubQkyMDIyLTAyLTE0IDE1OjA4OjQ0
LjM5NjM4OTgwMyArMTEwMApAQCAtMjgyLDcgKzI4Miw3IEBACiAJCQkJIyBm
dW4oKSBtaWdodCBleHBlY3QgZnVsbC1sZW5ndGgKIAkJCQkjIGFyZ3VtZW50
CiAgICAgICBmdmFsKGlkeCwgMSkgPSBmYyhpZHgsIDEpID0gZnVuIChjKSg6
KShpZHgsIDEpOwotICAgICAgbml0ZXIgKys7IG5mZXYgKys7CisgICAgICBu
aXRlcisrOyBuZmV2Kys7CiAgICAgZW5kaWYKIAogICAgICMjIE1vZGlmaWNh
dGlvbiAyOiBza2lwIGludmVyc2UgY3ViaWMgaW50ZXJwb2xhdGlvbiBpZgpG
aWxlcyBvcHRpbS0xLjYuMS9pbnN0L29wdGltX2RvYy5tIGFuZCBvcHRpbS0x
LjYuMS5uZXcvaW5zdC9vcHRpbV9kb2MubSBkaWZmZXIKLS0tIG9wdGltLTEu
Ni4xL2luc3Qvb3B0aW1fZG9jLm0JMjAyMS0wMi0xNyAwNjowMjoxMy4wMDAw
MDAwMDAgKzExMDAKKysrIG9wdGltLTEuNi4xLm5ldy9pbnN0L29wdGltX2Rv
Yy5tCTIwMjItMDItMTQgMTQ6NTk6MTIuNDMwMTkxNjg0ICsxMTAwCkBAIC0z
NSwxMiArMzUsMTQgQEAKICAgcGVyc2lzdGVudCBpbmZvcGF0aCA9ICIiOwog
ICBpZiAoaXNlbXB0eSAoaW5mb3BhdGgpKQogICAgIFtsb2NhbF9saXN0LCBn
bG9iYWxfbGlzdF0gPSBwa2cgKCJsaXN0Iik7Ci0gICAgaWYgKCEgaXNlbXB0
eSAoaWR4ID0gLi4uCisgICAgaWYgKGxlbmd0aChsb2NhbF9saXN0KT4wKSAm
JiAuLi4KKyAgICAgICAoISBpc2VtcHR5IChpZHggPSAuLi4KICAgICAgICAg
ICAgICAgICAgICBmaW5kIChzdHJjbXAgKCJvcHRpbSIsCiAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICB7c3RydWN0Y2F0KDEsIGxvY2FsX2xp
c3R7On0pLm5hbWV9KSwKICAgICAgICAgICAgICAgICAgICAgICAgICAxKSkp
Ci0gICAgICBpZGlyID0gbG9jYWxfbGlzdHtpZHh9LmRpcjsKLSAgICBlbHNl
aWYgKCEgaXNlbXB0eSAoaWR4ID0gLi4uCisgICAgICBpZGlyID0gbG9jYWxf
bGlzdHtpZHh9LmRpcjsgCisgICAgZWxzZWlmIChsZW5ndGgoZ2xvYmFsX2xp
c3QpPjApICYmIC4uLgorICAgICAgICAgICAoISBpc2VtcHR5IChpZHggPSAu
Li4KICAgICAgICAgICAgICAgICAgICAgICAgZmluZCAoc3RyY21wICgib3B0
aW0iLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHtz
dHJ1Y3RjYXQoMSwgZ2xvYmFsX2xpc3R7On0pLm5hbWV9KSwKICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgMSkpKQpGaWxlcyBvcHRpbS0xLjYuMS9z
cmMvZXJyb3ItaGVscGVycy5oIGFuZCBvcHRpbS0xLjYuMS5uZXcvc3JjL2Vy
cm9yLWhlbHBlcnMuaCBkaWZmZXIKLS0tIG9wdGltLTEuNi4xL3NyYy9lcnJv
ci1oZWxwZXJzLmgJMjAyMS0wMi0xNyAwNjowMjoxMy4wMDAwMDAwMDAgKzEx
MDAKKysrIG9wdGltLTEuNi4xLm5ldy9zcmMvZXJyb3ItaGVscGVycy5oCTIw
MjItMDItMTQgMTQ6NTk6MzYuMTA2MDcyNTAzICsxMTAwCkBAIC00NCwxMyAr
NDQsNiBAQAogICAgIHRyeSBcCiAgICAgICB7IFwKICAgICAgICAgY29kZSA7
IFwKLSBcCi0gICAgICAgIGlmIChlcnJvcl9zdGF0ZSkgXAotICAgICAgICAg
IHsgXAotICAgICAgICAgICAgZXJyb3IgKF9fVkFfQVJHU19fKTsgXAotIFwK
LSAgICAgICAgICAgIHJldHVybiByZXR2YWw7IFwKLSAgICAgICAgICB9IFwK
ICAgICAgIH0gXAogICAgIGNhdGNoIChPQ1RBVkVfX0VYRUNVVElPTl9FWENF
UFRJT04mIGUpIFwKICAgICAgIHsgXApAQCAtNjQsNyArNTcsOSBAQAogICAg
ICAgfSBcCiAgICAgY2F0Y2ggKE9DVEFWRV9fRVhFQ1VUSU9OX0VYQ0VQVElP
TiYgZSkgXAogICAgICAgeyBcCi0gICAgICAgIHZlcnJvciAoZSwgX19WQV9B
UkdTX18pOyBcCisgICAgICAgIF9wX2Vycm9yIChfX1ZBX0FSR1NfXyk7IFwK
KyBcCisgICAgICAgIGV4aXQgKDEpOyBcCiAgICAgICB9CiAjZW5kaWYKIApA
QCAtNzcsMTMgKzcyLDYgQEAKICAgICB0cnkgXAogICAgICAgeyBcCiAgICAg
ICAgIGNvZGUgOyBcCi0gXAotICAgICAgICBpZiAoZXJyb3Jfc3RhdGUpIFwK
LSAgICAgICAgICB7IFwKLSAgICAgICAgICAgIF9wX2Vycm9yIChfX1ZBX0FS
R1NfXyk7IFwKLSBcCi0gICAgICAgICAgICBleGl0ICgxKTsgXAotICAgICAg
ICAgIH0gXAogICAgICAgfSBcCiAgICAgY2F0Y2ggKE9DVEFWRV9fRVhFQ1VU
SU9OX0VYQ0VQVElPTiYpIFwKICAgICAgIHsgXApAQCAtMTE2LDExICsxMDQs
NiBAQAogICAgIHRyeSBcCiAgICAgICB7IFwKICAgICAgICAgY29kZSA7IFwK
LSAgICAgICAgaWYgKGVycm9yX3N0YXRlKSBcCi0gICAgICAgICAgeyBcCi0g
ICAgICAgICAgICBlcnJvcl9zdGF0ZSA9IDA7IFwKLSAgICAgICAgICAgIGVy
ciA9IHRydWU7IFwKLSAgICAgICAgICB9IFwKICAgICAgIH0gXAogICAgIGNh
dGNoIChPQ1RBVkVfX0VYRUNVVElPTl9FWENFUFRJT04mKSBcCiAgICAgICB7
IFwK
====
EOF
uudecode optim-$OPTIM_VER".patch.uue" > optim-$OPTIM_VER".patch"
tar -xf $OPTIM_ARCHIVE
NEW_OPTIM_ARCHIVE=optim-$OPTIM_VER".new.tar.gz"
pushd optim-$OPTIM_VER
patch -p1 < ../optim-$OPTIM_VER".patch"
popd
tar -czf $NEW_OPTIM_ARCHIVE optim-$OPTIM_VER
rm -Rf optim-$OPTIM_VER optim-$OPTIM_VER".patch.uue" optim-$OPTIM_VER".patch"

$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$NEW_OPTIM_ARCHIVE
rm -f $NEW_OPTIM_ARCHIVE

#
# Fix signal package and install the signal package
#
cat > signal-$SIGNAL_VER.patch.uue << 'EOF'
begin-base64 644 signal-1.4.1.patch
RmlsZXMgc2lnbmFsLTEuNC4xL2luc3QvenBsYW5lLm0gYW5kIHNpZ25hbC0x
LjQuMS5uZXcvaW5zdC96cGxhbmUubSBkaWZmZXIKLS0tIHNpZ25hbC0xLjQu
MS9pbnN0L3pwbGFuZS5tCTIwMTktMDItMDkgMDk6MDA6MzcuMDAwMDAwMDAw
ICsxMTAwCisrKyBzaWduYWwtMS40LjEubmV3L2luc3QvenBsYW5lLm0JMjAy
Mi0wMi0xNCAxNDowMzoxMy4zNjA5ODYwNjYgKzExMDAKQEAgLTExNSw4ICsx
MTUsOSBAQAogICAgICAgZm9yIGkgPSAxOmxlbmd0aCAoeF91KQogICAgICAg
ICBuID0gc3VtICh4X3UoaSkgPT0geCg6LGMpKTsKICAgICAgICAgaWYgKG4g
PiAxKQotICAgICAgICAgIGxhYmVsID0gc3ByaW50ZiAoIiBeJWQiLCBuKTsK
LSAgICAgICAgICB0ZXh0IChyZWFsICh4X3UoaSkpLCBpbWFnICh4X3UoaSkp
LCBsYWJlbCwgImNvbG9yIiwgY29sb3IpOworICAgICAgICAgIGxhYmVsID0g
c3ByaW50ZiAoIiVkIiwgbik7CisgICAgICAgICAgdGV4dCAocmVhbCAoeF91
KGkpKSwgaW1hZyAoeF91KGkpKSwgbGFiZWwsICJjb2xvciIsIGNvbG9yLCAu
Li4KKyAgICAgICAgICAgICAgICAidmVydGljYWxhbGlnbm1lbnQiLCAiYm90
dG9tIiwgImhvcml6b250YWxhbGlnbm1lbnQiLCAibGVmdCIpOwogICAgICAg
ICBlbmRpZgogICAgICAgZW5kZm9yCiAgICAgZW5kZm9yCkZpbGVzIHNpZ25h
bC0xLjQuMS9pbnN0L2J1ZmZlci5tIGFuZCBzaWduYWwtMS40LjEubmV3L2lu
c3QvYnVmZmVyLm0gZGlmZmVyCi0tLSBzaWduYWwtMS40LjEvaW5zdC9idWZm
ZXIubQkyMDE5LTAyLTA5IDA5OjAwOjM3LjAwMDAwMDAwMCArMTEwMAorKysg
c2lnbmFsLTEuNC4xLm5ldy9pbnN0L2J1ZmZlci5tCTIwMjItMDItMTQgMTQ6
MTQ6MDQuOTQxMDc3OTc3ICsxMTAwCkBAIC0xMjAsNyArMTIwLDcgQEAKICAg
ICAgICAgICBlbmR3aGlsZQogICAgICAgICAgIFtpLCBqXSA9IGluZDJzdWIo
W24tcCwgbV0sIGwpOwogICAgICAgICAgIGlmIChhbGwgKFtpLCBqXSA9PSBb
bi1wLCBtXSkpCi0gICAgICAgICAgICBvZmYgLS07CisgICAgICAgICAgICBv
ZmYtLTsKICAgICAgICAgICBlbmRpZgogICAgICAgICAgIHkgKDosIGVuZCAt
IG9mZiArIDIgOiBlbmQpID0gW107CiAgICAgICAgIGVsc2UKRmlsZXMgc2ln
bmFsLTEuNC4xL3NyYy9jbDJicC5jYyBhbmQgc2lnbmFsLTEuNC4xLm5ldy9z
cmMvY2wyYnAuY2MgZGlmZmVyCi0tLSBzaWduYWwtMS40LjEvc3JjL2NsMmJw
LmNjCTIwMTktMDItMDkgMDk6MDA6MzcuMDAwMDAwMDAwICsxMTAwCisrKyBz
aWduYWwtMS40LjEubmV3L3NyYy9jbDJicC5jYwkyMDIyLTAyLTE0IDE0OjA1
OjQyLjg3MDMyMDk3MiArMTEwMApAQCAtODksMzAgKzg5LDEwIEBACiAgIH0K
IAogICBjb25zdCBpbnQgbSA9IGFyZ3MoMCkuaW50X3ZhbHVlKHRydWUpOwot
ICBpZiAoZXJyb3Jfc3RhdGUpIHsKLSAgICBlcnJfd3JvbmdfdHlwZV9hcmcg
KCJjbDJicCIsIGFyZ3MoMCkpOwotICAgIHJldHVybiByZXR2YWw7Ci0gIH0K
ICAgY29uc3QgZG91YmxlIHcxID0gYXJncygxKS5kb3VibGVfdmFsdWUoKTsK
LSAgaWYgKGVycm9yX3N0YXRlKSB7Ci0gICAgZXJyX3dyb25nX3R5cGVfYXJn
ICgiY2wyYnAiLCBhcmdzKDEpKTsKLSAgICByZXR1cm4gcmV0dmFsOwotICB9
CiAgIGNvbnN0IGRvdWJsZSB3MiA9IGFyZ3MoMikuZG91YmxlX3ZhbHVlKCk7
Ci0gIGlmIChlcnJvcl9zdGF0ZSkgewotICAgIGVycl93cm9uZ190eXBlX2Fy
ZyAoImNsMmJwIiwgYXJncygyKSk7Ci0gICAgcmV0dXJuIHJldHZhbDsKLSAg
fQogICBjb25zdCBDb2x1bW5WZWN0b3IgdXBfdmVjdG9yKGFyZ3MoMykudmVj
dG9yX3ZhbHVlKCkpOwotICBpZiAoZXJyb3Jfc3RhdGUpIHsKLSAgICBlcnJf
d3JvbmdfdHlwZV9hcmcgKCJjbDJicCIsIGFyZ3MoMykpOwotICAgIHJldHVy
biByZXR2YWw7Ci0gIH0KICAgY29uc3QgQ29sdW1uVmVjdG9yIGxvX3ZlY3Rv
cihhcmdzKDQpLnZlY3Rvcl92YWx1ZSgpKTsKLSAgaWYgKGVycm9yX3N0YXRl
KSB7Ci0gICAgZXJyX3dyb25nX3R5cGVfYXJnICgiY2wyYnAiLCBhcmdzKDQp
KTsKLSAgICByZXR1cm4gcmV0dmFsOwotICB9CiAgIGlmICh1cF92ZWN0b3Iu
bnVtZWwoKSAhPSAzIHx8IGxvX3ZlY3Rvci5udW1lbCgpICE9IDMpIHsKICAg
ICBlcnJvcigiY2wyYnA6IFRoZSB1cCBhbmQgbG8gdmVjdG9ycyBtdXN0IGNv
bnRhaW4gMyB2YWx1ZXMiKTsKICAgICByZXR1cm4gcmV0dmFsOwpAQCAtMTI2
LDEwICsxMDYsNiBAQAogICB9CiAKICAgY29uc3QgaW50IEwgPSBhcmdzKDUp
LmludF92YWx1ZSh0cnVlKTsKLSAgaWYgKGVycm9yX3N0YXRlKSB7Ci0gICAg
ZXJyX3dyb25nX3R5cGVfYXJnICgiY2wyYnAiLCBhcmdzKDUpKTsKLSAgICBy
ZXR1cm4gcmV0dmFsOwotICB9CiAgIGlmIChMID4gMTAwMDAwMCkgewogICAg
IGVycm9yKCJjbDJicDogVGhlIFwiZ3JpZHNpemVcIiBwYXJhbWV0ZXIgY2Fu
bm90IGV4Y2VlZCAxMDAwMDAwIik7CiAgICAgcmV0dXJuIHJldHZhbDsKRmls
ZXMgc2lnbmFsLTEuNC4xL3NyYy9zb3NmaWx0LmNjIGFuZCBzaWduYWwtMS40
LjEubmV3L3NyYy9zb3NmaWx0LmNjIGRpZmZlcgotLS0gc2lnbmFsLTEuNC4x
L3NyYy9zb3NmaWx0LmNjCTIwMTktMDItMDkgMDk6MDA6MzcuMDAwMDAwMDAw
ICsxMTAwCisrKyBzaWduYWwtMS40LjEubmV3L3NyYy9zb3NmaWx0LmNjCTIw
MjItMDItMTQgMTQ6MDU6MjQuMDI4NDA0ODAyICsxMTAwCkBAIC01NSwxMiAr
NTUsNiBAQAogCiAgIE1hdHJpeCBzb3MoIGFyZ3MoMCkubWF0cml4X3ZhbHVl
KCkgKTsKIAotICBpZiAoZXJyb3Jfc3RhdGUpCi0gICAgewotICAgICAgZXJy
X3dyb25nX3R5cGVfYXJnICgic29zZmlsdCIsIGFyZ3MoMCkpOwotICAgICAg
cmV0dXJuIHJldHZhbDsKLSAgICB9Ci0KICAgaWYgKHNvcy5jb2x1bW5zKCkg
IT0gNikKICAgICB7CiAgICAgICBlcnJvcigiU2Vjb25kLW9yZGVyIHNlY3Rp
b24gbWF0cml4IG11c3QgYmUgYSBub24tZW1wdHkgTHg2IG1hdHJpeCIpOwpA
QCAtNjksMTIgKzYzLDYgQEAKIAogICBNYXRyaXggeCggYXJncygxKS5tYXRy
aXhfdmFsdWUoKSApOwogCi0gIGlmIChlcnJvcl9zdGF0ZSkKLSAgICB7Ci0g
ICAgICBlcnJfd3JvbmdfdHlwZV9hcmcgKCJzb3NmaWx0IiwgYXJncygxKSk7
Ci0gICAgICByZXR1cm4gcmV0dmFsOwotICAgIH0KLQogICBpbnQgbj14LnJv
d3MoKTsKICAgaW50IG09eC5jb2x1bW5zKCk7CiAKRmlsZXMgc2lnbmFsLTEu
NC4xL3NyYy91cGZpcmRuLmNjIGFuZCBzaWduYWwtMS40LjEubmV3L3NyYy91
cGZpcmRuLmNjIGRpZmZlcgotLS0gc2lnbmFsLTEuNC4xL3NyYy91cGZpcmRu
LmNjCTIwMTktMDItMDkgMDk6MDA6MzcuMDAwMDAwMDAwICsxMTAwCisrKyBz
aWduYWwtMS40LjEubmV3L3NyYy91cGZpcmRuLmNjCTIwMjItMDItMTQgMTQ6
MDU6MDYuNzg5NDgxNDgxICsxMTAwCkBAIC0xMDgsMzcgKzEwOCwxNCBAQAog
CiAgIENvbHVtblZlY3RvciBoIChhcmdzICgxKS52ZWN0b3JfdmFsdWUgKCkp
OwogCi0gIGlmIChlcnJvcl9zdGF0ZSkKLSAgICB7Ci0gICAgICBlcnJfd3Jv
bmdfdHlwZV9hcmcgKCJ1cGZpcmRuIiwgYXJncygxKSk7Ci0gICAgICByZXR1
cm4gcmV0dmFsOwotICAgIH0KLQogICBvY3RhdmVfaWR4X3R5cGUgcCA9IGFy
Z3MgKDIpLmlkeF90eXBlX3ZhbHVlICgpOwogCi0gIGlmIChlcnJvcl9zdGF0
ZSkKLSAgICB7Ci0gICAgICBlcnJfd3JvbmdfdHlwZV9hcmcgKCJ1cGZpcmRu
IiwgYXJncygyKSk7Ci0gICAgICByZXR1cm4gcmV0dmFsOwotICAgIH0KLQog
ICBvY3RhdmVfaWR4X3R5cGUgcSA9IGFyZ3MgKDMpLmlkeF90eXBlX3ZhbHVl
ICgpOwogCi0gIGlmIChlcnJvcl9zdGF0ZSkKLSAgICB7Ci0gICAgICBlcnJf
d3JvbmdfdHlwZV9hcmcgKCJ1cGZpcmRuIiwgYXJncygzKSk7Ci0gICAgICBy
ZXR1cm4gcmV0dmFsOwotICAgIH0KLQogICAvLyBEbyB0aGUgZGlzcGF0Y2hp
bmcKICAgaWYgKG9jdGF2ZTo6c2lnbmFsOjppc3JlYWwgKGFyZ3MgKDApKSkK
ICAgICB7CiAgICAgICBNYXRyaXggeCA9IGFyZ3MgKDApLm1hdHJpeF92YWx1
ZSAoKTsKLSAgICAgIGlmIChlcnJvcl9zdGF0ZSkKLSAgICAgICAgewotICAg
ICAgICAgIGVycl93cm9uZ190eXBlX2FyZyAoInVwZmlyZG4iLCBhcmdzKDAp
KTsKLSAgICAgICAgICByZXR1cm4gcmV0dmFsOwotICAgICAgICB9CiAKICAg
ICAgIE1hdHJpeCB5ID0gdXBmaXJkbiAoeCwgaCwgcCwgcSk7CiAgICAgICBy
ZXR2YWwgKDApID0geTsKQEAgLTE0NiwxMSArMTIzLDYgQEAKICAgZWxzZSBp
ZiAob2N0YXZlOjpzaWduYWw6OmlzY29tcGxleCAoYXJncyAoMCkpKQogICAg
IHsKICAgICAgIENvbXBsZXhNYXRyaXggeCA9IGFyZ3MgKDApLmNvbXBsZXhf
bWF0cml4X3ZhbHVlICgpOwotICAgICAgaWYgKGVycm9yX3N0YXRlKQotICAg
ICAgICB7Ci0gICAgICAgICAgZXJyX3dyb25nX3R5cGVfYXJnICgidXBmaXJk
biIsIGFyZ3MoMCkpOwotICAgICAgICAgIHJldHVybiByZXR2YWw7Ci0gICAg
ICAgIH0KIAogICAgICAgQ29tcGxleE1hdHJpeCB5ID0gdXBmaXJkbiAoeCwg
aCwgcCwgcSk7CiAgICAgICByZXR2YWwgKDApID0geTsK
====
EOF
uudecode signal-$SIGNAL_VER.patch.uue > signal-$SIGNAL_VER.patch
tar -xf $SIGNAL_ARCHIVE
pushd signal-$SIGNAL_VER
patch -p1 < ../signal-$SIGNAL_VER.patch
popd
NEW_SIGNAL_ARCHIVE=signal-$SIGNAL_VER".new.tar.gz"
tar -czf $NEW_SIGNAL_ARCHIVE signal-$SIGNAL_VER
rm -Rf signal-$SIGNAL_VER signal-$SIGNAL_VER.patch.uue signal-$SIGNAL_VER.patch

$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$NEW_SIGNAL_ARCHIVE
rm -f $NEW_SIGNAL_ARCHIVE

#
# Fix symbolic package for sympy-1.6 and install the symbolic package
# (Apply sympy-1.6.patch from octave-symbolic_2.9.0-3.debian.tar.xz)
#
cat > sympy-1.6.patch.uue << 'EOF'
begin-base64 644 sympy-1.6.patch
LS0tIHN5bWJvbGljLTIuOS4wL2luc3QvcHJpdmF0ZS9jaGVja19hbmRfY29u
dmVydC5tCTIwMjAtMDMtMDkgMDU6NDM6MTUuMDAwMDAwMDAwICsxMTAwCisr
KyBzeW1ib2xpYy0yLjkuMC5uZXcvL2luc3QvcHJpdmF0ZS9jaGVja19hbmRf
Y29udmVydC5tCTIwMjAtMTItMTMgMTE6NDU6MjUuNzk1MTQ1Mzk1ICsxMTAw
CkBAIC0zMCw4ICszMCw4IEBACiAKICAgICBzcCA9IHB5LnN5bXB5OwogICAg
IF9zeW0gPSBweS50dXBsZSh7c3AuQmFzaWMsIHNwLk1hdHJpeEJhc2V9KTsK
LSAgICBzdHJpbmdfdHlwZXMgPSBzcC5jb21wYXRpYmlsaXR5LnN0cmluZ190
eXBlczsKLSAgICBpbnRlZ2VyX3R5cGVzID0gc3AuY29tcGF0aWJpbGl0eS5p
bnRlZ2VyX3R5cGVzOworICAgIHN0cmluZ190eXBlcyA9IHNpeC5zdHJpbmdf
dHlwZXM7CisgICAgaW50ZWdlcl90eXBlcyA9IHNpeC5pbnRlZ2VyX3R5cGVz
OwogICBlbmQKIAogCi0tLSBzeW1ib2xpYy0yLjkuMC9pbnN0L3ByaXZhdGUv
cHl0aG9uX2lwY19uYXRpdmUubQkyMDIwLTAzLTA5IDA1OjQzOjE1LjAwMDAw
MDAwMCArMTEwMAorKysgc3ltYm9saWMtMi45LjAubmV3Ly9pbnN0L3ByaXZh
dGUvcHl0aG9uX2lwY19uYXRpdmUubQkyMDIwLTEyLTEzIDEyOjE1OjE1LjI2
NTYzMzI3OSArMTEwMApAQCAtODIsNyArODIsNyBAQAogICAgICAgICAgICAg
ICAgICAgICAnaW1wb3J0IGNvbGxlY3Rpb25zJwogICAgICAgICAgICAgICAg
ICAgICAnZnJvbSByZSBpbXBvcnQgc3BsaXQnCiAgICAgICAgICAgICAgICAg
ICAgICcjIHBhdGNoIHByZXR0eSBwcmludGVyLCBpc3N1ZSAjOTUyJwotICAg
ICAgICAgICAgICAgICAgICAnX215cHAgPSBwcmV0dHkuX19nbG9iYWxzX19b
IlByZXR0eVByaW50ZXIiXScKKyAgICAgICAgICAgICAgICAgICAgJ19teXBw
ID0gcHJldHR5JwogICAgICAgICAgICAgICAgICAgICAnZGVmIF9teV9yZXZf
cHJpbnQoY2xzLCBmLCAqKmt3YXJncyk6JwogICAgICAgICAgICAgICAgICAg
ICAnICAgIGcgPSBmLmZ1bmMoKnJldmVyc2VkKGYuYXJncyksIGV2YWx1YXRl
PUZhbHNlKScKICAgICAgICAgICAgICAgICAgICAgJyAgICByZXR1cm4gY2xz
Ll9wcmludF9GdW5jdGlvbihnLCAqKmt3YXJncyknCi0tLSBzeW1ib2xpYy0y
LjkuMC9pbnN0L3ByaXZhdGUvcHl0aG9uX2hlYWRlci5weQkyMDIwLTAzLTA5
IDA1OjQzOjE1LjAwMDAwMDAwMCArMTEwMAorKysgc3ltYm9saWMtMi45LjAu
bmV3Ly9pbnN0L3ByaXZhdGUvcHl0aG9uX2hlYWRlci5weQkyMDIwLTEyLTEz
IDEyOjE1OjQ3Ljc1MjM2MTQ1MSArMTEwMApAQCAtMTEsNiArMTEsNyBAQAog
aW1wb3J0IHN5cwogc3lzLnBzMSA9ICIiOyBzeXMucHMyID0gIiIKIAoraW1w
b3J0IHNpeAogCiBkZWYgZWNob19leGNlcHRpb25fc3Rkb3V0KG15c3RyKToK
ICAgICBleGNlcHRpb25fc3RyID0gc3lzLmV4Y19pbmZvKClbMF0uX19uYW1l
X18gKyAiOiAiICsgc3RyKHN5cy5leGNfaW5mbygpWzFdKQpAQCAtNTAsNyAr
NTEsNyBAQAogICAgIGltcG9ydCBjb2xsZWN0aW9ucwogICAgIGZyb20gcmUg
aW1wb3J0IHNwbGl0CiAgICAgIyBwYXRjaCBwcmV0dHkgcHJpbnRlciwgaXNz
dWUgIzk1MgotICAgIF9teXBwID0gcHJldHR5Ll9fZ2xvYmFsc19fWyJQcmV0
dHlQcmludGVyIl0KKyAgICBfbXlwcCA9IHByZXR0eQogICAgIGRlZiBfbXlf
cmV2X3ByaW50KGNscywgZiwgKiprd2FyZ3MpOgogICAgICAgICBnID0gZi5m
dW5jKCpyZXZlcnNlZChmLmFyZ3MpLCBldmFsdWF0ZT1GYWxzZSkKICAgICAg
ICAgcmV0dXJuIGNscy5fcHJpbnRfRnVuY3Rpb24oZywgKiprd2FyZ3MpCkBA
IC0xODQsNyArMTg1LDcgQEAKICAgICAgICAgICAgIGMgPSBFVC5TdWJFbGVt
ZW50KGV0LCAibGlzdCIpCiAgICAgICAgICAgICBmb3IgeSBpbiB4OgogICAg
ICAgICAgICAgICAgIG9jdG91dHB1dCh5LCBjKQotICAgICAgICBlbGlmIGlz
aW5zdGFuY2UoeCwgc3AuY29tcGF0aWJpbGl0eS5pbnRlZ2VyX3R5cGVzKToK
KyAgICAgICAgZWxpZiBpc2luc3RhbmNlKHgsIHNpeC5pbnRlZ2VyX3R5cGVz
KToKICAgICAgICAgICAgIGEgPSBFVC5TdWJFbGVtZW50KGV0LCAiaXRlbSIp
CiAgICAgICAgICAgICBmID0gRVQuU3ViRWxlbWVudChhLCAiZiIpCiAgICAg
ICAgICAgICBmLnRleHQgPSBzdHIoT0NUQ09ERV9JTlQpCkBAIC0yMDUsNyAr
MjA2LDcgQEAKICAgICAgICAgICAgIGYudGV4dCA9IGQyaGV4KHgucmVhbCkK
ICAgICAgICAgICAgIGYgPSBFVC5TdWJFbGVtZW50KGEsICJmIikKICAgICAg
ICAgICAgIGYudGV4dCA9IGQyaGV4KHguaW1hZykKLSAgICAgICAgZWxpZiBp
c2luc3RhbmNlKHgsIHNwLmNvbXBhdGliaWxpdHkuc3RyaW5nX3R5cGVzKToK
KyAgICAgICAgZWxpZiBpc2luc3RhbmNlKHgsIHNpeC5zdHJpbmdfdHlwZXMp
OgogICAgICAgICAgICAgYSA9IEVULlN1YkVsZW1lbnQoZXQsICJpdGVtIikK
ICAgICAgICAgICAgIGYgPSBFVC5TdWJFbGVtZW50KGEsICJmIikKICAgICAg
ICAgICAgIGYudGV4dCA9IHN0cihPQ1RDT0RFX1NUUikKLS0tIHN5bWJvbGlj
LTIuOS4wL2luc3QvQHN5bS9tcmRpdmlkZS5tCTIwMjAtMDMtMDkgMDU6NDM6
MTUuMDAwMDAwMDAwICsxMTAwCisrKyBzeW1ib2xpYy0yLjkuMC5uZXcvL2lu
c3QvQHN5bS9tcmRpdmlkZS5tCTIwMjAtMTItMTMgMTE6NDU6MjUuNzk1MTQ1
Mzk1ICsxMTAwCkBAIC0xMDEsNyArMTAxLDcgQEAKICUhIGFzc2VydCAoaXNl
cXVhbCAoIEEvMiAsIEQvMiAgKSkKICUhIGFzc2VydCAoaXNlcXVhbCAoIEEv
c3ltKDIpICwgRC8yICApKQogCi0lIXRlc3QKKyUheHRlc3QKICUhICUgSS9B
OiBlaXRoZXIgaW52ZXJ0IEEgb3IgbGVhdmUgdW5ldmFsdWF0ZWQ6IG5vdCBi
b3RoZXJlZCB3aGljaAogJSEgQSA9IHN5bShbMSAyOyAzIDRdKTsKICUhIEIg
PSBzeW0oZXllKDIpKSAvIEE7CkBAIC0xMTMsNyArMTEzLDcgQEAKICUhIEIg
PSBzeW0oJ0ltbXV0YWJsZURlbnNlTWF0cml4KFtbSW50ZWdlcigxKSwgSW50
ZWdlcigyKV0sIFtJbnRlZ2VyKDMpLCBJbnRlZ2VyKDQpXV0pJyk7CiAlISBh
c3NlcnQgKGlzZXF1YWwgKEEvQSwgQi9CKSkKIAotJSF0ZXN0CislIXh0ZXN0
CiAlISAlIEEgPSBDL0IgaXMgQyA9IEEqQgogJSEgQSA9IHN5bShbMSAyOyAz
IDRdKTsKICUhIEIgPSBzeW0oWzEgMzsgNCA4XSk7CkBAIC0xMzAsNyArMTMw
LDcgQEAKICUhIGFzc2VydCAoaXNlcXVhbCAoQigyLDEpLCAwKSkKICUhIGFz
c2VydCAoaXNlcXVhbCAoQigxLDIpLCAwKSkKIAotJSF0ZXN0CislIXh0ZXN0
CiAlISBBID0gc3ltKFs1IDZdKTsKICUhIEIgPSBzeW0oWzEgMjsgMyA0XSk7
CiAlISBDID0gQSpCOwotLS0gc3ltYm9saWMtMi45LjAvaW5zdC9Ac3ltL2Rz
b2x2ZS5tCTIwMjAtMDMtMDkgMDU6NDM6MTUuMDAwMDAwMDAwICsxMTAwCisr
KyBzeW1ib2xpYy0yLjkuMC5uZXcvL2luc3QvQHN5bS9kc29sdmUubQkyMDIw
LTEyLTEzIDExOjQ1OjI1Ljc5NTE0NTM5NSArMTEwMApAQCAtMjY2LDcgKzI2
Niw3IEBACiAlISBnID0gMypzaW4oMip4KSp0YW4oc3ltKCcyJykpKzMqY29z
KDIqeCk7CiAlISBhc3NlcnQgKGlzZXF1YWwgKHJocyhmKSwgZykpCiAKLSUh
dGVzdAorJSF4dGVzdAogJSEgJSBTeXN0ZW0gb2YgT0RFcwogJSEgc3ltcyB4
KHQpIHkodCkgQzEgQzIKICUhIG9kZTEgPSBkaWZmKHgodCksdCkgPT0gMip5
KHQpOwotLS0gc3ltYm9saWMtMi45LjAvaW5zdC9Ac3ltL21wb3dlci5tCTIw
MjAtMDMtMDkgMDU6NDM6MTUuMDAwMDAwMDAwICsxMTAwCisrKyBzeW1ib2xp
Yy0yLjkuMC5uZXcvL2luc3QvQHN5bS9tcG93ZXIubQkyMDIwLTEyLTEzIDEx
OjQ1OjI1Ljc5NTE0NTM5NSArMTEwMApAQCAtMTMwLDcgKzEzMCw3IEBACiAl
ISBDID0gc3VicyhCLCBuLCAwKTsKICUhIGFzc2VydCAoaXNlcXVhbCAoQywg
c3ltKGV5ZSgyKSkpKQogCi0lIXRlc3QKKyUheHRlc3QKICUhICUgc2NhbGFy
XmFycmF5IG5vdCBpbXBsZW1lbnRlZCBpbiBTeW1QeSA8IDEuMAogJSEgc3lt
cyB4CiAlISBBID0gWzEgMjsgMyA0XTsK
====
EOF
uudecode sympy-1.6.patch.uue > sympy-1.6.patch
cat > collect.m.uue << 'EOF'
begin-base64 644 collect.m
JSUgQ29weXJpZ2h0IChDKSAyMDE0LCAyMDE2LTIwMTkgQ29saW4gQi4gTWFj
ZG9uYWxkCiUlCiUlIFRoZSBzeW1ib2xpYy0yLjkuMCBwYWNrYWdlIGRvZXMg
bm90IHN1cHBvcnQgdGhlIFN5bVB5IGNvbGxlY3QgZnVuY3Rpb24uCiUlIFRo
aXMgY29kZSBpcyBjb3BpZWQgZnJvbSBvY3RhdmUvcGFja2FnZXMvc3ltYm9s
aWMtMi45LjAvQHN5bS9mYWN0b3IubQoKJSUKJSUgT2N0U3ltUHkgaXMgZnJl
ZSBzb2Z0d2FyZTsgeW91IGNhbiByZWRpc3RyaWJ1dGUgaXQgYW5kL29yIG1v
ZGlmeQolJSBpdCB1bmRlciB0aGUgdGVybXMgb2YgdGhlIEdOVSBHZW5lcmFs
IFB1YmxpYyBMaWNlbnNlIGFzIHB1Ymxpc2hlZAolJSBieSB0aGUgRnJlZSBT
b2Z0d2FyZSBGb3VuZGF0aW9uOyBlaXRoZXIgdmVyc2lvbiAzIG9mIHRoZSBM
aWNlbnNlLAolJSBvciAoYXQgeW91ciBvcHRpb24pIGFueSBsYXRlciB2ZXJz
aW9uLgolJQolJSBUaGlzIHNvZnR3YXJlIGlzIGRpc3RyaWJ1dGVkIGluIHRo
ZSBob3BlIHRoYXQgaXQgd2lsbCBiZSB1c2VmdWwsCiUlIGJ1dCBXSVRIT1VU
IEFOWSBXQVJSQU5UWTsgd2l0aG91dCBldmVuIHRoZSBpbXBsaWVkIHdhcnJh
bnR5CiUlIG9mIE1FUkNIQU5UQUJJTElUWSBvciBGSVRORVNTIEZPUiBBIFBB
UlRJQ1VMQVIgUFVSUE9TRS4gIFNlZQolJSB0aGUgR05VIEdlbmVyYWwgUHVi
bGljIExpY2Vuc2UgZm9yIG1vcmUgZGV0YWlscy4KJSUKJSUgWW91IHNob3Vs
ZCBoYXZlIHJlY2VpdmVkIGEgY29weSBvZiB0aGUgR05VIEdlbmVyYWwgUHVi
bGljCiUlIExpY2Vuc2UgYWxvbmcgd2l0aCB0aGlzIHNvZnR3YXJlOyBzZWUg
dGhlIGZpbGUgQ09QWUlORy4KJSUgSWYgbm90LCBzZWUgPGh0dHA6Ly93d3cu
Z251Lm9yZy9saWNlbnNlcy8+LgoKJSUgLSotIHRleGluZm8gLSotCiUlIEBk
b2N1bWVudGVuY29kaW5nIFVURi04CiUlIEBkZWZ0eXBlbWV0aG9kICBAQHN5
bSB7QHZhcntlfSA9fSBjb2xsZWN0IChAdmFye2Z9LCBAdmFye3h9KQolJSBD
b2xsZWN0IGNvbW1vbiBwb3dlcnMgb2YgYSB0ZXJtIGluIGFuIGV4cHJlc3Np
b24uCiUlCiUlIEFuIGV4YW1wbGUgb2YgY29sbGVjdGluZyB0ZXJtcyBpbiBh
IHBvbHlub21pYWw6CiUlIEBleGFtcGxlCiUlIEBncm91cAolJSBzeW1zIHgg
eSB6CiUlIGUgPSBjb2xsZWN0KFt4KnkgKyB4IC0gMyArIDIqeF4yIC0geip4
XjMgKyB4XjNdLCB4KQolJSAgIEByZXN1bHR7fSAoc3ltKSB4XjPii4UoMSAt
IHopICsgMuKLhXheMiAgKyB44ouFKHkgKyAxKSAtIDMKJSUgQGVuZCBncm91
cAolJSBAZW5kIGV4YW1wbGUKJSUKJSUgQHNlZWFsc297QEBzeW0vZXhwYW5k
fQolJSBAZW5kIGRlZnR5cGVtZXRob2QKCgpmdW5jdGlvbiBlID0gY29sbGVj
dChmLCB2YXJhcmdpbikKICAKICBpZiAobmFyZ291dCA+IDEpCiAgICBwcmlu
dF91c2FnZSAoKTsKICBlbmRpZgoKICBmID0gc3ltKGYpOwogIGZvciBpID0g
MTpsZW5ndGgodmFyYXJnaW4pCiAgICB2YXJhcmdpbntpfSA9IHN5bSh2YXJh
cmdpbntpfSk7CiAgZW5kZm9yCiAgCiAgZSA9IHB5Y2FsbF9zeW1weV9fICgn
cmV0dXJuIGNvbGxlY3QoKl9pbnMpJywgZiwgdmFyYXJnaW57On0pOwoKZW5k
ZnVuY3Rpb24KCiUhdGVzdCBzeW1zIHggeSB6CiUhIGYgPSBbeCp5ICsgeCAt
IDMgKyAyKnheMiAtIHoqeF4zICsgeF4zXQolISBhc3NlcnQoIGxvZ2ljYWwg
KGNvbGxlY3QoZix4KSA9PSAoKHheMykqKDEgLSB6KSArIDIqKHheMikgICsg
eCooeSArIDEpIC0gMykpKQoK
====
EOF
uudecode collect.m.uue > collect.m
tar -xf $SYMBOLIC_ARCHIVE
mv -f collect.m symbolic-$SYMBOLIC_VER/inst/@sym
pushd symbolic-$SYMBOLIC_VER
patch -p1 < ../sympy-1.6.patch
popd
NEW_SYMBOLIC_ARCHIVE=symbolic-$SYMBOLIC_VER".new.tar.gz"
tar -czf $NEW_SYMBOLIC_ARCHIVE symbolic-$SYMBOLIC_VER
rm -Rf symbolic-$SYMBOLIC_VER sympy-1.6.patch.uue sympy-1.6.patch collect.m.uue

$OCTAVE_BIN_DIR/octave-cli --eval "pkg -verbose install "$NEW_SYMBOLIC_ARCHIVE
rm -f $NEW_SYMBOLIC_ARCHIVE

#
# Installing Octave-Forge packages is done
#
$OCTAVE_BIN_DIR/octave-cli --eval "pkg list"

#
# Install solver packages from the GitHub forked repositories
#

GITHUB_URL="https://github.com/robertgj"

OCTAVE_LOCAL_VERSION=\
"`$OCTAVE_BIN_DIR/octave-cli --eval 'disp(OCTAVE_VERSION);'`"
OCTAVE_SITE_M_DIR=$OCTAVE_SHARE_DIR/$OCTAVE_LOCAL_VERSION/site/m

# Install SeDuMi
if ! test -f sedumi-master.zip ; then
    wget -c $GITHUB_URL/sedumi/archive/master.zip
    mv -f master.zip sedumi-master.zip
fi
rm -Rf sedumi-master $OCTAVE_SITE_M_DIR/SeDuMi
unzip sedumi-master.zip
rm -f sedumi-master/vec.m
rm -f sedumi-master/*.mex*
mv -f sedumi-master $OCTAVE_SITE_M_DIR/SeDuMi
if test $? -ne 0;then rm -Rf sedumi-master; exit -1; fi
$OCTAVE_BIN_DIR/octave-cli $OCTAVE_SITE_M_DIR/SeDuMi/install_sedumi.m

# Install SDPT3
if ! test -f sdpt3-master.zip ; then
   wget -c $GITHUB_URL/sdpt3/archive/master.zip
   mv master.zip sdpt3-master.zip
fi
rm -Rf sdpt3-master $OCTAVE_SITE_M_DIR/SDPT3
unzip sdpt3-master.zip 
rm -f sdpt3-master/Solver/Mexfun/*.mex*
rm -Rf sdpt3-master/Solver/Mexfun/o_win
mv sdpt3-master $OCTAVE_SITE_M_DIR/SDPT3
if test $? -ne 0;then rm -Rf sdpt3-master; exit -1; fi
$OCTAVE_BIN_DIR/octave-cli $OCTAVE_SITE_M_DIR/SDPT3/install_sdpt3.m

# Install YALMIP
if ! test -f YALMIP-develop.zip ; then
   wget -c $GITHUB_URL/YALMIP/archive/develop.zip
   mv develop.zip YALMIP-develop.zip
fi
rm -Rf YALMIP-develop $OCTAVE_SITE_M_DIR/YALMIP
unzip YALMIP-develop.zip 
mv YALMIP-develop $OCTAVE_SITE_M_DIR/YALMIP
if test $? -ne 0;then rm -Rf YALMIP-develop; exit -1; fi

# Install SparsePOP
if ! test -f SparsePOP-master.zip ; then
   wget -c $GITHUB_URL/SparsePOP/archive/master.zip
   mv master.zip SparsePOP-master.zip
fi
rm -Rf SparsePOP-master $OCTAVE_SITE_M_DIR/SparsePOP
unzip SparsePOP-master.zip
find SparsePOP-master -name \*.mex* -exec rm -f {} ';'
mv SparsePOP-master $OCTAVE_SITE_M_DIR/SparsePOP
if test $? -ne 0;then rm -Rf SparsePOP-master; exit -1; fi
# !! Do not build the SparsePOP .mex files !!
# $OCTAVE_BIN_DIR/octave-cli $OCTAVE_SITE_M_DIR/SparsePOP/compileSparsePOP.m

#
# Solver installation done
#
