allpass2ndOrderCascade_socp_sqmag_test_FIGURES = \
allpass2ndOrderCascade_socp_sqmag_test_ab0 \
allpass2ndOrderCascade_socp_sqmag_test_ab1pass \
allpass2ndOrderCascade_socp_sqmag_test_ab1pz \
allpass2ndOrderCascade_socp_sqmag_test_ab1 \
allpass2ndOrderCascade_socp_sqmag_test_ab1dual \
allpass2ndOrderCascade_socp_sqmag_test_ellip \
allpass2ndOrderCascade_socp_sqmag_test_ellipdual \
allpass2ndOrderCascade_socp_sqmag_test_ellippz

allpass2ndOrderCascade_socp_sqmag_test_COEFS = \
allpass2ndOrderCascade_socp_sqmag_test.mat \
allpass2ndOrderCascade_socp_sqmag_test_spec.m \
allpass2ndOrderCascade_socp_sqmag_test_a1_coef.m \
allpass2ndOrderCascade_socp_sqmag_test_b1_coef.m \
allpass2ndOrderCascade_socp_sqmag_test_Da1_coef.m \
allpass2ndOrderCascade_socp_sqmag_test_Db1_coef.m \
allpass2ndOrderCascade_socp_sqmag_test_Nellip_coef.m \
allpass2ndOrderCascade_socp_sqmag_test_Dellip_coef.m

allpass2ndOrderCascade_socp_sqmag_test_FILES = \
allpass2ndOrderCascade_socp_sqmag_test.m test_common.m delayz.m \
stability2ndOrderCascade.m print_polynomial.m allpass2ndOrderCascade.m \
allpass2ndOrderCascade_socp.m casc2tf.m tf2casc.m qroots.m qzsolve.oct \

allpass2ndOrderCascade_socp_sqmag_test.diary : \
tarczynski_allpass2ndOrderCascade_test.diary
