branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_FIGURES = \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_amplitude \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_phase \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_delay

branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_COEFS = \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_coef.m \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_sd_coef.m \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_Ito_sd_coef.m \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_allocsd_digits.m \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_min_coef.m \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_min_adders.tab \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_cost.tab

branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_FILES = \
branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test.m \
test_common.m \
directFIRnonsymmetric_allocsd_Ito.m \
directFIRnonsymmetricAsq.m directFIRnonsymmetricP.m directFIRnonsymmetricT.m \
 directFIRnonsymmetricEsq.m local_max.m print_polynomial.m \
flt2SD.m SDadders.m x2nextra.m bin2SDul.m bin2SD.oct bin2SPT.oct

branch_bound_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test.diary : \
directFIRnonsymmetric_socp_slb_bandpass_hilbert_test.diary
