branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_FIGURES = \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_amplitude_response \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_pass_relative_amplitude_response

branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_COEFS = \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_cost.tab \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_h0_coef.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_coef.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_sd_no_alloc_coef.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_sd_coef.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_allocsd_digits.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_coef.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_adders.m \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_signed_digits.m

branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_FILES= \
branch_bound_directFIRantisymmetric_lowpass_differentiator_12_nbits_test.m \
test_common.m \
selesnickFIRantisymmetric_linear_differentiator.m \
directFIRantisymmetric_socp_mmse.m \
directFIRantisymmetric_allocsd_Lim.m \
directFIRantisymmetricEsq.m \
directFIRantisymmetricA.m \
print_polynomial.m local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct

