branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_FIGURES = \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_kuv_minAsq \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_kuv_minP \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_kuv_minT \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_remez

branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_COEFS = \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_cost.tab \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_k0_sd_coef.m \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_u0_sd_coef.m \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_v0_sd_coef.m \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_k_min_coef.m \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_u_min_coef.m \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_v_min_coef.m 


branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test_FILES = \
branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test.m \
test_common.m schurOneMAPlattice_frm_hilbert_socp_mmse.m \
schurOneMAPlattice_frm_hilbert_slb_set_empty_constraints.m \
schurOneMAPlattice_frm_hilbert_slb_constraints_are_empty.m \
schurOneMAPlattice_frm_hilbert_slb_exchange_constraints.m \
schurOneMAPlattice_frm_hilbert_slb_update_constraints.m \
schurOneMAPlattice_frm_hilbert_slb_show_constraints.m \
schurOneMAPlattice_frm_hilbert_slb.m \
schurOneMAPlattice_frm_hilbert_allocsd_Ito.m \
schurOneMAPlattice_frm_hilbert_allocsd_Lim.m \
schurOneMAPlattice_frm_hilbertEsq.m schurOneMAPlattice_frm_hilbertAsq.m \
schurOneMAPlattice_frm_hilbertP.m schurOneMAPlattice_frm_hilbertT.m  \
schurOneMAPlatticeT.m schurOneMAPlatticeP.m schurOneMAPlattice2Abcd.m \
bin2SDul.m Abcd2tf.m schurOneMscale.m H2Asq.m H2T.m H2P.m flt2SD.m \
x2nextra.m local_max.m print_polynomial.m SDadders.m \
schurOneMAPlattice2H.oct schurdecomp.oct schurexpand.oct \
bin2SD.oct bitflip.oct bin2SPT.oct schurOneMlattice2Abcd.oct \
schurOneMlattice2H.oct complex_zhong_inverse.oct 

branch_bound_schurOneMAPlattice_frm_hilbert_12_nbits_test.diary : \
schurOneMAPlattice_frm_hilbert_socp_slb_test.diary
