branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_FIGURES = \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_initial_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_initial_sd_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_amplitude_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_stop_amplitude_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_pass_amplitude_error \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_pass_relative_error \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_pass_phase_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_pass_delay_response \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_pass_dCsqdw_error \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_D1k_min_pz \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_D2k_min_pz \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_k_min_pz

branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_COEFS = \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_k_allocsd_digits.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A1k_allocsd_digits.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A2k_allocsd_digits.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A1k0_sd_coef.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A2k0_sd_coef.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A1k_min_coef.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_A2k_min_coef.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_k_min_digits.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_k_min_adders.m \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_cost.tab

branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test_FILES = \
branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test.m \
test_common.m \
schurOneMPAlatticeAsq.m \
schurOneMPAlatticeT.m \
schurOneMPAlatticeP.m \
schurOneMPAlatticedAsqdw.m \
schurOneMPAlatticeEsq.m \
schurOneMPAlattice2tf.m \
schurOneMAPlattice2Abcd.m \
schurOneMPAlattice_allocsd_Lim.m \
schurOneMPAlattice_allocsd_Ito.m \
tf2schurOneMlattice.m \
schurOneMAPlattice2tf.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_slb_show_constraints.m \
H2Asq.m H2T.m H2P.m H2dAsqdw.m flt2SD.m bin2SDul.m SDadders.m x2nextra.m \
schurOneMscale.m print_polynomial.m Abcd2tf.m local_max.m delayz.m \
qroots.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMAPlattice2H.oct

branch_bound_schurOneMPAlattice_lowpass_differentiator_12_nbits_test.diary : \
schurOneMPAlattice_socp_slb_lowpass_differentiator_test.diary
