branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_FIGURES = \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_pass \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_stop

branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_COEFS = \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test.mat \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_spec.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_k_min_coef.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_p_min_coef.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_c_min_coef.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_kk_min_coef.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_ck_min_coef.m \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_cost.tab

branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test_FILES = \
branch_bound_schurOneMlatticePipelined_lowpass_16_nbits_test.m test_common.m \
schurOneMlatticePipelinedAsq.m schurOneMlatticePipelinedT.m \
schurOneMlatticePipelinedP.m schurOneMlatticePipelinedEsq.m \
schurOneMscale.m tf2schurOneMlattice.m \
local_max.m x2tf.m tf2pa.m print_polynomial.m Abcd2tf.m \
H2Asq.m H2T.m H2P.m flt2SD.m bin2SDul.m x2nextra.m SDadders.m \
schurdecomp.oct schurexpand.oct Abcd2H.oct bin2SPT.oct qroots.oct 
