branch_bound_directFIRhilbert_bandpass_12_nbits_test_FIGURES = \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_response

branch_bound_directFIRhilbert_bandpass_12_nbits_test_COEFS = \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM_allocsd_digits.m \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM2_coef.m \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM2_sd_coef.m \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM_sd_coef.m \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM_min_coef.m \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_hM_adders.tab \
branch_bound_directFIRhilbert_bandpass_12_nbits_test_cost.tab

branch_bound_directFIRhilbert_bandpass_12_nbits_test_FILES = \
branch_bound_directFIRhilbert_bandpass_12_nbits_test.m test_common.m \
directFIRhilbertA.m directFIRhilbertEsqPW.m local_max.m print_polynomial.m \
flt2SD.m SDadders.m x2nextra.m bin2SDul.m bin2SD.oct bin2SPT.oct

branch_bound_directFIRhilbert_bandpass_12_nbits_test.diary : \
directFIRhilbert_bandpass_slb_test.diary
