comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FIGURES = \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_amplitude \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_stop \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_phase \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_delay \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_dAsqdw

comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_COEFS = \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_cost.tab

comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FILES = \
comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
schurOneMlattice_allocsd_Lim.m \
print_polynomial.m Abcd2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
flt2SD.m x2nextra.m bin2SDul.m SDadders.m \
qroots.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMlattice2H.oct

comparison_no_POP_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.diary : \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test.diary \
branch_bound_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.diary \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.diary
