directFIRnonsymmetric_kyp_bandpass_test_FIGURES = \
directFIRnonsymmetric_kyp_bandpass_test_response \
directFIRnonsymmetric_kyp_bandpass_test_passband \
directFIRnonsymmetric_kyp_bandpass_test_k_kc_response

directFIRnonsymmetric_kyp_bandpass_test_COEFS = \
directFIRnonsymmetric_kyp_bandpass_test.mat \
directFIRnonsymmetric_kyp_bandpass_test.spec \
directFIRnonsymmetric_kyp_bandpass_test_max_passband_squared_error.tab \
directFIRnonsymmetric_kyp_bandpass_test_h_coef.m \
directFIRnonsymmetric_kyp_bandpass_test_k_coef.m \
directFIRnonsymmetric_kyp_bandpass_test_kc_coef.m 

directFIRnonsymmetric_kyp_bandpass_test_FILES = \
directFIRnonsymmetric_kyp_bandpass_test.m test_common.m delayz.m \
direct_form_scale.m complementaryFIRlattice.m complementaryFIRlatticeAsq.m \
complementaryFIRlatticeT.m minphase.m complementaryFIRlattice2Abcd.m \
H2Asq.m H2T.m print_polynomial.m complementaryFIRlatticeFilter.m crossWelch.m \
complementaryFIRdecomp.oct Abcd2H.oct
