directFIRsymmetric_kyp_union_bandpass_test_FIGURES = \
directFIRsymmetric_kyp_union_bandpass_test_response

directFIRsymmetric_kyp_union_bandpass_test_COEFS = \
directFIRsymmetric_kyp_union_bandpass_test.mat \
directFIRsymmetric_kyp_union_bandpass_test.spec \
directFIRsymmetric_kyp_union_bandpass_test_h_coef.m \
directFIRsymmetric_kyp_union_bandpass_test_max_passband_squared_error.tab

directFIRsymmetric_kyp_union_bandpass_test_FILES = \
directFIRsymmetric_kyp_union_bandpass_test.m test_common.m print_polynomial.m
