directFIRnonsymmetric_kyp_union_double_bandpass_test_FIGURES = \
directFIRnonsymmetric_kyp_union_double_bandpass_test_response 

directFIRnonsymmetric_kyp_union_double_bandpass_test_COEFS = \
directFIRnonsymmetric_kyp_union_double_bandpass_test_h_coef.m \
directFIRnonsymmetric_kyp_union_double_bandpass_test_max_passband_squared_error.tab

directFIRnonsymmetric_kyp_union_double_bandpass_test_FILES = \
directFIRnonsymmetric_kyp_union_double_bandpass_test.m \
test_common.m delayz.m print_polynomial.m
