directFIRnonsymmetric_kyp_lowpass_test_FIGURES = \
directFIRnonsymmetric_kyp_lowpass_test_response 

directFIRnonsymmetric_kyp_lowpass_test_COEFS = \
directFIRnonsymmetric_kyp_lowpass_test.mat \
directFIRnonsymmetric_kyp_lowpass_test_spec.m \
directFIRnonsymmetric_kyp_lowpass_test_h_coef.m \
directFIRnonsymmetric_kyp_lowpass_test_max_passband_squared_error.tab \
directFIRnonsymmetric_kyp_lowpass_test_max_stopband_squared_error.tab

directFIRnonsymmetric_kyp_lowpass_test_FILES = \
directFIRnonsymmetric_kyp_lowpass_test.m test_common.m delayz.m \
directFIRnonsymmetricEsqPW.m konopacki.m print_polynomial.m
