directFIRsymmetric_kyp_lowpass_test_FIGURES = \
directFIRsymmetric_kyp_lowpass_test_response \
directFIRsymmetric_kyp_lowpass_test_mcclellan

directFIRsymmetric_kyp_lowpass_test_COEFS = \
directFIRsymmetric_kyp_lowpass_test.mat \
directFIRsymmetric_kyp_lowpass_test.spec \
directFIRsymmetric_kyp_lowpass_test_h_coef.m \
directFIRsymmetric_kyp_lowpass_test_max_passband_squared_error.tab \
directFIRsymmetric_kyp_lowpass_test_max_stopband_squared_error.tab \
directFIRsymmetric_kyp_lowpass_test_mcclellan.spec \
directFIRsymmetric_kyp_lowpass_test_mcclellan_hM_coef.m

directFIRsymmetric_kyp_lowpass_test_FILES = \
directFIRsymmetric_kyp_lowpass_test.m test_common.m \
directFIRsymmetricEsqPW.m print_polynomial.m
