herrmannFIRsymmetric_flat_lowpass_test_FIGURES = \
herrmannFIRsymmetric_flat_lowpass_test_M_10_K_1_M

herrmannFIRsymmetric_flat_lowpass_test_COEFS = \
herrmannFIRsymmetric_flat_lowpass_test_hM18K11_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_aM18K11_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_hM18K12_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_aM18K12_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_hM19K11_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_aM19K11_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_hM19K12_coef.m \
herrmannFIRsymmetric_flat_lowpass_test_aM19K12_coef.m

herrmannFIRsymmetric_flat_lowpass_test_FILES = \
herrmannFIRsymmetric_flat_lowpass_test.m test_common.m \
herrmannFIRsymmetric_flat_lowpass.m directFIRsymmetricA.m print_polynomial.m
