hofstetterFIRsymmetric_multiband_test_FIGURES = \
hofstetterFIRsymmetric_multiband_test_response \
hofstetterFIRsymmetric_multiband_test_dual \
hofstetterFIRsymmetric_multiband_test_zeros

hofstetterFIRsymmetric_multiband_test_COEFS = \
hofstetterFIRsymmetric_multiband_test.mat \
hofstetterFIRsymmetric_multiband_test_spec.m \
hofstetterFIRsymmetric_multiband_test_hM_coef.m

hofstetterFIRsymmetric_multiband_test_FILES = \
hofstetterFIRsymmetric_multiband_test.m test_common.m print_polynomial.m \
hofstetterFIRsymmetric.m local_max.m lagrange_interp.m directFIRsymmetricA.m \
xfr2tf.m
