iir_sqp_slb_lowpass_differentiator_alternate_test_FIGURES = \
iir_sqp_slb_lowpass_differentiator_alternate_test_initial_x0_response \
iir_sqp_slb_lowpass_differentiator_alternate_test_initial_x0_pz \
iir_sqp_slb_lowpass_differentiator_alternate_test_mmse_x1_response \
iir_sqp_slb_lowpass_differentiator_alternate_test_mmse_x1_pz \
iir_sqp_slb_lowpass_differentiator_alternate_test_pcls_d1z_response \
iir_sqp_slb_lowpass_differentiator_alternate_test_pcls_d1z_pz

iir_sqp_slb_lowpass_differentiator_alternate_test_COEFS = \
iir_sqp_slb_lowpass_differentiator_alternate_test_d1z_coef.m \
iir_sqp_slb_lowpass_differentiator_alternate_test_N1_coef.m \
iir_sqp_slb_lowpass_differentiator_alternate_test_D1_coef.m \
iir_sqp_slb_lowpass_differentiator_alternate_test_spec.m \
iir_sqp_slb_lowpass_differentiator_alternate_test.mat

iir_sqp_slb_lowpass_differentiator_alternate_test_FILES = \
iir_sqp_slb_lowpass_differentiator_alternate_test.m \
test_common.m print_polynomial.m print_pole_zero.m \
iir_slb.m iir_sqp_mmse.m iir_slb_exchange_constraints.m \
iir_slb_set_empty_constraints.m iir_slb_constraints_are_empty.m \
iir_slb_show_constraints.m iir_slb_update_constraints.m \
armijo_kim.m cl2bp.m fixResultNaN.m iirA.m iirE.m \
iirT.m iirP.m invSVD.m local_max.m showZPplot.m \
sqp_bfgs.m zp2x.m tf2x.m updateWchol.m updateWbfgs.m x2tf.m xConstraints.m \
qroots.m qzsolve.oct

iir_sqp_slb_lowpass_differentiator_alternate_test.diary : \
tarczynski_lowpass_differentiator_alternate_test.diary
