mcclellanFIRsymmetric_flat_lowpass_test_FIGURES = \
mcclellanFIRsymmetric_flat_lowpass_test_response \
mcclellanFIRsymmetric_flat_lowpass_test_dual

mcclellanFIRsymmetric_flat_lowpass_test_COEFS = \
mcclellanFIRsymmetric_flat_lowpass_test.mat \
mcclellanFIRsymmetric_flat_lowpass_test_spec.m \
mcclellanFIRsymmetric_flat_lowpass_test_hM_coef.m \
mcclellanFIRsymmetric_flat_lowpass_test_hA_coef.m \
mcclellanFIRsymmetric_flat_lowpass_test_rho.tab 

mcclellanFIRsymmetric_flat_lowpass_test_FILES = \
mcclellanFIRsymmetric_flat_lowpass_test.m test_common.m print_polynomial.m \
mcclellanFIRsymmetric.m local_max.m lagrange_interp.m \
xfr2tf.m directFIRsymmetricA.m
