mcclellanFIRsymmetric_lowpass_alternate_test_FIGURES = \
mcclellanFIRsymmetric_lowpass_alternate_test_response \
mcclellanFIRsymmetric_lowpass_alternate_test_dual

mcclellanFIRsymmetric_lowpass_alternate_test_COEFS = \
mcclellanFIRsymmetric_lowpass_alternate_test.mat \
mcclellanFIRsymmetric_lowpass_alternate_test_spec.m \
mcclellanFIRsymmetric_lowpass_alternate_test_hM_coef.m \
mcclellanFIRsymmetric_lowpass_alternate_test_rho.tab

mcclellanFIRsymmetric_lowpass_alternate_test_FILES = \
mcclellanFIRsymmetric_lowpass_alternate_test.m test_common.m \
print_polynomial.m mcclellanFIRsymmetric.m local_max.m lagrange_interp.m \
xfr2tf.m directFIRsymmetricA.m
