mcclellanFIRsymmetric_bandpass_test_FIGURES = \
mcclellanFIRsymmetric_bandpass_test_response \
mcclellanFIRsymmetric_bandpass_test_dual \
mcclellanFIRsymmetric_bandpass_test_zeros

mcclellanFIRsymmetric_bandpass_test_COEFS = \
mcclellanFIRsymmetric_bandpass_test.mat \
mcclellanFIRsymmetric_bandpass_test_spec.m \
mcclellanFIRsymmetric_bandpass_test_hM_coef.m \
mcclellanFIRsymmetric_bandpass_test_hM_LD_coef.m \
mcclellanFIRsymmetric_bandpass_test_rho.tab

mcclellanFIRsymmetric_bandpass_test_FILES = \
mcclellanFIRsymmetric_bandpass_test.m test_common.m print_polynomial.m \
mcclellanFIRsymmetric.m local_max.m lagrange_interp.m \
xfr2tf.m directFIRsymmetricA.m \
qroots.oct
