mcclellanFIRantisymmetric_linear_differentiator_test_FIGURES = \
mcclellanFIRantisymmetric_linear_differentiator_test_response \
mcclellanFIRantisymmetric_linear_differentiator_test_error \
mcclellanFIRantisymmetric_linear_differentiator_test_dual \
mcclellanFIRantisymmetric_linear_differentiator_test_zeros \
mcclellanFIRantisymmetric_linear_differentiator_test_feasible

mcclellanFIRantisymmetric_linear_differentiator_test_COEFS = \
mcclellanFIRantisymmetric_linear_differentiator_test.mat \
mcclellanFIRantisymmetric_linear_differentiator_test_spec.m \
mcclellanFIRantisymmetric_linear_differentiator_test_hAM56_coef.m \
mcclellanFIRantisymmetric_linear_differentiator_test_hA56_coef.m \
mcclellanFIRantisymmetric_linear_differentiator_test_hAM57_coef.m \
mcclellanFIRantisymmetric_linear_differentiator_test_hA57_coef.m

mcclellanFIRantisymmetric_linear_differentiator_test_FILES = \
mcclellanFIRantisymmetric_linear_differentiator_test.m test_common.m \
mcclellanFIRantisymmetric_linear_differentiator.m print_polynomial.m \
local_max.m qroots.m \
qzsolve.oct
