mcclellanFIRsymmetric_multiband_test_FIGURES = \
mcclellanFIRsymmetric_multiband_test_response \
mcclellanFIRsymmetric_multiband_test_dual \
mcclellanFIRsymmetric_multiband_test_zeros

mcclellanFIRsymmetric_multiband_test_COEFS = \
mcclellanFIRsymmetric_multiband_test.mat \
mcclellanFIRsymmetric_multiband_test_spec.m \
mcclellanFIRsymmetric_multiband_test_hM_coef.m \
mcclellanFIRsymmetric_multiband_test_rho.tab

mcclellanFIRsymmetric_multiband_test_FILES = \
mcclellanFIRsymmetric_multiband_test.m test_common.m print_polynomial.m \
mcclellanFIRsymmetric.m local_max.m lagrange_interp.m directFIRsymmetricA.m \
xfr2tf.m qroots.m \
qzsolve.oct
