parallel_allpass_socp_slb_bandpass_hilbert_R2_test_FIGURES = \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_ab0 \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_ab1 \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_ab1pass \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_a1pz \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_b1pz

parallel_allpass_socp_slb_bandpass_hilbert_R2_test_COEFS = \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_a1_coef.m \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_b1_coef.m \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_Da1_coef.m \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_Db1_coef.m \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_Dab1_coef.m \
parallel_allpass_socp_slb_bandpass_hilbert_R2_test_Nab1_coef.m

parallel_allpass_socp_slb_bandpass_hilbert_R2_test_FILES = \
test/parallel_allpass_socp_slb_bandpass_hilbert_R2_test.m \
test_common.m \
parallel_allpassAsq.m \
parallel_allpassT.m \
parallel_allpassP.m \
parallel_allpass_slb.m \
parallel_allpass_slb_constraints_are_empty.m \
parallel_allpass_slb_exchange_constraints.m \
parallel_allpass_slb_set_empty_constraints.m \
parallel_allpass_slb_show_constraints.m \
parallel_allpass_slb_update_constraints.m \
parallel_allpass_socp_mmse.m \
delayz.m allpassP.m allpassT.m tf2a.m a2tf.m tf2pa.m aConstraints.m \
print_polynomial.m print_allpass_pole.m local_max.m \
qroots.oct spectralfactor.oct

parallel_allpass_socp_slb_bandpass_hilbert_R2_test.diary : \
tarczynski_parallel_allpass_bandpass_hilbert_R2_test.diary
