polyphase_allpass_socp_slb_flat_delay_test_FIGURES = \
polyphase_allpass_socp_slb_flat_delay_test_ab0 \
polyphase_allpass_socp_slb_flat_delay_test_ab1 \
polyphase_allpass_socp_slb_flat_delay_test_ab1pass \
polyphase_allpass_socp_slb_flat_delay_test_ab1phase \
polyphase_allpass_socp_slb_flat_delay_test_a1pz \
polyphase_allpass_socp_slb_flat_delay_test_b1pz 

polyphase_allpass_socp_slb_flat_delay_test_COEFS = \
polyphase_allpass_socp_slb_flat_delay_test.mat \
polyphase_allpass_socp_slb_flat_delay_test_spec.m \
polyphase_allpass_socp_slb_flat_delay_test_a1_coef.m \
polyphase_allpass_socp_slb_flat_delay_test_b1_coef.m \
polyphase_allpass_socp_slb_flat_delay_test_Da1_coef.m \
polyphase_allpass_socp_slb_flat_delay_test_Db1_coef.m

polyphase_allpass_socp_slb_flat_delay_test_FILES = \
polyphase_allpass_socp_slb_flat_delay_test.m test_common.m delayz.m \
parallel_allpassAsq.m parallel_allpassT.m parallel_allpassP.m \
parallel_allpass_slb.m \
parallel_allpass_slb_constraints_are_empty.m \
parallel_allpass_slb_exchange_constraints.m \
parallel_allpass_slb_set_empty_constraints.m \
parallel_allpass_slb_show_constraints.m \
parallel_allpass_slb_update_constraints.m \
parallel_allpass_socp_mmse.m allpassP.m allpassT.m tf2a.m a2tf.m \
aConstraints.m print_polynomial.m  local_max.m \
print_allpass_pole.m qroots.oct

polyphase_allpass_socp_slb_flat_delay_test.diary : \
tarczynski_polyphase_allpass_test.diary
