pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FIGURES = \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_delay \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass_error \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_phase \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_stop \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_error \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_pass \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_stop \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_dAsqdw \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pz

pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_COEFS = \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.mat \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_spec.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k_allocsd_digits.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c_allocsd_digits.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k0_sd_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c0_sd_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k0_sd_Ito_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c0_sd_Ito_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_kc_sd_min_digits.tab \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_kc_sd_min_adders.tab \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k_sd_min_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c_sd_min_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_N_sd_min_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_D_sd_min_coef.m \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_cost.tab

pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FILES = \
pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_pop_socp_mmse.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_allocsd_Ito.m \
schurOneMlattice_allocsd_Lim.m \
schurOneMscale.m schurOneMlattice2tf.m \
schurOneMlatticeFilter.m tf2schurOneMlattice.m local_max.m print_polynomial.m \
x2nextra.m H2Asq.m H2T.m H2P.m H2dAsqdw.m flt2SD.m bin2SDul.m SDadders.m \
qroots.m \
qzsolve.oct schurdecomp.oct schurexpand.oct schurOneMlattice2H.oct Abcd2tf.oct \
schurOneMlattice2Abcd.oct bin2SPT.oct bin2SD.oct complex_zhong_inverse.oct

pop_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.diary : \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test.diary
