purczynskiFIRantisymmetric_linear_differentiator_test_FIGURES = \
purczynskiFIRantisymmetric_linear_differentiator_test_response \
purczynskiFIRantisymmetric_linear_differentiator_test_error

purczynskiFIRantisymmetric_linear_differentiator_test_COEFS = \
purczynskiFIRantisymmetric_linear_differentiator_test.mat \
purczynskiFIRantisymmetric_linear_differentiator_test_h2_coef.m \
purczynskiFIRantisymmetric_linear_differentiator_test_h4_coef.m \
purczynskiFIRantisymmetric_linear_differentiator_test_h8_coef.m \
purczynskiFIRantisymmetric_linear_differentiator_test_h16_coef.m 

purczynskiFIRantisymmetric_linear_differentiator_test_FILES = \
purczynskiFIRantisymmetric_linear_differentiator_test.m test_common.m \
purczynskiFIRantisymmetric_linear_differentiator.m print_polynomial.m
