schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_FIGURES = \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_initial_response \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_initial_pz \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_error \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_pass_amplitude_relative_error \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_pz \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_dCsqdw_error \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_dAsqdw_error \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_pcls_dCsqdw_dAsqdw_error \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_direct_sensitivity \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_schur_sensitivity 

schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_COEFS = \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_N0_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_D0R_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_k0_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_epsilon0_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_p0_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_c0_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_k2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_epsilon2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_p2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_c2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_N2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_D2_coef.m

schurOneMlattice_socp_slb_lowpass_differentiator_R2_test_FILES = \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
local_max.m tf2pa.m x2tf.m tf2Abcd.m H2Asq.m H2T.m H2P.m  H2dAsqdw.m \
print_polynomial.m WISEJ.m \
qroots.oct schurOneMlattice2Abcd.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2H.oct Abcd2tf.oct Abcd2H.oct
