schurOneMPAlatticeDelay_lowpass_Esq_comparison_test_COEFS = \
schurOneMPAlatticeDelay_lowpass_Esq_comparison_test.tab

schurOneMPAlatticeDelay_lowpass_Esq_comparison_test_FILES = \
schurOneMPAlatticeDelay_lowpass_Esq_comparison_test.m test_common.m delayz.m \
schurOneMPAlatticeEsq.m schur_lattice_test_common.m schurOneMPAlatticedAsqdw.m \
schurOneMPAlatticeAsq.m schurOneMPAlatticeT.m schurOneMPAlatticeP.m \
tf2schurOneMlattice.m schurOneMAPlattice2Abcd.m schurOneMlattice2Abcd.oct \
H2Asq.m H2T.m H2P.m H2dAsqdw.m tf2pa.m schurOneMscale.m \
schurOneMAPlattice2H.oct spectralfactor.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct qroots.oct

schurOneMPAlatticeDelay_lowpass_Esq_comparison_test.diary: \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test.diary \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_LeeHu_lowpass_test.diary \
schurOneMPAlatticeDelay_socp_slb_lowpass_test.diary
