schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_FIGURES = \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_initial_response \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_error_response \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_response \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_convergence

schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_COEFS = \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test.mat \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_spec.m \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_k0_coef.m \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_k_coef.m

schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test_FILES = \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_Dinh_lowpass_test.m test_common.m \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_lowpass_common_start.m \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_lowpass_common_update.m \
schurOneMPAlatticeDoublyPipelinedDelay_kyp_lowpass_common_finish.m \
schurOneMPAlatticeAsq.m \
schurOneMPAlatticeP.m \
schurOneMPAlatticeT.m \
schurOneMPAlatticeEsq.m \
schurOneMPAlattice_slb.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_socp_mmse.m \
schurOneMPAlattice_slb_exchange_constraints.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_show_constraints.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMPAlattice2tf.m schurOneMAPlatticeDoublyPipelined2Abcd.m \
schurOneMAPlattice2tf.m schurOneMAPlattice2Abcd.m tf2schurOneMlattice.m \
schurOneMscale.m local_max.m tf2pa.m print_polynomial.m \
Abcd2tf.m tf2Abcd.m H2Asq.m H2T.m H2P.m WISEJ_DA.m delayz.m \
Abcd2H.oct schurdecomp.oct complex_zhong_inverse.oct \
schurOneMlattice2Abcd.oct schurOneMAPlattice2H.oct
