schurNSPAlattice_socp_slb_bandpass_hilbert_test_FIGURES = \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_response \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_sim \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1pz \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2pz \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A12pz 

schurNSPAlattice_socp_slb_bandpass_hilbert_test_COEFS = \
schurNSPAlattice_socp_slb_bandpass_hilbert_test.mat \
schurNSPAlattice_socp_slb_bandpass_hilbert_test.spec \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1s20_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1s00_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1s02_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1s22_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2s20_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2s00_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2s02_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2s22_coef.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A1stdx.m \
schurNSPAlattice_socp_slb_bandpass_hilbert_test_A2stdx.m

schurNSPAlattice_socp_slb_bandpass_hilbert_test_FILES = \
schurNSPAlattice_socp_slb_bandpass_hilbert_test.m test_common.m \
schurNSPAlatticeAsq.m \
schurNSPAlatticeT.m \
schurNSPAlatticeP.m \
schurNSPAlatticeEsq.m \
schurNSPAlattice_slb.m \
schurNSPAlattice_slb_constraints_are_empty.m \
schurNSPAlattice_socp_mmse.m \
schurNSPAlattice_slb_exchange_constraints.m \
schurNSPAlattice_slb_set_empty_constraints.m \
schurNSPAlattice_slb_show_constraints.m \
schurNSPAlattice_slb_update_constraints.m \
schurNSPAlattice2tf.m schurNSAPlattice2tf.m schurNSAPlattice2Abcd.m \
tf2schurNSlattice.m local_max.m tf2pa.m print_polynomial.m \
Abcd2tf.m H2Asq.m H2T.m H2P.m qroots.m schurNSlatticeFilter.m crossWelch.m \
schurNSscale.oct schurdecomp.oct schurexpand.oct complex_zhong_inverse.oct \
schurNSlattice2Abcd.oct Abcd2H.oct qzsolve.oct 

schurNSPAlattice_socp_slb_bandpass_hilbert_test.diary : \
tarczynski_parallel_allpass_bandpass_hilbert_test.diary

