schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_FIGURES=\
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_initial \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_mmse \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_pcls \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_pcls_pass

schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_COEFS = \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_phi_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_B_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_Qp_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1k0_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1epsilon0_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2k0_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2epsilon0_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1kmmse_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2kmmse_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1k_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1epsilon_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A1p_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2k_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2epsilon_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_A2p_coef.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_spec.m \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test.mat

schurOneMPAlattice_socp_slb_lowpass_to_multiband_test_FILES = \
schurOneMPAlattice_socp_slb_lowpass_to_multiband_test.m \
test_common.m print_polynomial.m \
schurOneMPAlattice_slb.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_socp_mmse.m \
schurOneMPAlattice_slb_exchange_constraints.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_show_constraints.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMPAlattice_socp_slb_lowpass_plot.m \
schurOneMPAlatticeEsq.m \
schurOneMPAlatticeAsq.m \
schurOneMPAlatticeT.m \
schurOneMPAlatticeP.m \
schurOneMPAlattice2tf.m \
schurOneMAPlattice2tf.m \
schurOneMAPlattice2Abcd.m \
tf2schurOneMlattice.m \
schurOneMlatticeRetimedNoiseGain.m \
schurOneMlatticeFilter.m \
schurOneMscale.m \
H2Asq.m H2T.m H2P.m phi2p.m tfp2g.m tf2x.m zp2x.m x2tf.m tf2pa.m qroots.m \
local_max.m \
complex_zhong_inverse.oct spectralfactor.oct qzsolve.oct Abcd2H.oct \
schurdecomp.oct schurexpand.oct schurOneMlattice2Abcd.oct \
schurOneMAPlattice2H.oct schurOneMlattice2H.oct 
