schurOneMlattice_piqp_slb_hilbert_R2_test_FIGURES = \
schurOneMlattice_piqp_slb_hilbert_R2_test_initial_response \
schurOneMlattice_piqp_slb_hilbert_R2_test_mmse_response \
schurOneMlattice_piqp_slb_hilbert_R2_test_mmse_pz \
schurOneMlattice_piqp_slb_hilbert_R2_test_pcls_response \
schurOneMlattice_piqp_slb_hilbert_R2_test_pcls_pz

schurOneMlattice_piqp_slb_hilbert_R2_test_COEFS = \
schurOneMlattice_piqp_slb_hilbert_R2_test_k2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test_epsilon2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test_p2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test_c2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test_n2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test_d2_coef.m \
schurOneMlattice_piqp_slb_hilbert_R2_test.mat \
schurOneMlattice_piqp_slb_hilbert_R2_test_spec.m

schurOneMlattice_piqp_slb_hilbert_R2_test_FILES = \
schurOneMlattice_piqp_slb_hilbert_R2_test.m test_common.m \
schurOneMlatticeAsq.m schurOneMlatticeT.m schurOneMlatticeP.m \
schurOneMlatticeEsq.m \
schurOneMlattice_piqp_mmse.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_sqp_slb_hilbert_plot.m \
schurOneMlattice2tf.m \
schurOneMscale.m tf2schurOneMlattice.m \
local_max.m print_polynomial.m H2Asq.m H2T.m H2P.m \
spectralfactor.oct schurdecomp.oct schurexpand.oct qroots.oct Abcd2tf.oct \
complex_zhong_inverse.oct schurOneMlattice2H.oct schurOneMlattice2Abcd.oct

schurOneMlattice_piqp_slb_hilbert_R2_test.diary : \
tarczynski_hilbert_R2_test.diary
