schurOneMlattice_socp_slb_hilbert_test_FIGURES = \
schurOneMlattice_socp_slb_hilbert_test_mmse_k1c1 \
schurOneMlattice_socp_slb_hilbert_test_mmse_k1c1pz \
schurOneMlattice_socp_slb_hilbert_test_pcls_k2c2 \
schurOneMlattice_socp_slb_hilbert_test_pcls_k2c2pz \

schurOneMlattice_socp_slb_hilbert_test_COEFS = \
schurOneMlattice_socp_slb_hilbert_test_k2_coef.m \
schurOneMlattice_socp_slb_hilbert_test_epsilon2_coef.m \
schurOneMlattice_socp_slb_hilbert_test_p2_coef.m \
schurOneMlattice_socp_slb_hilbert_test_c2_coef.m \
schurOneMlattice_socp_slb_hilbert_test_n2_coef.m \
schurOneMlattice_socp_slb_hilbert_test_d2_coef.m \
schurOneMlattice_socp_slb_hilbert_test.mat \
schurOneMlattice_socp_slb_hilbert_test_spec.m

schurOneMlattice_socp_slb_hilbert_test_FILES = \
schurOneMlattice_socp_slb_hilbert_test.m test_common.m \
schurOneMlatticeAsq.m schurOneMlatticeT.m schurOneMlatticeP.m \
schurOneMlatticeEsq.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_sqp_slb_hilbert_plot.m \
schurOneMscale.m tf2schurOneMlattice.m \
schurOneMlattice2tf.m local_max.m print_polynomial.m Abcd2tf.m \
H2Asq.m H2T.m H2P.m spectralfactor.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2H.oct schurOneMlattice2Abcd.oct

schurOneMlattice_socp_slb_hilbert_test.diary : \
tarczynski_hilbert_test.diary
