schurOneMlattice_socp_slb_lowpass_differentiator_test_FIGURES = \
schurOneMlattice_socp_slb_lowpass_differentiator_test_response \
schurOneMlattice_socp_slb_lowpass_differentiator_test_simulated_error_response \
schurOneMlattice_socp_slb_lowpass_differentiator_test_error_response \
schurOneMlattice_socp_slb_lowpass_differentiator_test_correction_response \
schurOneMlattice_socp_slb_lowpass_differentiator_test_pz

schurOneMlattice_socp_slb_lowpass_differentiator_test_COEFS = \
schurOneMlattice_socp_slb_lowpass_differentiator_test.mat \
schurOneMlattice_socp_slb_lowpass_differentiator_test_spec.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_k2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_epsilon2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_p2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_c2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_N2_coef.m \
schurOneMlattice_socp_slb_lowpass_differentiator_test_D2_coef.m

schurOneMlattice_socp_slb_lowpass_differentiator_test_FILES = \
schurOneMlattice_socp_slb_lowpass_differentiator_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
schurOneMlatticeFilter.m \
local_max.m tf2pa.m x2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
print_polynomial.m print_pole_zero.m p2n60.m crossWelch.m \
schurOneMlattice2Abcd.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2H.oct qroots.oct Abcd2tf.oct

schurOneMlattice_socp_slb_lowpass_differentiator_test.diary : \
tarczynski_lowpass_differentiator_test.diary
