schurOneMlattice_socp_slb_lowpass_R2_alternate_test_FIGURES = \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_initial_response \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_pcls_response \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_pcls_pz

schurOneMlattice_socp_slb_lowpass_R2_alternate_test_COEFS = \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_k2_coef.m \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_epsilon2_coef.m \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_p2_coef.m \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_c2_coef.m \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_N2_coef.m \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test_D2_coef.m

schurOneMlattice_socp_slb_lowpass_R2_alternate_test_FILES = \
schurOneMlattice_socp_slb_lowpass_R2_alternate_test.m test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeP.m \
schurOneMlatticeT.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_socp_slb_lowpass_plot.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
local_max.m H2Asq.m H2T.m print_polynomial.m WISEJ.m tf2Abcd.m delayz.m \
qroots.oct schurdecomp.oct schurexpand.oct complex_zhong_inverse.oct \
schurOneMlattice2Abcd.oct schurOneMlattice2H.oct Abcd2tf.oct qroots.oct
