sdp_relaxation_directFIRhilbert_12_nbits_test_FIGURES = \
sdp_relaxation_directFIRhilbert_12_nbits_test_amplitude

sdp_relaxation_directFIRhilbert_12_nbits_test_COEFS = \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_allocsd_digits.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_coef.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_sd_coef.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_Ito_coef.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_sdp_coef.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_hM1_min_coef.m \
sdp_relaxation_directFIRhilbert_12_nbits_test_cost.tab \
sdp_relaxation_directFIRhilbert_12_nbits_test_spec.m \
sdp_relaxation_directFIRhilbert_12_nbits_test.mat

sdp_relaxation_directFIRhilbert_12_nbits_test_FILES = \
sdp_relaxation_directFIRhilbert_12_nbits_test.m \
test_common.m \
directFIRhilbert_sdp_mmsePW.m \
directFIRhilbert_socp_mmsePW.m \
directFIRhilbert_allocsd_Ito.m \
directFIRhilbert_slb.m \
directFIRhilbert_slb_constraints_are_empty.m \
directFIRhilbert_slb_exchange_constraints.m \
directFIRhilbert_slb_set_empty_constraints.m \
directFIRhilbert_slb_show_constraints.m \
directFIRhilbert_slb_update_constraints.m \
directFIRhilbertEsqPW.m \
directFIRhilbertA.m \
print_polynomial.m \
local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct 
