sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_FIGURES = \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_response

sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_COEFS = \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_hM1_sd_Ito_coef.m \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_hM1_sd_sdp_coef.m \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_cost.tab \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test.spec \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test.mat

sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test_FILES = \
sdp_relaxation_directFIRsymmetric_bandpass_12_nbits_test.m \
test_common.m \
sdp_relaxation_directFIRsymmetric_mmsePW.m \
directFIRsymmetric_socp_mmsePW.m \
directFIRsymmetric_allocsd_Ito.m \
directFIRsymmetric_slb.m \
directFIRsymmetric_slb_constraints_are_empty.m \
directFIRsymmetric_slb_exchange_constraints.m \
directFIRsymmetric_slb_set_empty_constraints.m \
directFIRsymmetric_slb_show_constraints.m \
directFIRsymmetric_slb_update_constraints.m \
directFIRsymmetricEsqPW.m \
directFIRsymmetricA.m \
print_polynomial.m \
local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct 
