selesnickFIRsymmetric_lowpass_test_FIGURES = \
selesnickFIRsymmetric_lowpass_test_hMa_response \
selesnickFIRsymmetric_lowpass_test_hMa_dual \
selesnickFIRsymmetric_lowpass_test_hMa_zeros \
selesnickFIRsymmetric_lowpass_test_hMb_response \
selesnickFIRsymmetric_lowpass_test_hMb_dual \
selesnickFIRsymmetric_lowpass_test_hMb_zeros \
selesnickFIRsymmetric_lowpass_test_hMc_response \
selesnickFIRsymmetric_lowpass_test_hMc_dual \
selesnickFIRsymmetric_lowpass_test_hMc_zeros \
selesnickFIRsymmetric_lowpass_test_hMd_response \
selesnickFIRsymmetric_lowpass_test_hMd_dual \
selesnickFIRsymmetric_lowpass_test_hMd_zeros

selesnickFIRsymmetric_lowpass_test_COEFS = \
selesnickFIRsymmetric_lowpass_test.mat \
selesnickFIRsymmetric_lowpass_test_hMa_spec.m \
selesnickFIRsymmetric_lowpass_test_hMa_coef.m \
selesnickFIRsymmetric_lowpass_test_hMb_spec.m \
selesnickFIRsymmetric_lowpass_test_hMb_coef.m \
selesnickFIRsymmetric_lowpass_test_hMc_spec.m \
selesnickFIRsymmetric_lowpass_test_hMc_coef.m \
selesnickFIRsymmetric_lowpass_test_hMd_spec.m \
selesnickFIRsymmetric_lowpass_test_hMd_coef.m

selesnickFIRsymmetric_lowpass_test_FILES = \
selesnickFIRsymmetric_lowpass_test.m test_common.m \
selesnickFIRsymmetric_lowpass.m lagrange_interp.m print_polynomial.m \
local_max.m local_peak.m xfr2tf.m directFIRsymmetricA.m qroots.m \
qzsolve.oct
