selesnickFIRsymmetric_flat_lowpass_test_FIGURES = \
selesnickFIRsymmetric_flat_lowpass_test_response \
selesnickFIRsymmetric_flat_lowpass_test_dual

selesnickFIRsymmetric_flat_lowpass_test_COEFS = \
selesnickFIRsymmetric_flat_lowpass_test.mat \
selesnickFIRsymmetric_flat_lowpass_test_spec.m \
selesnickFIRsymmetric_flat_lowpass_test_hM_coef.m \
selesnickFIRsymmetric_flat_lowpass_test_hA_coef.m

selesnickFIRsymmetric_flat_lowpass_test_FILES = \
selesnickFIRsymmetric_flat_lowpass_test.m test_common.m print_polynomial.m \
selesnickFIRsymmetric_flat_lowpass.m local_max.m lagrange_interp.m \
xfr2tf.m directFIRsymmetricA.m
