selesnickFIRantisymmetric_linear_differentiator_test_FIGURES = \
selesnickFIRantisymmetric_linear_differentiator_test_N30_response \
selesnickFIRantisymmetric_linear_differentiator_test_N31_response

selesnickFIRantisymmetric_linear_differentiator_test_COEFS = \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K00_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K04_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K08_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K12_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K16_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K20_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN30K24_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K01_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K05_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K09_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K13_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K17_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K21_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_hN31K25_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_cL10K0_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_cL10K1_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_cL10K2_coef.m \
selesnickFIRantisymmetric_linear_differentiator_test_cL10K3_coef.m

selesnickFIRantisymmetric_linear_differentiator_test_FILES = \
selesnickFIRantisymmetric_linear_differentiator_test.m test_common.m \
selesnickFIRantisymmetric_linear_differentiator.m print_polynomial.m
