socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FIGURES = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_initial_response \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_initial_pz \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_amplitude \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_amplitude \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_correction_dCsqdw_error \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_dAsqdw_error \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_dCsqdw_error \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass_amplitude_error \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass_correction_error \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass_delay \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pass_phase \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_pz \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_response \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_stop_amplitude \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_stop_correction_error

socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_COEFS = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c0_sd_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c0_sd_no_alloc_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c_allocsd_digits.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_c_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_D_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k0_sd_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k0_sd_no_alloc_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_kc_min_adders.tab \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_kc_min_digits.tab \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_k_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_epsilon_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_N_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_cost.tab

socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test_FILES = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
schurOneMlattice_allocsd_Lim.m \
schurOneMlattice_allocsd_Ito.m \
local_max.m x2tf.m print_polynomial.m Abcd2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
schurOneMlatticeFilter.m flt2SD.m x2nextra.m bin2SDul.m SDadders.m \
qroots.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMlattice2H.oct

socp_relaxation_schurOneMlattice_lowpass_differentiator_R2_12_nbits_test.diary : \
schurOneMlattice_socp_slb_lowpass_differentiator_R2_test.diary
