socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_FIGURES = \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_amplitude_response \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_pass_relative_amplitude_response

socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_COEFS = \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_cost.tab \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_h0_coef.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_coef.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_3sd_coef.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_sd_coef.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM0_allocsd_digits.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_coef.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_adders.m \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_hM_min_signed_digits.m

socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test_FILES= \
socp_relaxation_directFIRantisymmetric_lowpass_differentiator_12_nbits_test.m \
test_common.m \
directFIRantisymmetric_socp_mmse.m \
directFIRantisymmetric_allocsd_Lim.m \
directFIRantisymmetric_slb.m \
directFIRantisymmetric_slb_constraints_are_empty.m \
directFIRantisymmetric_slb_exchange_constraints.m \
directFIRantisymmetric_slb_set_empty_constraints.m \
directFIRantisymmetric_slb_show_constraints.m \
directFIRantisymmetric_slb_update_constraints.m \
directFIRantisymmetricEsq.m \
directFIRantisymmetricA.m \
selesnickFIRantisymmetric_linear_differentiator.m \
print_polynomial.m \
local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct

