socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_FIGURES = \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_amplitude \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_pass_phase \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_pass_delay

socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_COEFS = \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test.mat \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_spec.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_kuv_min_cost.tab \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_u_allocsd_digits.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_v_allocsd_digits.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_k0_sd_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_epsilon0_sd_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_p0_sd_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_u0_sd_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_v0_sd_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_k_min_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_epsilon_min_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_p_min_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_u_min_coef.m \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_v_min_coef.m 


socp_relaxation_schurOneMAPlattice_frm_12_nbits_test_FILES = \
socp_relaxation_schurOneMAPlattice_frm_12_nbits_test.m \
test_common.m schurOneMAPlattice_frm_socp_mmse.m \
schurOneMAPlattice_frm_slb_set_empty_constraints.m \
schurOneMAPlattice_frm_slb_constraints_are_empty.m \
schurOneMAPlattice_frm_slb_exchange_constraints.m \
schurOneMAPlattice_frm_slb_update_constraints.m \
schurOneMAPlattice_frm_slb_show_constraints.m \
schurOneMAPlattice_frm_slb.m \
schurOneMAPlattice_frm_allocsd_Ito.m \
schurOneMAPlattice_frm_allocsd_Lim.m \
schurOneMAPlattice_frm.m \
schurOneMAPlattice_frmEsq.m schurOneMAPlattice_frmAsq.m \
schurOneMAPlattice_frmP.m schurOneMAPlattice_frmT.m  \
schurOneMAPlatticeT.m schurOneMAPlatticeP.m schurOneMAPlattice2Abcd.m \
bin2SDul.m Abcd2tf.m schurOneMscale.m H2Asq.m H2T.m H2P.m flt2SD.m \
x2nextra.m local_max.m print_polynomial.m SDadders.m \
schurOneMAPlattice2H.oct schurdecomp.oct schurexpand.oct \
bin2SD.oct bitflip.oct bin2SPT.oct schurOneMlattice2Abcd.oct \
schurOneMlattice2H.oct complex_zhong_inverse.oct

socp_relaxation_schurOneMAPlattice_frm_12_nbits_test.diary : \
schurOneMAPlattice_frm_socp_slb_test.diary
