socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_FIGURES = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_kc_min \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_kc_min_pz

socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_COEFS = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test.mat \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_spec.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_c_allocsd_digits.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_k0_sd_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_c0_sd_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_k_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_c_min_coef.m \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_kc_min_cost.tab

socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test_FILES = \
socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test.m \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMscale.m \
tf2schurOneMlattice.m \
schurOneMlattice2tf.m \
schurOneMlattice_allocsd_Lim.m \
schurOneMlattice_allocsd_Ito.m \
local_max.m x2tf.m print_polynomial.m Abcd2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
schurOneMlatticeFilter.m flt2SD.m x2nextra.m bin2SDul.m SDadders.m qroots.m \
qzsolve.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMlattice2H.oct

socp_relaxation_schurOneMlattice_lowpass_differentiator_12_nbits_test.diary : \
schurOneMlattice_socp_slb_lowpass_differentiator_test.diary
