socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_FIGURES = \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kc_min \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kc_min_pz

socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_COEFS = \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test.mat \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_spec.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_c_allocsd_digits.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kk_allocsd_digits.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_ck_allocsd_digits.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_k0_sd_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_c0_sd_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kk0_sd_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_ck0_sd_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_k_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_c_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kk_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_ck_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_N_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_D_min_coef.m \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_kc_min_cost.tab

socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test_FILES = \
socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test.m \
test_common.m \
schurOneMlatticePipelinedAsq.m \
schurOneMlatticePipelinedP.m \
schurOneMlatticePipelinedT.m \
schurOneMlatticePipelineddAsqdw.m \
schurOneMlatticePipelinedEsq.m \
schurOneMlatticePipelined_slb.m \
schurOneMlatticePipelined_slb_constraints_are_empty.m \
schurOneMlatticePipelined_socp_mmse.m \
schurOneMlatticePipelined_slb_exchange_constraints.m \
schurOneMlatticePipelined_slb_set_empty_constraints.m \
schurOneMlatticePipelined_slb_show_constraints.m \
schurOneMlatticePipelined_slb_update_constraints.m \
schurOneMlatticePipelined_allocsd_Lim.m \
schurOneMlatticePipelined_allocsd_Ito.m \
schurOneMlatticePipelined2Abcd.m \
schurOneMscale.m tf2schurOneMlattice.m local_max.m x2tf.m print_polynomial.m \
H2Asq.m H2T.m H2P.m H2dAsqdw.m flt2SD.m x2nextra.m bin2SDul.m SDadders.m \
qroots.m \
qzsolve.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
Abcd2H.oct Abcd2tf.oct

socp_relaxation_schurOneMlatticePipelined_lowpass_differentiator_12_nbits_test.diary : \
schurOneMlatticePipelined_socp_slb_lowpass_differentiator_test.diary
