socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_FIGURES = \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_amplitude \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_phase \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_delay

socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_COEFS = \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_allocsd_digits.m \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_sd_coef.m \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_Ito_sd_coef.m \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_min_coef.m \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_cost.tab \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_h_min_adders.tab

socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test_FILES = \
socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test.m \
test_common.m \
directFIRnonsymmetric_socp_mmse.m \
directFIRnonsymmetric_allocsd_Ito.m \
directFIRnonsymmetric_slb.m \
directFIRnonsymmetric_slb_constraints_are_empty.m \
directFIRnonsymmetric_slb_exchange_constraints.m \
directFIRnonsymmetric_slb_set_empty_constraints.m \
directFIRnonsymmetric_slb_show_constraints.m \
directFIRnonsymmetric_slb_update_constraints.m \
directFIRnonsymmetricEsq.m \
directFIRnonsymmetricAsq.m \
directFIRnonsymmetricP.m \
directFIRnonsymmetricT.m \
print_polynomial.m \
local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct 

socp_relaxation_directFIRnonsymmetric_bandpass_hilbert_13_nbits_test.diary: \
directFIRnonsymmetric_socp_slb_bandpass_hilbert_test.diary
