socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_FIGURES = \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_initial_response \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_initial_sd_response \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_response_error \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_pass_relative_error \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_D1k_min_pz \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_D2k_min_pz \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_k_min_pz

socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_COEFS = \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A1k_allocsd_digits.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A2k_allocsd_digits.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A1k0_sd_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A2k0_sd_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A1k_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_A2k_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_D1k_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_D2k_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_N_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_D_min_coef.m \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_cost.tab

socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test_FILES = \
socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test.m \
test_common.m \
schurOneMPAlatticeAsq.m \
schurOneMPAlatticeT.m \
schurOneMPAlatticeP.m \
schurOneMPAlatticedAsqdw.m \
schurOneMPAlatticeEsq.m \
schurOneMPAlattice_slb.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_socp_mmse.m \
schurOneMPAlattice_slb_exchange_constraints.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_show_constraints.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMscale.m \
schurOneMPAlattice2tf.m \
schurOneMAPlattice2tf.m \
schurOneMAPlattice2Abcd.m \
schurOneMPAlattice_allocsd_Lim.m \
schurOneMPAlattice_allocsd_Ito.m \
local_max.m x2tf.m print_polynomial.m Abcd2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
flt2SD.m x2nextra.m bin2SDul.m SDadders.m delayz.m \
qroots.oct bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMAPlattice2H.oct

socp_relaxation_schurOneMPAlattice_lowpass_differentiator_alternate_12_nbits_test.diary : \
schurOneMPAlattice_socp_slb_lowpass_differentiator_alternate_test.diary
