socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_FIGURES = \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_kmin \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_pz

socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_COEFS = \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test.mat \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_spec.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A1k_allocsd_digits.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A2k_allocsd_digits.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A1k0_sd_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A2k0_sd_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A1k_min_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_A2k_min_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_N0_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_D0_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_N_min_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_D_min_coef.m \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_kmin_digits.tab \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_kmin_adders.tab \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_kmin_cost.tab

socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test_FILES = \
socp_relaxation_schurOneMPAlattice_elliptic_lowpass_16_nbits_test.m test_common.m \
schurOneMPAlattice_allocsd_Lim.m \
schurOneMPAlattice_allocsd_Ito.m \
schurOneMPAlatticeAsq.m schurOneMPAlatticeT.m \
schurOneMPAlatticeP.m schurOneMPAlatticedAsqdw.m schurOneMPAlatticeEsq.m \
schurOneMPAlattice_slb.m schurOneMPAlattice_socp_mmse.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMPAlattice_slb_exchange_constraints.m \
schurOneMPAlattice_slb_show_constraints.m \
schurOneMPAlattice2tf.m schurOneMAPlattice2tf.m schurOneMAPlattice2Abcd.m \
local_max.m print_polynomial.m flt2SD.m bin2SDul.m x2nextra.m \
SDadders.m Abcd2tf.m H2Asq.m H2T.m H2P.m H2dAsqdw.m \
tf2pa.m tf2schurOneMlattice.m schurOneMscale.m spectralfactor.m \
bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMAPlattice2H.oct \
qroots.oct 
