socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_FIGURES = \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_delay \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_pass \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_phase \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_stop

socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_COEFS = \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test.mat \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_spec.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_c_allocsd_digits.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_k0_sd_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_c0_sd_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_k0_sd_Ito_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_c0_sd_Ito_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_kc_sd_min_digits.tab \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_kc_sd_min_adders.tab \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_k_sd_min_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_c_sd_min_coef.m \
socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_cost.tab

socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test_FILES = \
test_common.m \
schurOneMlatticeAsq.m \
schurOneMlatticeT.m \
schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_allocsd_Ito.m \
schurOneMlattice_allocsd_Lim.m \
schurOneMscale.m schurOneMlattice2tf.m \
schurOneMlatticeFilter.m tf2schurOneMlattice.m local_max.m print_polynomial.m \
x2nextra.m H2Asq.m H2T.m H2P.m H2dAsqdw.m flt2SD.m bin2SDul.m SDadders.m \
schurdecomp.oct schurexpand.oct schurOneMlattice2H.oct Abcd2tf.oct \
schurOneMlattice2Abcd.oct bin2SPT.oct bin2SD.oct complex_zhong_inverse.oct

socp_relaxation_schurOneMlattice_bandpass_hilbert_R2_13_nbits_test.diary : \
schurOneMlattice_socp_slb_bandpass_hilbert_R2_test.diary
