socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_FIGURES = \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_delay \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_pass \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_stop

socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_COEFS = \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test.mat \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_spec.m \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_k_allocsd_digits.m \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_c_allocsd_digits.m \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_k_min_coef.m \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_c_min_coef.m \
socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_cost.tab

socp_relaxation_schurOneMlattice_bandpass_10_nbits_test_FILES = \
schurOneMlattice_bandpass_10_nbits_common.m test_common.m \
schurOneMlatticeAsq.m schurOneMlatticeT.m schurOneMlatticeP.m \
schurOneMlatticedAsqdw.m \
schurOneMlatticeEsq.m \
schurOneMlattice_socp_mmse.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMlattice_allocsd_Ito.m \
schurOneMlattice_allocsd_Lim.m \
schurOneMscale.m schurOneMlattice2tf.m \
schurOneMlatticeFilter.m tf2schurOneMlattice.m local_max.m print_polynomial.m \
x2nextra.m H2Asq.m H2T.m H2P.m flt2SD.m bin2SDul.m SDadders.m \
schurdecomp.oct schurexpand.oct complex_zhong_inverse.oct Abcd2tf.oct \
schurOneMlattice2H.oct schurOneMlattice2Abcd.oct bin2SPT.oct bin2SD.oct \

socp_relaxation_schurOneMlattice_bandpass_10_nbits_test.diary : \
schurOneMlattice_sqp_slb_bandpass_test.diary
