state_variable_unequal_state_length_test_FIGURES=

state_variable_unequal_state_length_test_COEFS = \
state_variable_unequal_state_length_test_NN_1_pow2p.m \
state_variable_unequal_state_length_test_NN_1_pow2palt.m \
state_variable_unequal_state_length_test_NN_1_results.tab \
state_variable_unequal_state_length_test_NN_1_roundNBids.m \
state_variable_unequal_state_length_test_NN_1_roundNBis.m \
state_variable_unequal_state_length_test_NN_2_pow2p.m \
state_variable_unequal_state_length_test_NN_2_pow2palt.m \
state_variable_unequal_state_length_test_NN_2_results.tab \
state_variable_unequal_state_length_test_NN_2_roundNBids.m \
state_variable_unequal_state_length_test_NN_2_roundNBis.m \
state_variable_unequal_state_length_test_NN_3_pow2p.m \
state_variable_unequal_state_length_test_NN_3_pow2palt.m \
state_variable_unequal_state_length_test_NN_3_results.tab \
state_variable_unequal_state_length_test_NN_3_roundNBids.m \
state_variable_unequal_state_length_test_NN_3_roundNBis.m \
state_variable_unequal_state_length_test_NN_4_pow2p.m \
state_variable_unequal_state_length_test_NN_4_pow2palt.m \
state_variable_unequal_state_length_test_NN_4_results.tab \
state_variable_unequal_state_length_test_NN_4_roundNBids.m \
state_variable_unequal_state_length_test_NN_4_roundNBis.m \
state_variable_unequal_state_length_test_NN_5_pow2p.m \
state_variable_unequal_state_length_test_NN_5_pow2palt.m \
state_variable_unequal_state_length_test_NN_5_results.tab \
state_variable_unequal_state_length_test_NN_5_roundNBids.m \
state_variable_unequal_state_length_test_NN_5_roundNBis.m \
state_variable_unequal_state_length_test_NN_6_pow2p.m \
state_variable_unequal_state_length_test_NN_6_pow2palt.m \
state_variable_unequal_state_length_test_NN_6_results.tab \
state_variable_unequal_state_length_test_NN_6_roundNBids.m \
state_variable_unequal_state_length_test_NN_6_roundNBis.m

state_variable_unequal_state_length_test_FILES = \
state_variable_unequal_state_length_test.m test_common.m \
tf2schurOneMlattice.m schurOneMscale.m KW.m p2n60.m svf.m tf2Abcd.m \
print_polynomial.m \
schurOneMlatticeFilter.oct schurOneMlattice2Abcd.oct \
schurexpand.oct schurdecomp.oct reprand.oct qroots.oct complex_zhong_inverse.oct
