tarczynski_bandpass_differentiator_test_FIGURES = \
tarczynski_bandpass_differentiator_test_response \
tarczynski_bandpass_differentiator_test_error_response \
tarczynski_bandpass_differentiator_test_pz

tarczynski_bandpass_differentiator_test_COEFS = \
tarczynski_bandpass_differentiator_test_D0_coef.m \
tarczynski_bandpass_differentiator_test_N0_coef.m \

tarczynski_bandpass_differentiator_test_FILES = \
tarczynski_bandpass_differentiator_test.m test_common.m delayz.m \
WISEJ.m tf2Abcd.m print_polynomial.m print_pole_zero.m \
qroots.oct
