tarczynski_allpass2ndOrderCascade_test_FIGURES = \
tarczynski_allpass2ndOrderCascade_test_ABphase \
tarczynski_allpass2ndOrderCascade_test_Apz \
tarczynski_allpass2ndOrderCascade_test_Bpz \
tarczynski_allpass2ndOrderCascade_test_passband_response \
tarczynski_allpass2ndOrderCascade_test_pass_stop_response \
tarczynski_allpass2ndOrderCascade_test_phase_error \
tarczynski_allpass2ndOrderCascade_test_pz \
tarczynski_allpass2ndOrderCascade_test_response \
tarczynski_allpass2ndOrderCascade_test_flat_delay_ABphase \
tarczynski_allpass2ndOrderCascade_test_flat_delay_Apz \
tarczynski_allpass2ndOrderCascade_test_flat_delay_Bpz \
tarczynski_allpass2ndOrderCascade_test_flat_delay_passband_response \
tarczynski_allpass2ndOrderCascade_test_flat_delay_pass_stop_response \
tarczynski_allpass2ndOrderCascade_test_flat_delay_phase_error \
tarczynski_allpass2ndOrderCascade_test_flat_delay_pz \
tarczynski_allpass2ndOrderCascade_test_flat_delay_response

tarczynski_allpass2ndOrderCascade_test_COEFS = \
tarczynski_allpass2ndOrderCascade_test_ab0_coef.m \
tarczynski_allpass2ndOrderCascade_test_Da0_coef.m \
tarczynski_allpass2ndOrderCascade_test_Db0_coef.m \
tarczynski_allpass2ndOrderCascade_test_spec.m \
tarczynski_allpass2ndOrderCascade_test_flat_delay_ab0_coef.m \
tarczynski_allpass2ndOrderCascade_test_flat_delay_Da0_coef.m \
tarczynski_allpass2ndOrderCascade_test_flat_delay_Db0_coef.m \
tarczynski_allpass2ndOrderCascade_test_flat_delay_spec.m \
tarczynski_allpass2ndOrderCascade_test.mat

tarczynski_allpass2ndOrderCascade_test_FILES = \
tarczynski_allpass2ndOrderCascade_test.m test_common.m delayz.m \
allpass2ndOrderCascade.m casc2tf.m print_polynomial.m qroots.m \
qzsolve.oct
