tarczynski_parallel_allpass_lowpass_differentiator_test_FIGURES = \
tarczynski_parallel_allpass_lowpass_differentiator_test_response \
tarczynski_parallel_allpass_lowpass_differentiator_test_response_error \
tarczynski_parallel_allpass_lowpass_differentiator_test_pz \
tarczynski_parallel_allpass_lowpass_differentiator_test_phase

tarczynski_parallel_allpass_lowpass_differentiator_test_COEFS = \
tarczynski_parallel_allpass_lowpass_differentiator_test_Da0_coef.m \
tarczynski_parallel_allpass_lowpass_differentiator_test_Db0_coef.m \
tarczynski_parallel_allpass_lowpass_differentiator_test.mat

tarczynski_parallel_allpass_lowpass_differentiator_test_FILES = \
tarczynski_parallel_allpass_lowpass_differentiator_test.m \
test_common.m WISEJ_PA.m delayz.m print_polynomial.m print_pole_zero.m
