tarczynski_lowpass_differentiator_alternate_test_FIGURES = \
tarczynski_lowpass_differentiator_alternate_test_response \
tarczynski_lowpass_differentiator_alternate_test_error_response \
tarczynski_lowpass_differentiator_alternate_test_pz

tarczynski_lowpass_differentiator_alternate_test_COEFS = \
tarczynski_lowpass_differentiator_alternate_test_D0_coef.m \
tarczynski_lowpass_differentiator_alternate_test_N0_coef.m \
tarczynski_lowpass_differentiator_alternate_test.mat

tarczynski_lowpass_differentiator_alternate_test_FILES = \
tarczynski_lowpass_differentiator_alternate_test.m test_common.m delayz.m \
WISEJ.m tf2Abcd.m print_polynomial.m print_pole_zero.m
