tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_FIGURES = \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_response \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_correction \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_error \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_phase \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_Da0_pz \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_Db0_pz \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_pz 

tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_COEFS = \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_Da0_coef.m \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_Db0_coef.m \

tarczynski_parallel_allpass_lowpass_differentiator_alternate_test_FILES = \
tarczynski_parallel_allpass_lowpass_differentiator_alternate_test.m \
test_common.m WISEJ_PA.m delayz.m print_polynomial.m print_pole_zero.m \
qroots.oct
