tarczynski_parallel_allpass_multiband_test_FIGURES = \
tarczynski_parallel_allpass_multiband_test_response \
tarczynski_parallel_allpass_multiband_test_response_passband \
tarczynski_parallel_allpass_multiband_test_pz \
tarczynski_parallel_allpass_multiband_test_phase

tarczynski_parallel_allpass_multiband_test_COEFS = \
tarczynski_parallel_allpass_multiband_test_Da0_coef.m \
tarczynski_parallel_allpass_multiband_test_Db0_coef.m \
tarczynski_parallel_allpass_multiband_test.mat

tarczynski_parallel_allpass_multiband_test_FILES = \
tarczynski_parallel_allpass_multiband_test.m \
test_common.m delayz.m print_polynomial.m WISEJ_PA.m \
qroots.oct
