tarczynski_polyphase_allpass_test_FIGURES = \
tarczynski_polyphase_allpass_test_response \
tarczynski_polyphase_allpass_test_response_passband \
tarczynski_polyphase_allpass_test_flat_delay_response \
tarczynski_polyphase_allpass_test_flat_delay_response_passband \
tarczynski_polyphase_allpass_test_flat_delay_phase

tarczynski_polyphase_allpass_test_COEFS = \
tarczynski_polyphase_allpass_test_Da0_coef.m \
tarczynski_polyphase_allpass_test_Db0_coef.m \
tarczynski_polyphase_allpass_test_flat_delay_Da0_coef.m \
tarczynski_polyphase_allpass_test_flat_delay_Db0_coef.m \

tarczynski_polyphase_allpass_test_FILES = tarczynski_polyphase_allpass_test.m \
test_common.m delayz.m print_polynomial.m print_pole_zero.m WISEJ_PA.m
