tarczynski_frm_parallel_allpass_test_FIGURES = \
tarczynski_frm_parallel_allpass_test_response \
tarczynski_frm_parallel_allpass_test_passband_response \
tarczynski_frm_parallel_allpass_test_masking_response \
tarczynski_frm_parallel_allpass_test_model_response

tarczynski_frm_parallel_allpass_test_COEFS = \
tarczynski_frm_parallel_allpass_test.spec \
tarczynski_frm_parallel_allpass_test.mat \
tarczynski_frm_parallel_allpass_test_r_coef.m \
tarczynski_frm_parallel_allpass_test_s_coef.m \
tarczynski_frm_parallel_allpass_test_aa_coef.m \
tarczynski_frm_parallel_allpass_test_ac_coef.m

tarczynski_frm_parallel_allpass_test_FILES = \
tarczynski_frm_parallel_allpass_test.m \
test_common.m print_polynomial.m print_pole_zero.m WISEJ_PA.m \
frm_lowpass_vectors.m
