vaidyanathanFIRsymmetric_lowpass_test_FIGURES = \
vaidyanathanFIRsymmetric_lowpass_test_response 

vaidyanathanFIRsymmetric_lowpass_test_COEFS = 

vaidyanathanFIRsymmetric_lowpass_test_FILES = \
vaidyanathanFIRsymmetric_lowpass_test.m test_common.m 
