allpass_filter_test_FIGURES= \
allpass_filter_test_AL7c_complex_ng \
allpass_filter_test_AL7c_complex_pgrad \
allpass_filter_test_AL7c_real_ng \
allpass_filter_test_AL7c_real_pgrad \
allpass_filter_test_AL7c_retimed_complex_ng \
allpass_filter_test_AL7c_retimed_complex_pgrad \
allpass_filter_test_AL7c_retimed_real_ng \
allpass_filter_test_AL7c_retimed_real_pgrad \
allpass_filter_test_dir1_ng \
allpass_filter_test_dir1_retimed_ng \
allpass_filter_test_dir1_retimed_pgrad \
allpass_filter_test_dir1_pgrad \
allpass_filter_test_dir2_complex_ng \
allpass_filter_test_dir2_complex_pgrad \
allpass_filter_test_dir2_real_ng \
allpass_filter_test_dir2_real_pgrad \
allpass_filter_test_dir2_retimed_complex_ng \
allpass_filter_test_dir2_retimed_complex_pgrad \
allpass_filter_test_dir2_retimed_real_ng \
allpass_filter_test_dir2_retimed_real_pgrad \
allpass_filter_test_GM1_ng \
allpass_filter_test_GM1_pgrad \
allpass_filter_test_GM2_complex_ng \
allpass_filter_test_GM2_complex_pgrad \
allpass_filter_test_GM2_real_ng \
allpass_filter_test_GM2_real_pgrad \
allpass_filter_test_GM2_retimed_complex_ng \
allpass_filter_test_GM2_retimed_complex_pgrad \
allpass_filter_test_GM2_retimed_real_ng \
allpass_filter_test_GM2_retimed_real_pgrad \
allpass_filter_test_IS_complex_ng \
allpass_filter_test_IS_complex_pgrad \
allpass_filter_test_IS_real_ng \
allpass_filter_test_IS_real_pgrad \
allpass_filter_test_IS_retimed_complex_ng \
allpass_filter_test_IS_retimed_complex_pgrad \
allpass_filter_test_IS_retimed_real_ng \
allpass_filter_test_IS_retimed_real_pgrad \
allpass_filter_test_LS1_ng \
allpass_filter_test_LS1_pgrad \
allpass_filter_test_LS2a_complex_ng \
allpass_filter_test_LS2a_complex_pgrad \
allpass_filter_test_LS2a_real_ng \
allpass_filter_test_LS2a_real_pgrad \
allpass_filter_test_MH2d_complex_ng \
allpass_filter_test_MH2d_complex_pgrad \
allpass_filter_test_MH2d_real_ng \
allpass_filter_test_MH2d_real_pgrad \
allpass_filter_test_MH2d_retimed_complex_ng \
allpass_filter_test_MH2d_retimed_complex_pgrad \
allpass_filter_test_MH2d_retimed_real_ng \
allpass_filter_test_MH2d_retimed_real_pgrad \
allpass_filter_test_MH3d_complex_ng \
allpass_filter_test_MH3d_complex_pgrad \
allpass_filter_test_MH3d_real_ng \
allpass_filter_test_MH3d_real_pgrad

allpass_filter_test_FILES = \
allpass_filter_test.m \
test_common.m \
Abcd2tf.m \
H2Asq.m \
H2T.m \
H2P.m \
svf.m \
KW.m \
Abcd2H.oct \
Abcd2ng.m \
allpass_AL7c.m \
allpass_AL7c_coef2Abcd.m \
allpass_AL7c_coef2ng.m \
allpass_AL7c_pole2coef.m \
allpass_AL7c_retimed.m \
allpass_AL7c_retimed_coef2Abcd.m \
allpass_AL7c_retimed_coef2ng.m \
allpass_AL7c_retimed_pole2coef.m \
allpass_GM1.m \
allpass_GM1_coef2Abcd.m \
allpass_GM1_coef2ng.m \
allpass_GM1_pole2coef.m \
allpass_GM2.m \
allpass_GM2_coef2Abcd.m \
allpass_GM2_coef2ng.m \
allpass_GM2_pole2coef.m \
allpass_GM2_retimed.m \
allpass_GM2_retimed_coef2Abcd.m \
allpass_GM2_retimed_coef2ng.m \
allpass_GM2_retimed_pole2coef.m \
allpass_IS.m \
allpass_IS_coef2Abcd.m \
allpass_IS_coef2ng.m \
allpass_IS_pole2coef.m \
allpass_IS_retimed.m \
allpass_IS_retimed_coef2Abcd.m \
allpass_IS_retimed_coef2ng.m \
allpass_IS_retimed_pole2coef.m \
allpass_LS1.m \
allpass_LS1_coef2Abcd.m \
allpass_LS1_coef2ng.m \
allpass_LS1_pole2coef.m \
allpass_LS2a.m \
allpass_LS2a_coef2Abcd.m \
allpass_LS2a_coef2ng.m \
allpass_LS2a_pole2coef.m \
allpass_MH2d.m \
allpass_MH2d_coef2Abcd.m \
allpass_MH2d_coef2ng.m \
allpass_MH2d_pole2coef.m \
allpass_MH2d_retimed.m \
allpass_MH2d_retimed_coef2Abcd.m \
allpass_MH2d_retimed_coef2ng.m \
allpass_MH2d_retimed_pole2coef.m \
allpass_MH2dt.m \
allpass_MH2dt_coef2Abcd.m \
allpass_MH2dt_coef2ng.m \
allpass_MH2dt_pole2coef.m \
allpass_MH3d.m \
allpass_MH3d_coef2Abcd.m \
allpass_MH3d_coef2ng.m \
allpass_MH3d_pole2coef.m \
allpass_MH3dt.m \
allpass_MH3dt_coef2Abcd.m \
allpass_MH3dt_coef2ng.m \
allpass_MH3dt_pole2coef.m \
allpass_MH3dtp.m \
allpass_MH3dtp_coef2Abcd.m \
allpass_MH3dtp_coef2ng.m \
allpass_MH3dtp_pole2coef.m \
allpass_dir1.m \
allpass_dir1_coef2Abcd.m \
allpass_dir1_coef2ng.m \
allpass_dir1_pole2coef.m \
allpass_dir1_retimed.m \
allpass_dir1_retimed_coef2Abcd.m \
allpass_dir1_retimed_coef2ng.m \
allpass_dir1_retimed_pole2coef.m \
allpass_dir2.m \
allpass_dir2_coef2Abcd.m \
allpass_dir2_coef2ng.m \
allpass_dir2_pole2coef.m \
allpass_dir2_retimed.m \
allpass_dir2_retimed_coef2Abcd.m \
allpass_dir2_retimed_coef2ng.m \
allpass_dir2_retimed_pole2coef.m 
