branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_FIGURES = \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_stop \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_pass \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_delay

branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_COEFS = \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test.mat \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test.spec \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_A1k0_sd_coef.m \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_A2k0_sd_coef.m \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_A1k_min_coef.m \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_A2k_min_coef.m \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_digits.tab \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_adders.tab \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_kmin_cost.tab

branch_bound_schurOneMPAlattice_bandpass_12_nbits_test_FILES = \
branch_bound_schurOneMPAlattice_bandpass_12_nbits_test.m test_common.m \
schurOneMPAlattice_allocsd_Lim.m \
schurOneMPAlattice_allocsd_Ito.m \
schurOneMPAlatticeAsq.m schurOneMPAlatticeT.m \
schurOneMPAlatticeP.m schurOneMPAlatticeEsq.m \
schurOneMPAlattice_slb.m schurOneMPAlattice_socp_mmse.m \
schurOneMPAlattice_slb_set_empty_constraints.m \
schurOneMPAlattice_slb_constraints_are_empty.m \
schurOneMPAlattice_slb_update_constraints.m \
schurOneMPAlattice_slb_exchange_constraints.m \
schurOneMPAlattice_slb_show_constraints.m \
schurOneMPAlattice2tf.m schurOneMAPlattice2tf.m schurOneMAPlattice2Abcd.m \
local_max.m tf2pa.m print_polynomial.m flt2SD.m bin2SDul.m x2nextra.m \
SDadders.m Abcd2tf.m H2Asq.m H2T.m H2P.m tf2schurOneMlattice.m schurOneMscale.m \
bin2SD.oct bin2SPT.oct schurdecomp.oct schurexpand.oct \
complex_zhong_inverse.oct schurOneMlattice2Abcd.oct schurOneMAPlattice2H.oct \
qroots.m qzsolve.oct sedumi_test.diary
