branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_FIGURES = \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_resp \

branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_COEFS = \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_cost.tab \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_f_min_coef.m \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_k0_min_coef.m \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_k1_min_coef.m \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test.spec \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test.mat

branch_bound_johanssonOneMlattice_bandstop_16_nbits_test_FILES = \
branch_bound_johanssonOneMlattice_bandstop_16_nbits_test.m \
test_common.m johanssonOneMlatticeAzp.m johanssonOneMlatticeEsq.m \
tf2schurOneMlattice.m phi2p.m tfp2g.m tf2pa.m local_max.m print_polynomial.m \
flt2SD.m x2nextra.m bin2SDul.m SDadders.m qroots.m schurOneMAPlatticeP.m \
schurOneMscale.m schurOneMAPlattice2Abcd.m H2P.m \
bin2SD.oct bin2SPT.oct qzsolve.oct schurOneMlattice2Abcd.oct \
complex_zhong_inverse.oct schurOneMAPlattice2H.oct schurdecomp.oct \
schurexpand.oct spectralfactor.oct
