branch_bound_schurOneMlattice_bandpass_10_nbits_test_FIGURES = \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_delay \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_pass \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_stop

branch_bound_schurOneMlattice_bandpass_10_nbits_test_COEFS = \
branch_bound_schurOneMlattice_bandpass_10_nbits_test.mat \
branch_bound_schurOneMlattice_bandpass_10_nbits_test.spec \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_k_allocsd_digits_Ito.m \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_c_allocsd_digits_Ito.m \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_k_min_coef.m \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_c_min_coef.m \
branch_bound_schurOneMlattice_bandpass_10_nbits_test_cost.tab

branch_bound_schurOneMlattice_bandpass_10_nbits_test_FILES = \
branch_bound_schurOneMlattice_bandpass_10_nbits_test.m \
schurOneMlattice_bandpass_10_nbits_common.m test_common.m \
schurOneMlatticeAsq.m schurOneMlatticeT.m schurOneMlatticeP.m \
schurOneMlatticeEsq.m \
schurOneMlattice_slb.m \
schurOneMlattice_slb_constraints_are_empty.m \
schurOneMlattice_sqp_mmse.m \
schurOneMlattice_slb_exchange_constraints.m \
schurOneMlattice_slb_set_empty_constraints.m \
schurOneMlattice_slb_show_constraints.m \
schurOneMlattice_slb_update_constraints.m \
schurOneMscale.m \
schurOneMlattice2tf.m \
schurOneMlattice_allocsd_Ito.m \
schurOneMlatticeFilter.m \
tf2schurOneMlattice.m \
local_max.m x2tf.m tf2pa.m print_polynomial.m Abcd2tf.m x2nextra.m sqp_bfgs.m \
armijo_kim.m updateWbfgs.m invSVD.m H2Asq.m H2T.m H2P.m flt2SD.m bin2SDul.m \
SDadders.m schurdecomp.oct schurexpand.oct complex_zhong_inverse.oct \
schurOneMlattice2H.oct schurOneMlattice2Abcd.oct bin2SPT.oct bin2SD.oct
