decimator_R2_interpolated_test_FIGURES = \
decimator_R2_interpolated_test_fir_antialiasing \
decimator_R2_interpolated_test_response \
decimator_R2_interpolated_test_passband_response \
decimator_R2_interpolated_test_remez_comparison_interpolated_IIR \
decimator_R2_interpolated_test_remez_comparison_interpolated_FIR \
decimator_R2_interpolated_test_remez_comparison_direct_FIR_multipliers \
decimator_R2_interpolated_test_remez_comparison_direct_FIR 

decimator_R2_interpolated_test_COEFS = \
decimator_R2_interpolated_test.mat \
decimator_R2_interpolated_test.spec \
decimator_R2_interpolated_test_xi_coef.m \
decimator_R2_interpolated_test_d1_coef.m \
decimator_R2_interpolated_test_N1_coef.m \
decimator_R2_interpolated_test_D1_coef.m \
decimator_R2_interpolated_test_b_coef.m \
decimator_R2_interpolated_test_baa_coef.m \
decimator_R2_interpolated_test_beq_coef.m \
decimator_R2_interpolated_test_bb_coef.m \
decimator_R2_interpolated_test_bbb_coef.m \
decimator_R2_interpolated_test_actual_stopband.tab \
decimator_R2_interpolated_test_actual_passband.tab \
decimator_R2_interpolated_test_nominal_delay.tab \
decimator_R2_interpolated_test_distinct_multipliers.tab \
decimator_R2_interpolated_test_b_scale.tab \
decimator_R2_interpolated_test_bbeq_delay.tab \
decimator_R2_interpolated_test_bbeq_distinct_multipliers.tab \
decimator_R2_interpolated_test_fir_delay.tab \
decimator_R2_interpolated_test_fir_distinct_multipliers.tab 

decimator_R2_interpolated_test_FILES = \
decimator_R2_interpolated_test.m test_common.m \
print_polynomial.m print_pole_zero.m armijo_kim.m fixResultNaN.m \
iirA.m iirE.m iirP.m iirT.m invSVD.m local_max.m iir_sqp_mmse.m \
iir_slb.m iir_slb_exchange_constraints.m iir_slb_show_constraints.m \
iir_slb_constraints_are_empty.m iir_slb_set_empty_constraints.m \
iir_slb_update_constraints.m showResponseBands.m showResponse.m \
showResponsePassBands.m showZPplot.m sqp_bfgs.m updateWchol.m updateWbfgs.m \
xConstraints.m x2tf.m xInitHd.m
