directFIRnonsymmetric_kyp_lowpass_test_FIGURES = \
directFIRnonsymmetric_kyp_lowpass_test_response \
directFIRnonsymmetric_kyp_lowpass_test_passband

directFIRnonsymmetric_kyp_lowpass_test_COEFS = \
directFIRnonsymmetric_kyp_lowpass_test.mat \
directFIRnonsymmetric_kyp_lowpass_test.spec \
directFIRnonsymmetric_kyp_lowpass_test_h_coef.m \
directFIRnonsymmetric_kyp_lowpass_test_max_abs_H.tab \
directFIRnonsymmetric_kyp_lowpass_test_max_passband_error.tab \
directFIRnonsymmetric_kyp_lowpass_test_max_stopband_error.tab

directFIRnonsymmetric_kyp_lowpass_test_FILES = \
directFIRnonsymmetric_kyp_lowpass_test.m test_common.m print_polynomial.m
