directFIRsymmetric_sdp_lowpass_test_FIGURES = \
directFIRsymmetric_sdp_lowpass_test_hM200_response \
directFIRsymmetric_sdp_lowpass_test_hM201_response 

directFIRsymmetric_sdp_lowpass_test_COEFS = \
directFIRsymmetric_sdp_lowpass_test_hM200.mat \
directFIRsymmetric_sdp_lowpass_test_hM200.spec \
directFIRsymmetric_sdp_lowpass_test_hM200_coef.m \
directFIRsymmetric_sdp_lowpass_test_hM201.mat \
directFIRsymmetric_sdp_lowpass_test_hM201.spec \
directFIRsymmetric_sdp_lowpass_test_hM201_coef.m 

directFIRsymmetric_sdp_lowpass_test_FILES = \
directFIRsymmetric_sdp_lowpass_test.m test_common.m \
print_polynomial.m directFIRsymmetricA.m directFIRsymmetric_sdp_basis.m \
directFIRsymmetricEsqPW.m
