directFIRnonsymmetric_kyp_bandpass_test_FIGURES = \
directFIRnonsymmetric_kyp_bandpass_test_response \
directFIRnonsymmetric_kyp_bandpass_test_passband

directFIRnonsymmetric_kyp_bandpass_test_COEFS = \
directFIRnonsymmetric_kyp_bandpass_test.mat \
directFIRnonsymmetric_kyp_bandpass_test.spec \
directFIRnonsymmetric_kyp_bandpass_test_h_coef.m 

directFIRnonsymmetric_kyp_bandpass_test_FILES = \
directFIRnonsymmetric_kyp_bandpass_test.m test_common.m print_polynomial.m
