directFIRsymmetric_socp_slb_bandpass_test_FIGURES = \
directFIRsymmetric_socp_slb_bandpass_test_response \
directFIRsymmetric_socp_slb_bandpass_test_dual_response

directFIRsymmetric_socp_slb_bandpass_test_COEFS = \
directFIRsymmetric_socp_slb_bandpass_test.mat \
directFIRsymmetric_socp_slb_bandpass_test.spec \
directFIRsymmetric_socp_slb_bandpass_test_hM1_coef.m 

directFIRsymmetric_socp_slb_bandpass_test_FILES = \
directFIRsymmetric_socp_slb_bandpass_test.m test_common.m \
directFIRsymmetric_slb.m \
directFIRsymmetric_slb_constraints_are_empty.m \
directFIRsymmetric_slb_exchange_constraints.m \
directFIRsymmetric_slb_set_empty_constraints.m \
directFIRsymmetric_slb_show_constraints.m \
directFIRsymmetric_slb_update_constraints.m \
directFIRsymmetric_socp_mmsePW.m \
directFIRsymmetricEsqPW.m \
directFIRsymmetricA.m \
local_max.m \
print_polynomial.m
