freq_transform_structure_test_FIGURES= \
freq_transform_structure_test_lowpass_response \
freq_transform_structure_test_bandpass_A_response \
freq_transform_structure_test_bandpass_B_response

freq_transform_structure_test_FILES = \
freq_transform_structure_test.m test_common.m print_polynomial.m \
WISEJ.m tfp2g.m tf2Abcd.m phi2p.m
