hofstetterFIRsymmetric_lowpass_test_FIGURES = \
hofstetterFIRsymmetric_lowpass_test_response \
hofstetterFIRsymmetric_lowpass_test_dual \
hofstetterFIRsymmetric_lowpass_test_zeros

hofstetterFIRsymmetric_lowpass_test_COEFS = \
hofstetterFIRsymmetric_lowpass_test.mat \
hofstetterFIRsymmetric_lowpass_test.spec \
hofstetterFIRsymmetric_lowpass_test_hM_coef.m

hofstetterFIRsymmetric_lowpass_test_FILES = \
hofstetterFIRsymmetric_lowpass_test.m test_common.m print_polynomial.m \
hofstetterFIRsymmetric.m local_max.m lagrange_interp.m \
xfr2tf.m directFIRsymmetricA.m
