% iir_socp_slb_test.m
% Copyright (C) 2017 Robert G. Jenssen

% Optimise a filter generated by the ellip function

test_common;

unlink("iir_socp_slb_test.diary");
unlink("iir_socp_slb_test.diary.tmp");
diary iir_socp_slb_test.diary.tmp

tic;

format compact

verbose=false;
tol=1e-8;
maxiter=2000;

% Lowpass filter specification. Frequencies are normalised to sample
% rate, and a non-zero Wt constrains peaks in the transition band.
fap=0.15;dBap=0.02;fas=0.1835;dBas=50;Wap=1;Wat=1.1*tol;Was=1;

% Initial filter
[b0,a0]=ellip(7,0.2,40,2*fap);
[x0,U,V,M,Q]=tf2x(b0,a0,tol);
R=1;
 
% Frequency points
n=1000;

% Coefficient constraints
[xl,xu]=xConstraints(U,V,M,Q);

% Amplitude constraints
wa=(0:(n-1))'*pi/n;
npass=ceil(n*fap/0.5)+1;
nstop=floor(n*fas/0.5)+1;
Ad=[ones(npass,1);zeros(n-npass,1)];
Adu=[ones(nstop-1,1);(10^(-dBas/20))*ones(n-nstop+1,1)];
Adl=[(10^(-dBap/20))*ones(npass,1);zeros(n-npass,1)];
Wa=[Wap*ones(npass,1);Wat*ones(nstop-npass-1,1);Was*ones(n-nstop+1,1)];

% Amplitude stop-band constraints
ws=[];Sd=[];Sdu=[];Sdl=[];Ws=[];

% Group delay constraints
wt=[];Td=[];Tdu=[];Tdl=[];Wt=[];

% Phase constraints
wp=[];Pd=[];Pdu=[];Pdl=[];Wp=[];

% SOCP PCLS
[d2,E,slb_iter,socp_iter,func_iter,feasible]= ...
  iir_slb(@iir_socp_mmse, ...
          x0,xu,xl,inf,U,V,M,Q,R, ...
          wa,Ad,Adu,Adl,Wa,ws,Sd,Sdu,Sdl,Ws, ...
          wt,Td,Tdu,Tdl,Wt,wp,Pd,Pdu,Pdl,Wp, ...
          maxiter,tol,verbose)
if feasible == 0 
  error("d2(pcls) infeasible");
endif

% Check constraints
A=iirA(wa,d2,U,V,M,Q,R);
vAl=local_max(Adl-A);
vAu=local_max(A-Adu);
wAS=unique([wa(vAl);wa(vAu); ...
            wa([1,npass-1,npass,npass+1,nstop-1,nstop,nstop+1,end])]);
AS=iirA(wAS,d2,U,V,M,Q,R);
printf("d2:fAS=[ ");printf("%f ",wAS'*0.5/pi);printf(" ] (fs==1)\n");
printf("d2:AS=[ ");printf("%f ",20*log10(AS'));printf(" ] (dB)\n");

% Compare with elliptic filter
[be,ae]=ellip(7,dBap,dBas,2*fap);
[xe,Ue,Ve,Me,Qe]=tf2x(be,ae,tol);

% Show results
nplot=1024
[h_e,wplot]=freqz(be,ae,nplot);
h_d2=iirA(wplot,d2,U,V,M,Q,R);
subplot(211);
plot(wplot*0.5/pi,20*log10(abs([h_e,h_d2])));
strT=sprintf("Lowpass: fap=%g,Wap=%g,fas=%g,Was=%g",fap,Wap,fas,Was);
title(strT);
xlabel("Frequency");
ylabel("Amplitude(dB)");
axis([0 0.5 -60 5]);
grid("on");
subplot(212);
plot(wplot*0.5/pi,20*log10(abs([h_e,h_d2])));
xlabel("Frequency");
ylabel("Amplitude(dB)");
axis([0 fap -0.02 0]);
grid("on");
print("iir_socp_slb_test_response","-dpdflatex");
close
showZPplot(d2,U,V,M,Q,R,strT)
print("iir_socp_slb_test_pz","-dpdflatex");
close

% Save results
print_pole_zero(x0,U,V,M,Q,R,"x0","iir_socp_slb_test_x0_coef.m");
print_pole_zero(d2,U,V,M,Q,R,"d2","iir_socp_slb_test_d2_coef.m");
save iir_socp_slb_test.mat U V M Q R fap fas x0 d2

% Done 
toc;
diary off
movefile iir_socp_slb_test.diary.tmp iir_socp_slb_test.diary;
