iir_frm_parallel_allpass_socp_slb_test_FIGURES = \
iir_frm_parallel_allpass_socp_slb_test_initial_response \
iir_frm_parallel_allpass_socp_slb_test_initial_passband_response \
iir_frm_parallel_allpass_socp_slb_test_initial_mask_filters \
iir_frm_parallel_allpass_socp_slb_test_initial_mask_response \
iir_frm_parallel_allpass_socp_slb_test_initial_model_response \
iir_frm_parallel_allpass_socp_slb_test_pcls_response \
iir_frm_parallel_allpass_socp_slb_test_pcls_passband_response \
iir_frm_parallel_allpass_socp_slb_test_pcls_mask_response \
iir_frm_parallel_allpass_socp_slb_test_pcls_mask_filters \
iir_frm_parallel_allpass_socp_slb_test_pcls_model_response

iir_frm_parallel_allpass_socp_slb_test_COEFS = \
iir_frm_parallel_allpass_socp_slb_test.mat \
iir_frm_parallel_allpass_socp_slb_test.spec \
iir_frm_parallel_allpass_socp_slb_test_r_coef.m \
iir_frm_parallel_allpass_socp_slb_test_s_coef.m \
iir_frm_parallel_allpass_socp_slb_test_aa_coef.m \
iir_frm_parallel_allpass_socp_slb_test_ac_coef.m 

iir_frm_parallel_allpass_socp_slb_test_FILES = \
iir_frm_parallel_allpass_socp_slb_test.m test_common.m \
iir_frm_parallel_allpass.m \
iir_frm_parallel_allpass_slb.m \
iir_frm_parallel_allpass_slb_constraints_are_empty.m \
iir_frm_parallel_allpass_slb_exchange_constraints.m \
iir_frm_parallel_allpass_slb_set_empty_constraints.m \
iir_frm_parallel_allpass_slb_show_constraints.m \
iir_frm_parallel_allpass_slb_update_constraints.m \
iir_frm_parallel_allpass_socp_mmse.m \
iir_frm_parallel_allpass_socp_slb_plot.m \
iir_frm_parallel_allpass_struct_to_vec.m \
iir_frm_parallel_allpass_vec_to_struct.m \
allpassP.m allpassT.m tf2a.m a2tf.m \
aConstraints.m print_polynomial.m \
local_max.m qroots.m qzsolve.oct 

iir_frm_parallel_allpass_socp_slb_test.diary : \
tarczynski_frm_parallel_allpass_test.diary
