mcclellanFIRsymmetric_multi_band_test_FIGURES = \
mcclellanFIRsymmetric_multi_band_test_response \
mcclellanFIRsymmetric_multi_band_test_dual \
mcclellanFIRsymmetric_multi_band_test_zeros

mcclellanFIRsymmetric_multi_band_test_COEFS = \
mcclellanFIRsymmetric_multi_band_test.mat \
mcclellanFIRsymmetric_multi_band_test.spec \
mcclellanFIRsymmetric_multi_band_test_hM_coef.m \
mcclellanFIRsymmetric_multi_band_test_rho.tab

mcclellanFIRsymmetric_multi_band_test_FILES = \
mcclellanFIRsymmetric_multi_band_test.m test_common.m print_polynomial.m \
mcclellanFIRsymmetric.m local_max.m lagrange_interp.m \
directFIRsymmetricA.m
