mcclellanFIRantisymmetric_flat_differentiator_test_FIGURES = \
mcclellanFIRantisymmetric_flat_differentiator_test_response \
mcclellanFIRantisymmetric_flat_differentiator_test_error \
mcclellanFIRantisymmetric_flat_differentiator_test_dual \
mcclellanFIRantisymmetric_flat_differentiator_test_zeros \
mcclellanFIRantisymmetric_flat_differentiator_test_feasible

mcclellanFIRantisymmetric_flat_differentiator_test_COEFS = \
mcclellanFIRantisymmetric_flat_differentiator_test.mat \
mcclellanFIRantisymmetric_flat_differentiator_test.spec \
mcclellanFIRantisymmetric_flat_differentiator_test_hAM56_coef.m \
mcclellanFIRantisymmetric_flat_differentiator_test_hA56_coef.m \
mcclellanFIRantisymmetric_flat_differentiator_test_hAM57_coef.m \
mcclellanFIRantisymmetric_flat_differentiator_test_hA57_coef.m

mcclellanFIRantisymmetric_flat_differentiator_test_FILES = \
mcclellanFIRantisymmetric_flat_differentiator_test.m test_common.m \
mcclellanFIRantisymmetric_flat_differentiator.m print_polynomial.m local_max.m
