mcclellanFIRsymmetric_lowpass_test_FIGURES = \
mcclellanFIRsymmetric_lowpass_test_response \
mcclellanFIRsymmetric_lowpass_test_dual \
mcclellanFIRsymmetric_lowpass_test_zeros \
mcclellanFIRsymmetric_lowpass_test_extremal

mcclellanFIRsymmetric_lowpass_test_COEFS = \
mcclellanFIRsymmetric_lowpass_test.mat \
mcclellanFIRsymmetric_lowpass_test.spec \
mcclellanFIRsymmetric_lowpass_test_hM_coef.m \
mcclellanFIRsymmetric_lowpass_test_rho.tab

mcclellanFIRsymmetric_lowpass_test_FILES = \
mcclellanFIRsymmetric_lowpass_test.m test_common.m print_polynomial.m \
mcclellanFIRsymmetric.m local_max.m lagrange_interp.m directFIRsymmetricA.m
