parallel_allpass_delay_socp_slb_test_FIGURES = \
parallel_allpass_delay_socp_slb_a0 \
parallel_allpass_delay_socp_slb_a0pz \
parallel_allpass_delay_socp_slb_a1 \
parallel_allpass_delay_socp_slb_a1yy \
parallel_allpass_delay_socp_slb_a1pz

parallel_allpass_delay_socp_slb_test_COEFS = \
parallel_allpass_delay_socp_slb_test.mat \
parallel_allpass_delay_socp_slb_test.spec \
parallel_allpass_delay_socp_slb_test_Da1_coef.m

parallel_allpass_delay_socp_slb_test_FILES = \
parallel_allpass_delay_socp_slb_test.m test_common.m \
parallel_allpass_delayAsq.m \
parallel_allpass_delayT.m \
parallel_allpass_delay_slb.m \
parallel_allpass_delay_slb_constraints_are_empty.m \
parallel_allpass_delay_slb_exchange_constraints.m \
parallel_allpass_delay_slb_set_empty_constraints.m \
parallel_allpass_delay_slb_show_constraints.m \
parallel_allpass_delay_slb_update_constraints.m \
parallel_allpass_delay_socp_mmse.m \
allpassP.m allpassT.m tf2a.m a2tf.m \
aConstraints.m print_polynomial.m local_max.m sedumi_test.diary
