parallel_allpass_socp_slb_flat_delay_test_FIGURES = \
parallel_allpass_socp_slb_flat_delay_ab0 \
parallel_allpass_socp_slb_flat_delay_ab0pz \
parallel_allpass_socp_slb_flat_delay_ab1 \
parallel_allpass_socp_slb_flat_delay_ab1pass \
parallel_allpass_socp_slb_flat_delay_ab1phase \
parallel_allpass_socp_slb_flat_delay_ab1pz \
parallel_allpass_socp_slb_flat_delay_a1pz \
parallel_allpass_socp_slb_flat_delay_b1pz

parallel_allpass_socp_slb_flat_delay_test_COEFS = \
parallel_allpass_socp_slb_flat_delay_test.mat \
parallel_allpass_socp_slb_flat_delay_test.spec \
parallel_allpass_socp_slb_flat_delay_test_a1_coef.m \
parallel_allpass_socp_slb_flat_delay_test_b1_coef.m \
parallel_allpass_socp_slb_flat_delay_test_Da1_coef.m \
parallel_allpass_socp_slb_flat_delay_test_Db1_coef.m \
parallel_allpass_socp_slb_flat_delay_test_Dab1_coef.m \
parallel_allpass_socp_slb_flat_delay_test_Nab1_coef.m

parallel_allpass_socp_slb_flat_delay_test_FILES = \
parallel_allpass_socp_slb_flat_delay_test.m test_common.m \
parallel_allpassAsq.m parallel_allpassT.m parallel_allpass_slb.m \
parallel_allpass_slb_constraints_are_empty.m \
parallel_allpass_slb_exchange_constraints.m \
parallel_allpass_slb_set_empty_constraints.m \
parallel_allpass_slb_show_constraints.m \
parallel_allpass_slb_update_constraints.m \
parallel_allpass_socp_mmse.m allpassP.m allpassT.m tf2a.m a2tf.m \
aConstraints.m print_polynomial.m print_pole_zero.m local_max.m \
sedumi_test.diary
