selesnickFIRsymmetric_lowpass_alternate_test_FIGURES = \
selesnickFIRsymmetric_lowpass_alternate_test_response \
selesnickFIRsymmetric_lowpass_alternate_test_dual

selesnickFIRsymmetric_lowpass_alternate_test_COEFS = \
selesnickFIRsymmetric_lowpass_alternate_test.mat \
selesnickFIRsymmetric_lowpass_alternate_test.spec \
selesnickFIRsymmetric_lowpass_alternate_test_hM_coef.m \
selesnickFIRsymmetric_lowpass_alternate_test_fapx.tab

selesnickFIRsymmetric_lowpass_alternate_test_FILES = \
selesnickFIRsymmetric_lowpass_alternate_test.m test_common.m \
print_polynomial.m selesnickFIRsymmetric_lowpass.m local_max.m \
lagrange_interp.m xfr2tf.m directFIRsymmetricA.m
