socp_relaxation_directFIRhilbert_12_nbits_test_FIGURES = \
socp_relaxation_directFIRhilbert_12_nbits_test_response

socp_relaxation_directFIRhilbert_12_nbits_test_COEFS = \
socp_relaxation_directFIRhilbert_12_nbits_test.mat \
socp_relaxation_directFIRhilbert_12_nbits_test.spec \
socp_relaxation_directFIRhilbert_12_nbits_test_cost.tab \
socp_relaxation_directFIRhilbert_12_nbits_test_hM0_coef.m \
socp_relaxation_directFIRhilbert_12_nbits_test_hM0_sd_coef.m \
socp_relaxation_directFIRhilbert_12_nbits_test_hM0_Ito_sd_coef.m \
socp_relaxation_directFIRhilbert_12_nbits_test_hM_min_adders.tab \
socp_relaxation_directFIRhilbert_12_nbits_test_hM_min_coef.m \
socp_relaxation_directFIRhilbert_12_nbits_test_hM_min_signed_digits.tab

socp_relaxation_directFIRhilbert_12_nbits_test_FILES = \
socp_relaxation_directFIRhilbert_12_nbits_test.m \
test_common.m \
directFIRhilbert_mmsePW.m \
directFIRhilbert_socp_mmsePW.m \
directFIRhilbert_allocsd_Ito.m \
directFIRhilbert_slb.m \
directFIRhilbert_slb_constraints_are_empty.m \
directFIRhilbert_slb_exchange_constraints.m \
directFIRhilbert_slb_set_empty_constraints.m \
directFIRhilbert_slb_show_constraints.m \
directFIRhilbert_slb_update_constraints.m \
directFIRhilbertEsqPW.m \
directFIRhilbertA.m \
print_polynomial.m local_max.m flt2SD.m SDadders.m x2nextra.m bin2SDul.m \
bin2SD.oct bin2SPT.oct sedumi_test.diary
