zolotarev_vlcek_zahradnik_test_FIGURES = \
zolotarev_vlcek_zahradnik_test_p_4_q_11_chen_parks \
zolotarev_vlcek_zahradnik_test_p_4_q_11_isoextremal \
zolotarev_vlcek_zahradnik_test_p_4_q_11_generator \
zolotarev_vlcek_zahradnik_test_p_4_q_11_S \
zolotarev_vlcek_zahradnik_test_p_4_q_11_zero_phase \
zolotarev_vlcek_zahradnik_test_p_4_q_11_response \
zolotarev_vlcek_zahradnik_test_p_100_q_300_response \
zolotarev_vlcek_zahradnik_test_as_120_fp_0_15_response

zolotarev_vlcek_zahradnik_test_COEFS = \
zolotarev_vlcek_zahradnik_test_p_4_q_11_generator_coef.m \
zolotarev_vlcek_zahradnik_test_p_4_q_11_a_coef.m \
zolotarev_vlcek_zahradnik_test_p_4_q_11_h_coef.m \
zolotarev_vlcek_zahradnik_test_p_100_q_300_h_coef.m \
zolotarev_vlcek_zahradnik_test_as_120_fp_0_15_h_coef.m

zolotarev_vlcek_zahradnik_test_FILES = \
zolotarev_vlcek_zahradnik_test.m zolotarev_vlcek_zahradnik.m \
test_common.m zolotarev_chen_parks.m zolotarev_vlcek_unbehauen.m \
elliptic_F.m elliptic_E.m jacobi_Eta.m jacobi_Theta.m jacobi_Zeta.m \
jacobi_theta1.m jacobi_theta1k.m jacobi_theta2.m jacobi_theta2k.m \
jacobi_theta3.m jacobi_theta3k.m jacobi_theta4.m jacobi_theta4k.m \
carlson_RJ.m carlson_RD.m carlson_RC.m carlson_RF.m \
chebychevP.m chebychevT.m chebychevU.m \
chebychevP_backward_recurrence.m chebychevT_backward_recurrence.m \
chebychevU_backward_recurrence.m print_polynomial.m 
